export const types = {
  PLAYING: "PLAYING",
};

export const WAGERING_NOTIFICATION_TYPES = {
  REAL_MONEY_WAGERING: "REAL_MONEY_WAGERING",
  BONUS_MONEY_WAGERING: "BONUS_MONEY_WAGERING",
};

export const CMS_SLUGS = {
  MODAL_WAGERING: "iframe-solution",
};

export const WALLET_BALANCE_DELAY_DURATION = 500;

export const WALLET_BONUS_UNBLOCK_AFTER = 10000;
