export const gameMock = {
  __typename: "Game",
  id: "1",
  name: "Gonzo&#8217;s Quest",
  slug: "gonzos-quest",
  backgroundImage: "https://cms.casumo.com/wp-content/uploads/2014/06/GonzosQuest_Thumb.jpg",
  logo: "https://cms.casumo.com/wp-content/uploads/2014/02/GonzosQuest_Logo.png",
  hasPlayForFun: true,
  isInMaintenance: false,
  jackpotId: null,
  liveCasinoId: null,
  lobby: null,
  gameStudio: "Net Entertainment",
  category: "SLOT_MACHINE",
  playBackground: "https://cms.casumo.com/wp-content/uploads/2012/04/bg1.jpg",
  realMoneyPlayRequired: false,
} as const;
