export default {
  EUR: [
    {
      games: [],
      jackpotId: "netent-gof_mega",
      jackpotType: "Local",
      iso4217CurrencyCode: "EUR",
      jackpotAmount: 234.5678,
      formattedJackpotAmount: "€234.56",
      latestPayoutDate: 1439398212569,
      payoutCount: 0,
      totalJackpotAmountPaidOut: 0.0,
      formattedTotalJackpotAmountPaidOut: "0,00 €",
    },
    {
      games: [],
      jackpotId: "netent-megafortunedreams_mega",
      jackpotType: "Local",
      iso4217CurrencyCode: "EUR",
      jackpotAmount: 111.1111,
      formattedJackpotAmount: "€111.11",
      latestPayoutDate: 1439398212569,
      payoutCount: 0,
      totalJackpotAmountPaidOut: 0.0,
      formattedTotalJackpotAmountPaidOut: "0,00 €",
    },
  ],
  GBP: [
    {
      games: [],
      jackpotId: "netent-gof_mega",
      jackpotType: "Local",
      iso4217CurrencyCode: "GBP",
      jackpotAmount: 567.89,
      formattedJackpotAmount: "£567.89",
      latestPayoutDate: 1439398212569,
      payoutCount: 0,
      totalJackpotAmountPaidOut: 0.0,
      formattedTotalJackpotAmountPaidOut: "0,00 £",
    },
    {
      games: [],
      jackpotId: "netent-megafortunedreams_mega",
      jackpotType: "Local",
      iso4217CurrencyCode: "GBP",
      jackpotAmount: 111.1111,
      formattedJackpotAmount: "£111.11",
      latestPayoutDate: 1439398212569,
      payoutCount: 0,
      totalJackpotAmountPaidOut: 0.0,
      formattedTotalJackpotAmountPaidOut: "0,00 £",
    },
  ],
};
