export default [
  {
    name: "Football",
    id: 1000093190,
    clientPath: "filter/football",
    termKey: "football",
    flagEmoji: null,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/handball.svg",
    canSelectSubgroups: true,
    groups: [
      {
        name: "Champions League",
        id: 1000093381,
        clientPath: "filter/football/champions_league",
        termKey: "champions_league",
        flagEmoji: "🇪🇺",
      },
      {
        name: "Premier League",
        id: 1000094985,
        clientPath: "filter/football/premier_league",
        termKey: "premier_league",
        flagEmoji: null,
      },
      {
        name: "The Championship",
        id: 1000094981,
        clientPath: "filter/football/the_championship",
        termKey: "the_championship",
        flagEmoji: null,
      },
      {
        name: "Europa League",
        id: 2000051195,
        clientPath: "filter/football/europa_league",
        termKey: "europa_league",
        flagEmoji: "🇪🇺",
      },
      {
        name: "Allsvenskan",
        id: 1000095057,
        clientPath: "filter/football/allsvenskan",
        termKey: "allsvenskan",
        flagEmoji: null,
      },
    ],
  },
  {
    name: "Tennis",
    id: 1000093193,
    clientPath: "filter/tennis",
    termKey: "tennis",
    flagEmoji: null,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/tennis.svg",
    canSelectSubgroups: false,
    groups: [
      {
        name: "ATP",
        id: 1000093324,
        clientPath: "filter/tennis/atp",
        termKey: "atp",
        flagEmoji: null,
      },
      {
        name: "WTA",
        id: 1000093904,
        clientPath: "filter/tennis/wta",
        termKey: "wta",
        flagEmoji: null,
      },
      {
        name: "ITF Men",
        id: 2000054086,
        clientPath: "filter/tennis/itf_men",
        termKey: "itf_men",
        flagEmoji: null,
      },
      {
        name: "ITF Women",
        id: 1000462066,
        clientPath: "filter/tennis/itf_women",
        termKey: "itf_women",
        flagEmoji: null,
      },
      {
        name: "ITF Women Doubles",
        id: 2000071266,
        clientPath: "filter/tennis/itf_women_doubles",
        termKey: "itf_women_doubles",
        flagEmoji: null,
      },
    ],
  },
  {
    name: "Golf",
    id: 1000093187,
    clientPath: "filter/golf",
    termKey: "golf",
    flagEmoji: null,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/golf.svg",
    canSelectSubgroups: false,
    groups: [
      {
        name: "PGA Tour",
        id: 1000093683,
        clientPath: "filter/golf/pga_tour",
        termKey: "pga_tour",
        flagEmoji: null,
      },
      {
        name: "European Tour",
        id: 1000093480,
        clientPath: "filter/golf/european_tour",
        termKey: "european_tour",
        flagEmoji: null,
      },
      {
        name: "LPGA Tour",
        id: 1000093598,
        clientPath: "filter/golf/lpga_tour",
        termKey: "lpga_tour",
        flagEmoji: null,
      },
      {
        name: "Champions Tour",
        id: 1000093384,
        clientPath: "filter/golf/champions_tour",
        termKey: "champions_tour",
        flagEmoji: null,
      },
      {
        name: "Web.com",
        id: 2000086150,
        clientPath: "filter/golf/web_com",
        termKey: "web_com",
        flagEmoji: null,
      },
    ],
  },
  {
    name: "Baseball",
    id: 1000093211,
    clientPath: "filter/baseball",
    termKey: "baseball",
    flagEmoji: null,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/baseball.svg",
    canSelectSubgroups: false,
    groups: [
      {
        name: "MLB",
        id: 1000093616,
        clientPath: "filter/baseball/mlb",
        termKey: "mlb",
        flagEmoji: null,
      },
    ],
  },
  {
    name: "Basketball",
    id: 1000093204,
    clientPath: "filter/basketball",
    termKey: "basketball",
    flagEmoji: null,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/basketball.svg",
    canSelectSubgroups: false,
    groups: [
      {
        name: "BBL",
        id: 1000094172,
        clientPath: "filter/basketball/bbl",
        termKey: "bbl",
        flagEmoji: null,
      },
      {
        name: "Euroleague (W)",
        id: 1000174247,
        clientPath: "filter/basketball/euroleague__w_",
        termKey: "euroleague__w_",
        flagEmoji: null,
      },
      {
        name: "NBA",
        id: 1000093652,
        clientPath: "filter/basketball/nba",
        termKey: "nba",
        flagEmoji: null,
      },
      {
        name: "Cup",
        id: 1000215424,
        clientPath: "filter/basketball/cup",
        termKey: "cup",
        flagEmoji: "🇵🇸",
      },
      {
        name: "NCAAB",
        id: 1000093654,
        clientPath: "filter/basketball/ncaab",
        termKey: "ncaab",
        flagEmoji: null,
      },
    ],
  },
  {
    name: "Boxing",
    id: 1000093201,
    clientPath: "filter/boxing",
    termKey: "boxing",
    flagEmoji: null,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/boxing.svg",
    canSelectSubgroups: false,
    groups: [
      {
        name: "Upcoming Fights",
        id: 2000050854,
        clientPath: "filter/boxing/upcoming_fights",
        termKey: "upcoming_fights",
        flagEmoji: null,
      },
      {
        name: "Unconfirmed Fights",
        id: 2000091527,
        clientPath: "filter/boxing/unconfirmed_fights",
        termKey: "unconfirmed_fights",
        flagEmoji: null,
      },
    ],
  },
  {
    name: "Chess",
    id: 1000190837,
    clientPath: "filter/chess",
    termKey: "chess",
    flagEmoji: null,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/chess.svg",
    canSelectSubgroups: false,
    groups: [
      {
        name: "International Tournaments",
        id: 2000050395,
        clientPath: "filter/chess/international_tournaments",
        termKey: "international_tournaments",
        flagEmoji: null,
      },
      {
        name: "Exhibition Matches",
        id: 2000051851,
        clientPath: "filter/chess/exhibition_matches",
        termKey: "exhibition_matches",
        flagEmoji: null,
      },
      {
        name: "Specials",
        id: 2000070243,
        clientPath: "filter/chess/specials",
        termKey: "specials",
        flagEmoji: null,
      },
      {
        name: "World Championship",
        id: 1000190838,
        clientPath: "filter/chess/world_championship",
        termKey: "world_championship",
        flagEmoji: null,
      },
    ],
  },
  {
    name: "Cricket",
    id: 1000093178,
    clientPath: "filter/cricket",
    termKey: "cricket",
    flagEmoji: null,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/cricket.svg",
    canSelectSubgroups: false,
    groups: [
      {
        name: "Pakistan Super League",
        id: 2000092588,
        clientPath: "filter/cricket/pakistan_super_league",
        termKey: "pakistan_super_league",
        flagEmoji: "🇵🇰",
      },
      {
        name: "T20 Big Bash League",
        id: 2000068063,
        clientPath: "filter/cricket/t20_big_bash_league",
        termKey: "t20_big_bash_league",
        flagEmoji: null,
      },
      {
        name: "International Test Cricket",
        id: 2000085729,
        clientPath: "filter/cricket/international_test_cricket",
        termKey: "international_test_cricket",
        flagEmoji: null,
      },
      {
        name: "International One Day",
        id: 2000085728,
        clientPath: "filter/cricket/international_one_day",
        termKey: "international_one_day",
        flagEmoji: null,
      },
      {
        name: "Momentum One Day Cup",
        id: 2000064800,
        clientPath: "filter/cricket/momentum_one_day_cup",
        termKey: "momentum_one_day_cup",
        flagEmoji: null,
      },
    ],
  },
  {
    name: "Darts",
    id: 1000093225,
    clientPath: "filter/darts",
    termKey: "darts",
    flagEmoji: null,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/darts.svg",
    canSelectSubgroups: false,
    groups: [
      {
        name: "Unibet Premier League of Darts",
        id: 1000093703,
        clientPath: "filter/darts/unibet_premier_league_of_darts",
        termKey: "unibet_premier_league_of_darts",
        flagEmoji: null,
      },
      {
        name: "PDC World Championship",
        id: 1000093681,
        clientPath: "filter/darts/pdc_world_championship",
        termKey: "pdc_world_championship",
        flagEmoji: null,
      },
    ],
  },
  {
    name: "Esports",
    id: 2000077768,
    clientPath: "filter/esports",
    termKey: "esports",
    flagEmoji: null,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/e-sports.svg",
    canSelectSubgroups: false,
    groups: [
      {
        name: "LCK",
        id: 2000117181,
        clientPath: "filter/esports/lck",
        termKey: "lck",
        flagEmoji: null,
      },
      {
        name: "Intel Extreme Masters",
        id: 2000116832,
        clientPath: "filter/esports/intel_extreme_masters",
        termKey: "intel_extreme_masters",
        flagEmoji: null,
      },
      {
        name: "CWL Pro League",
        id: 2000115520,
        clientPath: "filter/esports/cwl_pro_league",
        termKey: "cwl_pro_league",
        flagEmoji: null,
      },
      {
        name: "United Masters League",
        id: 2000117776,
        clientPath: "filter/esports/united_masters_league",
        termKey: "united_masters_league",
        flagEmoji: null,
      },
      {
        name: "ESEA Premier EU",
        id: 2000116651,
        clientPath: "filter/esports/esea_premier_eu",
        termKey: "esea_premier_eu",
        flagEmoji: null,
      },
    ],
  },
  {
    name: "Floorball",
    id: 1000093206,
    clientPath: "filter/floorball",
    termKey: "floorball",
    flagEmoji: null,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/floorball.svg",
    canSelectSubgroups: false,
    groups: [
      {
        name: "Superligan",
        id: 1000094957,
        clientPath: "filter/floorball/superligan",
        termKey: "superligan",
        flagEmoji: null,
      },
      {
        name: "Salibandyliiga",
        id: 1000094956,
        clientPath: "filter/floorball/salibandyliiga",
        termKey: "salibandyliiga",
        flagEmoji: null,
      },
      {
        name: "Superligan (W)",
        id: 2000060789,
        clientPath: "filter/floorball/superligan__w_",
        termKey: "superligan__w_",
        flagEmoji: null,
      },
    ],
  },
];
