import * as A from "Types/apollo";

export const t = {
  schedule_tab_title: "Full Schedule",
  previous_winners_tab_title: "Previous Winners",
  mobile_promoted_race_title_single: "Previous Winners",
  mobile_race_title_single: "Previous Winners",
  today: "Today",
  tomorrow: "Tomorrow",
  points_template: "string",
  right_now: "string",
  up_next: "string",
  later_today: "string",
  show_prizes_button: "string",
  hide_prizes_button: "string",
  hide_leaderboard_button: "string",
  show_leaderboard_button: "string",
  show_more_reel_races: "string",
  leaderboard_rank: "string",
} as const;

export const reelRacesSchedule: Array<A.ReelRaceScheduleCard_ReelRaceFragment> = [
  {
    id: "ca8e6f20-7514-11eb-9c3c-9a248007d6f0",
    game: {
      id: "17c617cd-f752-42cd-b92b-2dd6fea0174f",
      slug: "buffalo-hunter",
      name: "Buffalo Hunter",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2020/08/Buffalo_Hunter_Thumbnail_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2020/08/Buffalo_Hunter_Thumbnail_BG.png",
    },
    startTime: 1614252600000,
    endTime: 1614254100000,
    optedIn: false,
    status: "Started",
    spinLimit: 180,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "ca976fd0-7514-11eb-9c3c-9a248007d6f0",
    game: {
      id: "755c5170-62d5-11e7-86a4-005056a15ead",
      slug: "vikings-go-berzerk",
      name: "Vikings Go Berzerk",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2017/06/vikings_go_berzerk_logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2017/06/vikings_go_berzerk_bg.jpg",
    },
    startTime: 1614254400000,
    endTime: 1614255900000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 140,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "ca98f670-7514-11eb-9c3c-9a248007d6f0",
    game: {
      id: "063fefca-9dd0-11e5-8960-0050568c183b",
      slug: "big-bad-wolf",
      name: "Big Bad Wolf",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2015/08/bigbadwolf_logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2015/08/bigbadwolfbgthumb.jpg",
    },
    startTime: 1614256200000,
    endTime: 1614257700000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 140,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "caa85fc0-7514-11eb-9c3c-9a248007d6f0",
    game: {
      id: "e6ca9b90-0f8b-11ea-bdb1-0242ac110003",
      slug: "finns-golden-tavern",
      name: "Finn's Golden Tavern",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2019/11/finn_s_golden_tavern_Thumbnail_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2019/11/finn_s_golden_tavern_Thumbnail_BG.png",
    },
    startTime: 1614258000000,
    endTime: 1614259500000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 190,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "caaa0d70-7514-11eb-9c3c-9a248007d6f0",
    game: {
      id: "fd304e80-2e34-11ea-9ec2-0242ac110003",
      slug: "jewel-scarabs",
      name: "Jewel Scarabs",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2019/12/jewel_Scarabs_Thumbnail_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2019/12/jewel_Scarabs_Thumbnail_BG.png",
    },
    startTime: 1614259800000,
    endTime: 1614261300000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 200,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "cab30e20-7514-11eb-9c3c-9a248007d6f0",
    game: {
      id: "0154c8c6-6c57-4b31-8ee6-c361ac1dab4b",
      slug: "tiki-tumble",
      name: "Tiki Tumble",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2018/02/tiki_tumble_logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2018/02/tiki_tumble_thumbnail.jpg",
    },
    startTime: 1614261600000,
    endTime: 1614263100000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 230,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "cabaaf40-7514-11eb-9c3c-9a248007d6f0",
    game: {
      id: "3601f4da-55d6-4809-864b-863db7c4fdb1",
      slug: "the-dog-house",
      name: "The Dog House",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2019/05/the_dog_house_logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2019/05/the_dog_house_thumbnail.jpg",
    },
    startTime: 1614263400000,
    endTime: 1614264900000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 230,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "cac18d10-7514-11eb-9c3c-9a248007d6f0",
    game: {
      id: "b0950981-0580-4c4c-9bc7-f4b14fb2a173",
      slug: "fat-rabbit",
      name: "Fat Rabbit",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2018/03/fat_rabbit_logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2018/03/fat_rabbit_thumbnail.jpg",
          },
    startTime: 1614265200000,
    endTime: 1614266700000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 200,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "caccfec0-7514-11eb-9c3c-9a248007d6f0",
    game: {
      id: "1a59a230-d037-11e7-83ec-005056a15ead",
      slug: "finn-and-the-swirly-spin",
      name: "Finn and the Swirly Spin",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2017/11/finn_and_the_swirlly_logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2017/11/finn_and_the_swirlly_thumbnail.jpg",
    },
    startTime: 1614267000000,
    endTime: 1614268500000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 140,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "cad403a0-7514-11eb-9c3c-9a248007d6f0",
    game: {
      id: "4a694fc0-0adc-11ea-9a43-0242ac110003",
      slug: "sword-of-khans",
      name: "Sword of Khans",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2019/11/Sword_of_khans_Thumbnail_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2019/11/Sword_of_khans_Thumbnail_BG.png",
    },
    startTime: 1614268800000,
    endTime: 1614270300000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 240,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "cadaba60-7514-11eb-9c3c-9a248007d6f0",
    game: {
      id: "1aea4280-81a0-11e7-a864-005056a15ead",
      slug: "sticky-bandits",
      name: "Sticky Bandits",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2017/08/sticky_bandits_logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2017/08/sticky_bandits_thumbnail.jpg",
    },
    startTime: 1614270600000,
    endTime: 1614272100000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 210,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "cae60500-7514-11eb-9c3c-9a248007d6f0",
    game: {
      id: "9f349190-1b44-11ea-888e-0242ac110003",
      slug: "divine-showdown",
      name: "Divine Showdown",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2019/12/Divine_showdown_Thumbnail_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2019/12/Divine_showdown_Thumbnail_BG.png",
    },
    startTime: 1614272400000,
    endTime: 1614275400000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 230,
    promoted: false,
    formattedPrize: "£100",
    formattedPrizes: [
      "£100",
      "£50",
      "£30",
      "£20",
      "£10",
      "£10",
      "£10",
      "£5",
      "£5",
      "£5",
    ],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "caece2d0-7514-11eb-9c3c-9a248007d6f0",
    game: {
      id: "7034e400-62d5-11e7-86a4-005056a15ead",
      slug: "vikings-go-wild",
      name: "Vikings Go Wild",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2017/06/vikings_go_wild_logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2017/06/vikings_go_wild_bg.jpg",
    },
    startTime: 1614276000000,
    endTime: 1614279000000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 425,
    promoted: false,
    formattedPrize: "£100",
    formattedPrizes: [
      "£100",
      "£50",
      "£30",
      "£20",
      "£10",
      "£10",
      "£10",
      "£5",
      "£5",
      "£5",
    ],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "cb0e2670-7514-11eb-9c3c-9a248007d6f0",
    game: {
      id: "0a6c1ae8-111d-45b8-967b-366dd0178d21",
      slug: "ring-of-odin",
      name: "Ring of Odin",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2020/04/Ring_of_odin_Thumbnail_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2020/04/Ring_of_odin_Thumbnail_BG.png",
    },
    startTime: 1614283200000,
    endTime: 1614286200000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 400,
    promoted: false,
    formattedPrize: "£250",
    formattedPrizes: [
      "£250",
      "£100",
      "£50",
      "£25",
      "£25",
      "£10",
      "£10",
      "£10",
      "£10",
      "£10",
    ],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "cb1ca560-7514-11eb-9c3c-9a248007d6f0",
    game: {
      id: "7a9c91c0-1def-11e7-9dd7-005056a15ead",
      slug: "sakura-fortune",
      name: "Sakura Fortune",
      logo: "https://cms.casumo.com/wp-content/uploads/2017/09/sakura-logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2017/09/sakura-bg.jpg",
    },
    startTime: 1614286800000,
    endTime: 1614289800000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 500,
    promoted: false,
    formattedPrize: "£250",
    formattedPrizes: [
      "£250",
      "£100",
      "£50",
      "£25",
      "£25",
      "£10",
      "£10",
      "£10",
      "£10",
      "£10",
    ],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "cb322930-7514-11eb-9c3c-9a248007d6f0",
    game: {
      id: "a1e57960-ef55-11e9-8e4b-0242ac110003",
      slug: "honey-rush",
      name: "Honey Rush",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2019/10/honey_rush_Thumbnail_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2019/10/honey_rush_Thumbnail_BG.png",
    },
    startTime: 1614290400000,
    endTime: 1614293400000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 400,
    promoted: false,
    formattedPrize: "£100",
    formattedPrizes: [
      "£100",
      "£50",
      "£30",
      "£20",
      "£10",
      "£10",
      "£10",
      "£5",
      "£5",
      "£5",
    ],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "f41178a0-75dd-11eb-9c3c-9a248007d6f0",
    game: {
      id: "9f349190-1b44-11ea-888e-0242ac110003",
      slug: "divine-showdown",
      name: "Divine Showdown",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2019/12/Divine_showdown_Thumbnail_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2019/12/Divine_showdown_Thumbnail_BG.png",
    },
    startTime: 1614294000000,
    endTime: 1614295500000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 230,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "f4179320-75dd-11eb-9c3c-9a248007d6f0",
    game: {
      id: "b0950981-0580-4c4c-9bc7-f4b14fb2a173",
      slug: "fat-rabbit",
      name: "Fat Rabbit",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2018/03/fat_rabbit_logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2018/03/fat_rabbit_thumbnail.jpg",
    },
    startTime: 1614295800000,
    endTime: 1614297300000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 200,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "f42eebb0-75dd-11eb-9c3c-9a248007d6f0",
    game: {
      id: "5ffb7480-8ef7-11e6-894c-005056a15ead",
      slug: "starburst",
      name: "Starburst",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2020/04/Starburst_Thumbnail_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2020/04/Starburst_Thumbnail_BG.png",
    },
    startTime: 1614297600000,
    endTime: 1614299100000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 240,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "f43665c0-75dd-11eb-9c3c-9a248007d6f0",
    game: {
      id: "de6d6350-af52-11e8-8c23-0242ac110003",
      slug: "jaguar-temple",
      name: "Jaguar Temple",
      logo: "https://cms.casumo.com/wp-content/uploads/2018/08/logo-jaguar.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2018/08/back-jaguar.png",
    },
    startTime: 1614299400000,
    endTime: 1614300900000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 200,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "f43d91b0-75dd-11eb-9c3c-9a248007d6f0",
    game: {
      id: "3601f4da-55d6-4809-864b-863db7c4fdb1",
      slug: "the-dog-house",
      name: "The Dog House",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2019/05/the_dog_house_logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2019/05/the_dog_house_thumbnail.jpg",
    },
    startTime: 1614301200000,
    endTime: 1614302700000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 230,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "f44a62f0-75dd-11eb-9c3c-9a248007d6f0",
    game: {
      id: "fa553c80-65ca-11e9-822d-0242ac110003",
      slug: "dead-or-alive-2",
      name: "Dead or Alive 2",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2019/04/dead_or_alive_logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2019/04/dead_or_alive_thumbnail.jpg",
    },
    startTime: 1614303000000,
    endTime: 1614304500000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 180,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "f451b5f0-75dd-11eb-9c3c-9a248007d6f0",
    game: {
      id: "fa9b16b0-d479-11e9-bf63-0242ac110003",
      slug: "dragon-fire-megaways",
      name: "Dragon's Fire: Megaways",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2019/09/dragon_s_fire_Thumbnail_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2019/09/dragon_s_fire_Thumbnail_BG.png",
    },
    startTime: 1614304800000,
    endTime: 1614306300000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 180,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "f458bad0-75dd-11eb-9c3c-9a248007d6f0",
    game: {
      id: "17c617cd-f752-42cd-b92b-2dd6fea0174f",
      slug: "buffalo-hunter",
      name: "Buffalo Hunter",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2020/08/Buffalo_Hunter_Thumbnail_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2020/08/Buffalo_Hunter_Thumbnail_BG.png",
    },
    startTime: 1614306600000,
    endTime: 1614308100000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 180,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "f45fbfb0-75dd-11eb-9c3c-9a248007d6f0",
    game: {
      id: "a2c1d6d0-b3e3-11e7-aea3-005056a15ead",
      slug: "pink-elephants",
      name: "Pink Elephants",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2017/09/pink_elephants_logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2017/09/pink_elephants_thumbnail.jpg",
    },
    startTime: 1614308400000,
    endTime: 1614309900000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 170,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "f4669d80-75dd-11eb-9c3c-9a248007d6f0",
    game: {
      id: "f270de9d-ddf1-42ca-b872-82c111c5f5c1",
      slug: "razor-shark",
      name: "Razor Shark",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2019/08/razor_shark_Thumbnail_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2019/08/razor_shark_Thumbnail_BG.png",
    },
    startTime: 1614310200000,
    endTime: 1614311700000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 200,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "f4723640-75dd-11eb-9c3c-9a248007d6f0",
    game: {
      id: "d58add20-8ef8-11e6-894c-005056a15ead",
      slug: "piggy-riches",
      name: "Piggy Riches",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2014/02/PiggyRiches_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2014/06/PiggyRiches_Thumb.jpg",
    },
    startTime: 1614312000000,
    endTime: 1614313500000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 160,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "f47829b0-75dd-11eb-9c3c-9a248007d6f0",
    game: {
      id: "33672f32-d87e-11e9-8f11-0242ac110003",
      slug: "the-wild-chase-tokyo-go",
      name: "The Wild Chase: Tokyo Go",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2019/09/wild_chase_tokyo_go_Thumbnail_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2019/09/wild_chase_tokyo_go_Thumbnail_BG.png",
    },
    startTime: 1614313800000,
    endTime: 1614315300000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 140,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "f484faf0-75dd-11eb-9c3c-9a248007d6f0",
    game: {
      id: "0a6c1ae8-111d-45b8-967b-366dd0178d21",
      slug: "ring-of-odin",
      name: "Ring of Odin",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2020/04/Ring_of_odin_Thumbnail_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2020/04/Ring_of_odin_Thumbnail_BG.png",
    },
    startTime: 1614315600000,
    endTime: 1614317100000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 200,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
  {
    id: "f48bb1b0-75dd-11eb-9c3c-9a248007d6f0",
    game: {
      id: "35091e40-c418-11e9-991a-0242ac110003",
      slug: "riders-of-the-storm",
      name: "Riders of the Storm",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2019/08/riders_of_the_storm_Thumbnail_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2019/08/riders_of_the_storm_Thumbnail_BG.png",
    },
    startTime: 1614317400000,
    endTime: 1614318900000,
    optedIn: false,
    status: "Scheduled",
    spinLimit: 210,
    promoted: false,
    formattedPrize: "£20",
    formattedPrizes: ["£20", "£10", "£5"],
    translations: {
      optIn: "Opt in",
      optedIn: "Opted in",
      startingIn: "Starts:",
      spins: "Spins",
      duration: "Duration",
      durationTemplate: "{{{duration}}} min",
      caveatShort:
        'Opt in. Spins/Games restrictions. <a href="#" {{{ ctaTermsAndConditions }}}><strong>T&C’s apply.</strong></a>',
      today: "Today",
      tomorrow: "Tomorrow",
    },
  },
];

export const reelRacesPrevious: Array<A.ReelRacePreviousCard_ReelRaceFragment> = [
  {
    id: "ca834b90-7514-11eb-9c3c-9a248007d6f0",
    game: {
      name: "Jack and the Beanstalk",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2014/02/JackOfTheBeanstalk_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2014/06/JackOfTheBeanstalk_Thumb.jpg",
    },
    startTime: 1614249000000,
    endTime: 1614250500000,
    formattedPrizes: ["£20", "£10", "£5"],
    leaderboard: [
      {
        playerName: "Peluri64",
        position: 1,
        points: 408,
      },
      {
        playerName: "Kriz_DK",
        position: 2,
        points: 328,
      },
      {
        playerName: "Kikka18",
        position: 3,
        points: 314,
      },
      {
        playerName: "rosa991",
        position: 4,
        points: 279,
      },
      {
        playerName: "annalisa199019",
        position: 5,
        points: 277,
      },
      {
        playerName: "niilou",
        position: 6,
        points: 246,
      },
      {
        playerName: "Musalu",
        position: 7,
        points: 209,
      },
      {
        playerName: "NG23",
        position: 8,
        points: 208,
      },
      {
        playerName: "jahandor",
        position: 9,
        points: 201,
      },
      {
        playerName: "kaffefugl",
        position: 10,
        points: 145,
      },
      {
        playerName: "jsnakes",
        position: 11,
        points: 137,
      },
      {
        playerName: "jenn101105",
        position: 12,
        points: 123,
      },
      {
        playerName: "Teuwo82",
        position: 13,
        points: 121,
      },
      {
        playerName: "KatalaKetku",
        position: 14,
        points: 112,
      },
      {
        playerName: "Vilmaveera",
        position: 15,
        points: 110,
      },
      {
        playerName: "Ormilol",
        position: 16,
        points: 104,
      },
      {
        playerName: "gocart",
        position: 17,
        points: 102,
      },
      {
        playerName: "Natalie388",
        position: 18,
        points: 99,
      },
      {
        playerName: "Sammytommi",
        position: 19,
        points: 97,
      },
      {
        playerName: "59occu",
        position: 20,
        points: 69,
      },
      {
        playerName: "Jennygog187",
        position: 21,
        points: 63,
      },
      {
        playerName: "PanzerRabbit",
        position: 22,
        points: 58,
      },
      {
        playerName: "Schlinda",
        position: 23,
        points: 44,
      },
      {
        playerName: "SmokeDaRoach",
        position: 24,
        points: 34,
      },
      {
        playerName: "julieu8686",
        position: 25,
        points: 32,
      },
      {
        playerName: "ines89",
        position: 26,
        points: 29,
      },
      {
        playerName: "Sarry1989",
        position: 27,
        points: 22,
      },
      {
        playerName: "Wester0s",
        position: 28,
        points: 0,
      },
      {
        playerName: "ezcash",
        position: 29,
        points: 0,
      },
      {
        playerName: "moideenjasid",
        position: 30,
        points: 0,
      },
      {
        playerName: "jol69",
        position: 31,
        points: 0,
      },
      {
        playerName: "loona0068",
        position: 32,
        points: 0,
      },
      {
        playerName: "yvanberthelot9",
        position: 33,
        points: 0,
      },
      {
        playerName: "Gil200",
        position: 34,
        points: 0,
      },
      {
        playerName: "fssa811",
        position: 35,
        points: 0,
      },
      {
        playerName: "Ikkies",
        position: 36,
        points: 0,
      },
      {
        playerName: "rayzz6969",
        position: 37,
        points: 0,
      },
      {
        playerName: "Nadz78695",
        position: 38,
        points: 0,
      },
    ],
  },
  {
    id: "ca8cc170-7514-11eb-9c3c-9a248007d6f0",
    game: {
      name: "Eastern Emeralds",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2018/06/eastern_emeralds_logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2018/06/eastern_emeralds_thumbnail.jpg",
    },
    startTime: 1614250800000,
    endTime: 1614252300000,
    formattedPrizes: ["£20", "£10", "£5"],
    leaderboard: [
      {
        playerName: "jsnakes",
        position: 1,
        points: 498,
      },
      {
        playerName: "anonymouz",
        position: 2,
        points: 487,
      },
      {
        playerName: "Peluri64",
        position: 3,
        points: 475,
      },
      {
        playerName: "Kikka18",
        position: 4,
        points: 418,
      },
      {
        playerName: "Elaine34",
        position: 5,
        points: 414,
      },
      {
        playerName: "59occu",
        position: 6,
        points: 404,
      },
      {
        playerName: "reinikka7",
        position: 7,
        points: 395,
      },
      {
        playerName: "NG23",
        position: 8,
        points: 317,
      },
      {
        playerName: "kaffefugl",
        position: 9,
        points: 309,
      },
      {
        playerName: "Kriz_DK",
        position: 10,
        points: 297,
      },
      {
        playerName: "Nunavute",
        position: 11,
        points: 273,
      },
      {
        playerName: "jahandor",
        position: 12,
        points: 271,
      },
      {
        playerName: "NickWard13",
        position: 13,
        points: 257,
      },
      {
        playerName: "Musalu",
        position: 14,
        points: 250,
      },
      {
        playerName: "Teuwo82",
        position: 15,
        points: 229,
      },
      {
        playerName: "ogonao",
        position: 16,
        points: 226,
      },
      {
        playerName: "annalisa199019",
        position: 17,
        points: 217,
      },
      {
        playerName: "julieu8686",
        position: 18,
        points: 213,
      },
      {
        playerName: "daffykuh",
        position: 19,
        points: 211,
      },
      {
        playerName: "ryuji1234",
        position: 20,
        points: 171,
      },
      {
        playerName: "MAAHINE",
        position: 21,
        points: 148,
      },
      {
        playerName: "ManojSharma0007",
        position: 22,
        points: 135,
      },
      {
        playerName: "emilrisberg",
        position: 23,
        points: 92,
      },
      {
        playerName: "loona0068",
        position: 24,
        points: 86,
      },
      {
        playerName: "Ehjax1978",
        position: 25,
        points: 72,
      },
      {
        playerName: "Vilmaveera",
        position: 26,
        points: 60,
      },
      {
        playerName: "niilou",
        position: 27,
        points: 57,
      },
      {
        playerName: "mole4",
        position: 28,
        points: 54,
      },
      {
        playerName: "Indy85",
        position: 29,
        points: 21,
      },
      {
        playerName: "loke_",
        position: 30,
        points: 16,
      },
      {
        playerName: "SmokeDaRoach",
        position: 31,
        points: 12,
      },
      {
        playerName: "Natalie388",
        position: 32,
        points: 10,
      },
      {
        playerName: "Kirito2021",
        position: 33,
        points: 0,
      },
      {
        playerName: "Wester0s",
        position: 34,
        points: 0,
      },
      {
        playerName: "ezcash",
        position: 35,
        points: 0,
      },
      {
        playerName: "LauraDiona",
        position: 36,
        points: 0,
      },
      {
        playerName: "moideenjasid",
        position: 37,
        points: 0,
      },
      {
        playerName: "jol69",
        position: 38,
        points: 0,
      },
      {
        playerName: "Ormilol",
        position: 39,
        points: 0,
      },
      {
        playerName: "icetee",
        position: 40,
        points: 0,
      },
      {
        playerName: "Ikkies",
        position: 41,
        points: 0,
      },
      {
        playerName: "Kaasdrengen",
        position: 42,
        points: 0,
      },
      {
        playerName: "Nadz78695",
        position: 43,
        points: 0,
      },
    ],
  },
  {
    id: "ca8e6f20-7514-11eb-9c3c-9a248007d6f0",
    game: {
      name: "Buffalo Hunter",
      logo:
        "https://cms.casumo.com/wp-content/uploads/2020/08/Buffalo_Hunter_Thumbnail_Logo.png",
      backgroundImage:
        "https://cms.casumo.com/wp-content/uploads/2020/08/Buffalo_Hunter_Thumbnail_BG.png",
    },
    startTime: 1614252600000,
    endTime: 1614254100000,
    formattedPrizes: ["£20", "£10", "£5"],
    leaderboard: [
      {
        playerName: "reinikka7",
        position: 1,
        points: 329,
      },
      {
        playerName: "icetee",
        position: 2,
        points: 312,
      },
      {
        playerName: "Teuwo82",
        position: 3,
        points: 300,
      },
      {
        playerName: "ryuji1234",
        position: 4,
        points: 248,
      },
      {
        playerName: "LauraDiona",
        position: 5,
        points: 238,
      },
      {
        playerName: "Nunavute",
        position: 6,
        points: 223,
      },
      {
        playerName: "Peluri64",
        position: 7,
        points: 217,
      },
      {
        playerName: "TurboSi",
        position: 8,
        points: 210,
      },
      {
        playerName: "59occu",
        position: 9,
        points: 129,
      },
      {
        playerName: "MAAHINE",
        position: 10,
        points: 121,
      },
      {
        playerName: "gocart",
        position: 11,
        points: 116,
      },
      {
        playerName: "loona0068",
        position: 12,
        points: 94,
      },
      {
        playerName: "stefanke",
        position: 13,
        points: 84,
      },
      {
        playerName: "Ester12345",
        position: 14,
        points: 48,
      },
      {
        playerName: "Ehjax1978",
        position: 15,
        points: 29,
      },
      {
        playerName: "manu1811",
        position: 16,
        points: 20,
      },
      {
        playerName: "chasmarcel",
        position: 17,
        points: 16,
      },
      {
        playerName: "Wester0s",
        position: 18,
        points: 0,
      },
      {
        playerName: "ezcash",
        position: 19,
        points: 0,
      },
      {
        playerName: "moideenjasid",
        position: 20,
        points: 0,
      },
      {
        playerName: "jahandor",
        position: 21,
        points: 0,
      },
      {
        playerName: "ManojSharma0007",
        position: 22,
        points: 0,
      },
      {
        playerName: "destiny124",
        position: 23,
        points: 0,
      },
      {
        playerName: "boguslaw86",
        position: 24,
        points: 0,
      },
      {
        playerName: "Jess_24",
        position: 25,
        points: 0,
      },
    ],
  },
];
