// @flow

const changelog = `1.3 Cambiar a la cantidad de giros gratis ofrecidos
1.6 Oferta de bienvenida actualizada
2.12 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
13.4 Cambiar a términos de bonificación`;

const content = `<h4>1. General</h4>
  <p>1.1. The Terms and Conditions defined in this text regulate the usage of the games provided through www.casumo.com, as well as other URLs licensed to or belonging to Casumo Services Limited (hereinafter referred to as “Website” or “Websites”). These Terms and Conditions, the Game Rules and any document expressly referred to in them, as well as any guidelines or rules posted on the Website constitute the agreement and understanding between the Parties and govern the contractual relationship between Casumo and the Account Holder. Please read these Terms and Conditions carefully and make sure you understand them. Should you not agree with their contents, please refrain from using this Website any further. These Terms and Conditions shall also apply to all gaming made via mobile devices, including downloadable applications. We also recommend that you familiarise yourself with our Privacy Notice. All references to the use of the Website shall be construed as references to the use of our betting facilities for mobile devices.</p>
  <p>1.2. Casumo Services Limited is a company incorporated under the laws of Malta with company registration number C55663, and having its registered address at The Unicorn Centre, Triq il-Uqija, Swieqi, SWQ 2335, Malta.</p>
  <p>1.3.1. Casumo Services Limited is licensed and regulated by the Malta Gaming Authority (“MGA”) to offer type 1 gaming services under licence reference number MGA/B2C/217/2012, valid until 4th September 2027.</p>
  <p>1.3.2. Games provided by the following game providers are licensed and regulated by MGA under the following service provider licences:</p>
  <p>(i) Games provided by Evolution are offered under licence number MGA/B2B/187/2010.</p>
  <p>(ii) Games provided by Greentube Malta Limited are offered under licence number MGA/B2B/120/2006.</p>
  <p>(iii) Games provided by Microgaming Europe Limited are offered under licence number MGA/B2B/139/2007.</p>
  <p>(iv) Games provided by NetEnt Malta Limited are offered under licence number MGA/B2B/109/2004.</p>
  <p>(v) Games provided by NYX Digital Gaming (Malta) Limited are offered under licence number MGA/B2B/112/2004.</p>
  <p>(vi) Games provided by Play&#8217;n Go Malta Limited are offered under licence number MGA/B2B/225/2012.</p>
  <p>(vii) Games provided by Relax Gaming Limited are offered under licence number MGA/B2B/246/2013.</p>
  <p>(viii) Games provided by Thunderkick Malta Limited are offered under licence number MGA/B2B/248/2013.</p>
  <p>(ix) Games provided by Yggdrasil Gaming Limited are offered under licence number MGA/B2B/230/2012.</p>
  <p>(x) Games provided by Casumo Games Limited are offered under licence number MGA/B2B/440/2017.</p>
  <p>(xi) Games provided by Red Tiger Malta Limited are offered under licence number MGA/B2B/480/2018.</p>
  <p>(xii) Games provided by Edict Malta Limited are offered under licence number MGA/B2B/336/2016.</p>
  <p>1.3.3 Games provided by the following game providers are licensed and regulated by gambling authorities outside Malta:</p>
  <p>(i) Games provided by IGT are licensed and regulated in Great Britain under Licence Number 000-041794-R-320803-016.</p>
  <p>1.4. Casumo Services Limited is here referred to as “Casumo”, “We”, “Us” or “Our” and the Player and registered Account Holder shall be referred to as “You”, “Yours”, “User” or “the Player”, as and where appropriate.</p>
  <p>1.5. “Games”, “the Games” or “Game” refers to any of the gaming products offered on the Websites.</p>
  <p>1.6. The version of this agreement is currently Version 2.9 and was last updated on the 14th May 2019. It is valid until a new version is in place on the Websites and is accepted by the Player.</p>
  <p>1.7. These Terms and Conditions also apply to all platforms and devices that enable game play of games provided by Casumo. ‘Games’ are defined as Casino and other games, which are available on the Website.</p>
  <p>1.8. Casumo reserves the right to modify these Terms and Conditions from time to time for a number of reasons, including to comply with applicable laws and regulations, as well as other regulatory requirements, consequently we may amend this agreement between you and Casumo at any time. Nevertheless, whenever a substantial amendment is made to the Terms and Conditions, we will notify you via a notice on the Website upon account login and prior to the terms coming into effect. You will then be required to re-confirm your acceptance of the contents therein. If you do not agree to the updated Terms and Conditions you will no longer be able to play on our Website. The full Terms and Conditions are available on the front page of the Website at all times. It is always recommended to check the Terms and Conditions from time to time to ensure that you agree with them. All versions are dated and time stamped.</p>
  <p>1.9. Such amendments will become effective immediately upon being posted on www.casumo.com. It is your sole responsibility to review this Agreement, together with the specific Rules for each Game you choose to participate in, in order to remain updated with all amendments each time you play. You can easily identify whether these Terms and Conditions have changed by referring to the version number and the date, which are stated under clause 1.6. Moreover, it is always advisable to review these Terms and Conditions and any respective rules of the games you participate in, on a regular basis and not less than once a month, so as to not forget their contents.</p>
  <p>1.10. You must read and understand these Terms and Conditions fully before registering an account with us. Should you not agree with any part of this agreement, you must not use or continue to use the Websites.</p>
  <p>1.11. These Terms and Conditions become applicable when you register and confirm your registration details in the registration process on the Website. By registering an account with Casumo, you agree that you have read and understood these Terms and Conditions. By using any of the Websites you signify that you have accepted and agreed to the contents contained therein.</p>
  <p>1.12.You understand and agree to be bound by the clauses contained in this text, as may be amended from time to time. You further acknowledge that by registering and using the Website or any other Website that we own, you are also bound by the Game rules, and it is deemed that you have read, understood and accepted all such rules and terms. We also recommend that you familiarise yourself with our Privacy Notice.</p>
  <p>1.13. These Terms and Conditions may be published in a number of languages and shall reflect the same principles. This is done for information purposes and to help players. It is however only the English version that is the legal basis of the relationship between you and Casumo. In case of any discrepancy between the English version and the non-English version of these Terms and Conditions, the English version shall always prevail.</p>
  <h4>2. Your Obligations</h4>
  <p>2.1. You may only open one account on each of the Websites provided by us. Casumo retains the right to terminate any duplicate account.</p>
  <p>2.2. If you open or attempt to open more than one account, for whatever reason, Casumo may block or close any or all of your accounts at its discretion. Casumo may also at its discretion void all the bets that have been placed in the duplicate accounts. Should Casumo decide to leave one account open, it will be the first account that you opened with Casumo, to which your remaining deposits, if any, will be transferred. Casumo will deduct an administrative fee of 10% (minimum EUR 30) for every other account you opened as well as any other deductions that may apply in accordance with the provisions of these Terms and Conditions.</p>
  <p>2.3. You declare that you are over 18 years of age or comply with a higher minimum legal age as stipulated in the jurisdiction of your residence under the laws applicable to you. It is your sole responsibility to know whether online gambling is legal in your country of residence. It is a criminal offence to gamble whilst being under age.</p>
  <p>2.4. You are solely responsible for your account details. This includes but shall not be limited to the username and password and/or any other means to access your account via the respective Website. In the case there is a suspicion that such information should have been compromised, you must inform Casumo and take proper actions to prohibit or prevent any unauthorised access to any part of your account or funds.</p>
  <p>2.5. You shall use the Games on your own behalf and not on behalf of any other person or company. A Casumo account may only be held by an individual. For the avoidance of doubt, company accounts are not permitted. Moreover, you shall not allow any other individual, to access and/or use your Casumo account or accept any Prize or access and participate in any of the Casumo services. You understand that you shall be fully liable for any losses incurred by a third party on your Account and you shall immediately inform us should you suspect that a third party has obtained access to your Account, and shall assist us fully in our investigations into the matter.</p>
  <p>2.6. You may participate in the Games strictly in your personal non-professional capacity for recreational and entertainment reasons only.</p>
  <p>2.7. You are aware that the right to access and use the Website and any products there offered, may be considered illegal in certain countries. Casumo is not able to verify the legality of service in each and every jurisdiction, consequently, you are responsible in determining whether your accessing and using our Website is compliant with the applicable laws in your country and you warrant to us that gambling is not illegal in the territory where you reside. Moreover, you declare that you are not a resident of the United States and its dependencies, military bases and territories. Casumo also prohibits persons located in (including temporary visitors) or residents of certain jurisdictions; for avoidance of doubt, access and registration from countries that do not feature on the dropdown options available at registration stage, is strictly prohibited.</p>
  <p>2.8. You are not allowed to transfer funds from your account to other players or to receive money from other players into your account. Casumo accounts are not transferable and it is prohibited for players to sell, transfer or acquire accounts from other players.</p>
  <p>2.9. As an account holder you are responsible for providing Casumo with correct personal details. Consequently, you agree that all information that you give us, such as but not limited to, address and email, during the term of validity of this agreement, is complete and true, and that you will immediately notify Casumo should there be changes to such information. Should Casumo become aware that you have deliberately failed to provide to us correct information, we retain the right to block the account and confiscate any funds therein.</p>
  <p>2.10. You may participate in any Game provided on our Websites only if you have enough funds on your account for such participation.</p>
  <p>2.11. You may not use funds that are tainted or associated with any illegality and, in particular, funds that originate from any illegal activity or source. We moreover reserve the right to terminate an account, ban a player and retain all funds where that player is reasonably suspected of engaging in fraudulent activities which include, but are not limited to: the use of stolen or falsified credit cards or account numbers, chip dumping, forgery, collusion, and the submission of data or documents which are forged, stolen or otherwise misappropriated.</p>
  <p>2.12. You are solely responsible for abiding with any reporting processes related to the payment of taxes and/or other fees which might be charged on winnings that you receive from Casumo, if and where applicable.</p>
  <p>2.13. In relation to deposits and withdrawals of funds into and from your Account, you acknowledge that you shall only use such credit cards and other financial instruments that are valid and issued by lawful institutions and that legally belong to you. We retain the right to prohibit the use of company credit cards.</p>
  <p>2.14. You understand and acknowledge that by playing Games provided by us, you take the risk of losing money deposited into your account. Should you not wish to accept this, kindly refrain from using this site any further.</p>
  <p>2.15. You declare that you are not and shall not be involved in any fraudulent, collusive, fixing or other unlawful activity in relation to your or third parties’ participation in any of the Games and shall not use any software-assisted methods or techniques or hardware devices for your participation in any of the Games. We hereby reserve the right to invalidate any betting and confiscate any funds, should we suspect such behaviour.</p>
  <p>2.16. You may only use our sites and products for your own personal, recreational use, in accordance with the rules and the Terms and Conditions we have established and in accordance with all laws, rules and regulations, if and where applicable.</p>
  <p>2.17. You shall be courteous to other players using the Websites, as well as support personnel employed by Casumo and avoid rude or obscene comments. The non- observance of these Terms and Conditions and of the game rules shall not be tolerated under any circumstance.</p>
  <p>2.18. As part of your use of our casino products, we provide you with a live chat availability, through which you can communicate with our customer service representatives. All conversations shall be recorded. Abusive or offensive language will not be tolerated. Use of the chat facility should strictly relate to our services and any queries related thereto.</p>
  <h4>3. Your Account</h4>
  <p>3.1. In order for you to be able to place bets and deposit money, you must first register personally with us and open an account (“account”).</p>
  <p>3.2.1. You are allowed to have only one Casumo account at any single point in time and shall register this personally. You may not apply for or open an Account if you are not acting as principal and are acting on behalf of someone else or for someone else’s benefit. If you attempt to open more than one account, all betting accounts you try to open may be blocked or closed and any bets and bonuses may be voided. At Casumo’s sole discretion and in the event that we consider that multiple Accounts have been opened in genuine error, we may agree to credit the first Account which you would have opened with us with any of balance remaining on your additional Account(s). Should we have reasonable grounds to believe that fraud has been committed or attempted, we reserve the right to cancel any related transaction, any bonus or any other promotion without prejudice to any other action or redress we might avail ourselves of. In these Terms and Conditions, a reference to ‘fraud’ shall be deemed to include ‘bonus abuse’. Bonus abuse includes, but is not limited to, opening more than one Account in order to claim an additional bonus or benefit.</p>
  <p>3.2.2. Only one Account for each household, IP address and computer device is allowed. If two or more users share the same household, IP address and computer device, Casumo must be informed by the respective accounts’ holders.</p>
  <p>3.3. You must enter all mandatory information requested in the registration form and it is your sole responsibility to ensure that the information you provide to us is true, complete and correct. You are hereby notified that we carry out verification procedures and that your Account may be blocked for access or closed if we suspect that you have supplied us with false or misleading information. You are required to inform Casumo as to any updates, as well as to keep up to date the mandatory information provided in the registration form in the event that such information changes.</p>
  <p>3.4. If you notice that you have more than one registered Account you must notify us immediately. Failure to do so may lead to your Account being blocked for access.</p>
  <p>3.5. As part of the registration process, you will have to choose your username and password for your login into the Website(s). It is your sole and exclusive responsibility to ensure that your login details are kept securely. You must not disclose your login details to anyone. We are not responsible for any abuse or misuse of your Account by third parties due to your disclosure, whether intentional or accidental, whether active or passive, of your login details to any third party.</p>
  <p>3.6. Casumo reserves the right to perform background checks on any player and request any relevant documentation, at all times and, for any reason, including (but not limited to) any investigation into the identity of the player, any credit checks performed on the player, or any enquiries into the player’s personal history. The basis for such investigations will be dependent on the specific case, but could include (but is not limited to) verification of the player’s registration details, such as the name, address and age, occupation, verification of the player’s financial transactions, financial standing, source of wealth, source of funds and/or gaming activity. Casumo is under no obligation to advise the player of such an investigation taking place. Such activities may include the use of specific third party companies, who perform the investigations as required. Casumo may decide at its sole discretion to terminate a player’s account, and withhold all funds in such account, on the basis that such an investigation provides a negative or uncertain conclusion.</p>
  <p>3.7. Casumo reserves the right to suspend or terminate a player account at any time in cases where we believe that continuing its business relationship with you could negatively impact Casumo&#8217;s licensing and general regulatory obligations at its sole discretion and without any explanation whatsoever.</p>
  <p>3.8. Casumo reserves the right to refuse or close an Account at its sole discretion and without any explanation whatsoever, however, any contractual obligations already made by Casumo shall, without prejudice to any rights available at law to Casumo, be honoured accordingly.</p>
  <p>3.9. You understand and accept that Casumo strictly prohibits cheating players and player collusion. Should we have reasonable suspicion that any cheating or collusion has occurred, we reserve the right to void any bet that we suspect has been made as a result of such behaviour and/or confiscate any funds on your account and close your account. Moreover, any player which has reasonable grounds to suspect that another player is taking an unfair advantage through cheating or collusion is to report the suspicion to Casumo by sending an email on <a href="mailto:hey@casumo.com"><span>hey@casumo.com</span>.</a></p>
  <p>3.10. Casumo does not allow the use of robotic, automated, mechanical, electronic or other devices to make automated decisions in any game or in respect of any bet on its sites, whether such use is attempted or affected by you or by any third parties. Should we have reasonable suspicion that any such device is being used on the sites, we reserve the right to void any bet that we suspect has been made using such a device and exclude any customer from any promotion or competition in which we suspect that such a device has been used. You are also prohibited from utilising an external resource that is designed to provide a player with an unfair advantage over other players. Such prohibited external resources may include, but are not limited to, third-party software applications and databases as well as websites, web-based databases, subscription services and the assistance of any other person regardless of whether or not that person is also the holder of a Casumo account. We may also suspend the Account in question pending investigation into the matter and terminate the Account at our sole discretion. Casumo considers the use of such devices to be tantamount to fraud and reserves its right not to refund any balance on the Account at the time of termination and to cancel any pending games.</p>
  <p>3.11.1. If you wish to close your account, you may do so at any time, either by setting the closure via the Play OK settings on your account or by contacting customer support on <a href="mailto:hey@casumo.com"><span>hey@casumo.com</span></a>. Any funds in the Casumo Account will be remitted to you. The effective closure of the Account will correspond to the termination of the Terms and Conditions, however any obligations already entered into shall be honoured.</p>
  <p>3.11.2. In case the reason behind the closure of the Account is related to concerns about possible gambling addiction the player shall indicate it. A player who closes an account for gambling addiction reasons shall not open or try to open a new Casumo account. Casumo shall not be liable for any direct or indirect consequential damages, should an individual succeed in opening a new account. We reserve the right to close an account opened in breach of this rule at any point in time.</p>
  <p>3.12. All communication between the account holder and Casumo is kept on record for compliance, as well as accounting and financial regulations’ purposes. In the case a player account is closed, related information about the account is saved for up to five (5) years from the time the account is closed. Related information includes player name, address, phone, email and account transactional details. After this time period all the information will be archived.</p>
  <p>3.13. Casumo has the right to appoint payment solution providers to act, receive and/or pay funds on its behalf.</p>
  <p>3.14. You may not apply for an Account or use any of our Services if you or a member of your household are or have in the last two years been employed with Casumo. For the purposes of this clause “employee” includes third party contractors such as licensors, software suppliers, developers or partners and all those persons in any way affiliated with us.</p>
  <p>3.15. Casumo do not offer our services to players who are identified as Politically Exposed Persons (PEP). Should you be identified a PEP at any stage, your account will be closed and any remaining real money balance will be returned (subject to general regulatory obligations). If you disagree with our determination of your PEP status, please contact us.</p>
  <p>3.16. Account Timeouts</p>
  <p>Account Holders may wish to take a break from playing on Casumo for reasons, which are not related to managing gameplay and spending, in such cases you may opt to set a “Timeout” period on your account. Your Time-Out periods cannot exceed six (6) months. Should you wish to set a timeout on your account, you may either set the timeout yourself by going to the Play OK settings of your account or by contacting customer support on <a href="mailto:hey@casumo.com"><span>hey@casumo.com</span></a>. Please be aware that if you close your account for time out, we may allow you to reopen your account prior to the lapse of the timeout term. Should you wish to take a break from gambling in general, please refer to section 8 of these Terms and Conditions.</p>
  <h4>4. Deposits into your Account</h4>
  <p>4.1. When you open an Account we require you to make a minimum deposit before you can bet or play. We will assign minimum deposit levels and maximum deposit levels as specified on the Website under the deposit section. You acknowledge that you may only wager and play with the amount of cleared funds held in your Casumo account. Consequently, if you would like to participate in gaming, you must deposit money into your account. You can make a deposit at any time online by using your debit or credit card, e-wallet, prepaid voucher or via a bank transfer. Cash or cheques are not an accepted method of deposit. Certain payment methods may not be available to you depending on certain factors such as jurisdiction and currency.</p>
  <p>4.2. By depositing funds into your account, your direct us and we agree to hold them, along with any winnings, for the sole and specific purpose of using them (i) to place any gaming stakes; and (ii) to settle any fees or charges that you might incur in connection with the use of our services. We may charge assigned fees for processing deposits. If such fees occur they shall be possible to see during the deposit process and shall also be seen in the deposit section on the Website.</p>
  <p>4.3. Depositing funds into your account shall at all times be made through a Financial Institution or a Payment Solution Provider, by the use of any of the methods specified on the Website, as may be amended from time to time. Procedures, terms, availability and duration for transactions may vary depending on the time, the country and the Financial Institution used. Details about the timings for withdrawals in respect to the payment method utilized are available on the relevant pages of the Website, and these may be amended from time to time.</p>
  <p>4.4 Deposited funds are available on the Account within a reasonable amount of time following the confirmation of the deposit made, unless extra verification procedures as stated under clause 4.5 are required.</p>
  <p>4.5. Casumo reserves the right to use additional procedures and means to verify your identity (Know Your Client), both before and after effecting deposits into your Account.</p>
  <p>4.6. If Casumo mistakenly credits your Account with winnings that do not belong to you, whether this is due to a technical or human error or otherwise, the amount will remain property of Casumo and the amount will be transferred back to us from your Account. We reserve the right to void any transactions placed using them, including related winnings paid out in error. To satisfy any such liability, we further reserve the right to freeze and withhold these funds and set-off any subsequent winnings owed to you. If prior to Casumo becoming aware of the error, you would have withdrawn funds that do not belong to you, without prejudice to other remedies and actions that may be available to us at law, the mistakenly paid amount will constitute a debt owed by you to Casumo. In the event of an incorrect crediting, you are obliged to notify our Customer Support services immediately by email.</p>
  <p>4.7. You shall only use debit or credit cards and other financial instruments that are valid and lawfully belong to you.</p>
  <p>4.8. The minimum deposit amount is ten (10) Euro (and any other currency equivalent). Casumo retains the right to change this minimum amount at any time should we deem so appropriate.</p>
  <p>4.9. It is unlawful to deposit money from ill-gotten means. In accordance with our anti-fraud policies, we reserve the right to pay any requested withdrawal partly or in total via the same method of payment through which one or more deposits were made. We further reserve the right to pay any requested withdrawal directly to your bank account.</p>
  <p>4.10. Casumo accepts payments made in Euro (EUR). In case your payment account (i.e. your bank account or your eWallet-account) is in a different currency, Casumo, or your bank/eWallet, as the case may be, will accordingly convert the funds to EUR before depositing it to your account. Likewise the funds you withdraw will be sent to you in EUR and Casumo or your bank/eWallet, as the case may be, will convert the funds to your payment account currency. Please note that any exchange premiums are payable by the Player.</p>
  <p>4.11. Casumo has a quick-deposit feature which allows you to make quick and safe deposits while staying within the gaming session. This feature is only available for customers who either use visa or Skrill as their depositing method. Customers shall use this feature responsibly.
  <p>4.12. Deposits made to your Casumo account should be commensurate with game play. If in Casumo’s discretion, there is suspicion of abuse (for instance, where a deposited amount has not been wagered or used for an appropriate level of game play and the user then makes a withdrawal request in relation to that deposited amount or where Casumo suspects that you are abusing exchange rate fluctuations or made a financial gain through arbitrage), we reserve the right, in our absolute discretion, to cancel other deposit(s), and/or any withdrawals there related, in part or in full, to deduct and/or to retract any balance or costs that may have resulted in conjunction therewith from any funds held in the User’s account, confiscate funds including winnings and to close the Casumo account indefinitely, without any warning and notification. We further reserve the right to request and obtain satisfactory proof of deposit and additional copies of personal identification and other documents as may be required at any stage during the account’s lifetime and in such instances prior to processing any withdrawal request, the processing of such request to be entirely at Casumo’s discretion. In cases where we are not satisfied by the submitted documentation, Casumo may cancel the withdrawal and return the funds to the account or confiscate the funds and block the account indefinitely.</p>
  <p>4.13. You agree that the funds deposited in your Account must only be used for playing the Games which are found on our Websites. We shall be entitled to suspend or close your account if we reasonably consider or have reason to believe that you are depositing funds without any intention to place gaming stakes. In such circumstances we may also report this to relevant authorities.</p>
  <p>4.14. Casumo does not grant any credit for the use of its services.</p>
  <p>4.15. You acknowledge that we shall have the right to block a Casumo Account should we receive a chargeback request in relation to that Account. When a chargeback request has been received, we will contact you as the registered account holder, so as to seek confirmation of your identity and if retained necessary, we shall also ask you to confirm your preferred method of payment. Reminders may be sent should the requested confirmation not be received. Administrative fees may apply in such cases and the balance of your Casumo account may decrease in the case of unduly incurred chargebacks, reversals or other charges we may sustain in relation to your account. You are to note that any remaining funds held in a Casumo account which has been blocked due to a chargeback request, shall be treated as though they were funds on an Inactive account and the procedure laid down under section 7 of these Terms and Conditions shall apply.</p>
  <h4>5. Withdrawals</h4>
  <p>5.1.1. Available withdrawal options are clearly stated on the Websites and may differ depending on the market from which the Player originates.</p>
  <p>5.1.2. Withdrawals will be made to your bank account or other withdrawal methods available to you to choose from under the “Withdrawal” pages and/or as chosen by Casumo. Whenever possible, Casumo shall pay your withdrawals by using the same method you would have utilised to make your deposits. Withdrawal payments may only be made in the name of and to the registered account holder. Casumo reserves the right to cancel withdrawals either to enforce a closed loop or to force the customer to withdraw to a particular withdrawal method.</p>
  <p>5.2. It will not be possible to withdraw funds marked as “Bonus money”, as well as funds stuck in an aborted game. Please refer to Section 6 for further information regarding bonuses and promotions.</p>
  <p>5.3. Financing a bet through the Internet may be illegal in the jurisdiction in which you reside, in such circumstances you are not authorised to use and finance your account for the purposes of placing a bet. Your participation in the products we provide in a jurisdiction where such participation is prohibited by law, shall not affect any stakes or payments made to and accrued for the benefit of Casumo. Moreover, you understand that it is your sole responsibility to pay and proceed with all necessary diligence in relation to taxes on any prize money, if and where these are applicable.</p>
  <p>5.4. The payment managers employed by Casumo will carry out additional verification procedures for any payout exceeding the equivalent of 1000 EUR or cumulative withdrawals exceeding 2000 EUR (or their equivalent under the operational currency).  We further reserve the right to carry out such verification procedures in case of lower pay-outs. Such verifications may include but shall not be limited to, copies of a player’s passport, National Identity Card, copies of a player’s utility bills, and/or copies of the credit/debit cards used to make deposits. Where applicable, all identification documents provided should include a clear photographic image of the registered customer.</p>
  <p>5.5. All transactions shall be checked in order to prevent money laundering. Casumo, the Regulator and any Governing body can monitor or request to review all transactions to prevent this crime from being committed. Casumo shall report any suspicious transactions to the relevant competent authorities in the jurisdiction they would respectively fall under and in which Casumo is licensed to operate. Should we be made aware of any suspicious activity relating to any of our Games, we shall report this to the relevant institutions immediately. Casumo may suspend, block or close an Account and withhold any funds therein, if it is requested to do so in accordance with the applicable prevention of money laundering and financing of terrorism laws and regulations.</p>
  <p>5.6. The time for a withdrawal request to be finalised may vary due to circumstances, however a withdrawal attempt should be approved or denied within three (3) days. When a withdrawal is cancelled, the funds are returned back to your account and you can make use of those funds accordingly on the account. Casumo does not assume any responsibility for any funds lost during gameplay following a withdrawal cancellation either by you or by us.</p>
  <p>5.7. Please be advised that our products are consumed instantly during gameplay. Thus, we cannot provide refunds, returns of monies, or cancellation of the requested service when playing. If you play a game with real money, the money will be drawn from your player account instantly.</p>
  <p>5.8. You shall not treat Casumo as a financial institution nor expect any interest.</p>
  <p>5.9. We may charge assigned fees for processing withdrawals and this shall be clearly stated when you perform a withdrawal request. For further information, it is advisable to refer to the withdrawal page on the Website.</p>
  <p>5.10.1. Casumo also reserves the right to charge a fee should you request a withdrawal without having turned over an amount that is equal to or more than the sum of a deposit that has not been staked. Should this fee be charged, it would amount to 5% of the requested withdrawal and additional bank charges associated with payments made can be passed on to you in this case. Moreover, we shall always reserve the right to apply a fee to withdrawals. If a fee is to be applied to a withdrawal the sum will be shown in the cashier prior to the confirmation of the withdrawal request. The fee will be deducted automatically from your account balance if you choose to proceed with the transaction. The minimum amount you are permitted to withdraw may vary depending on the payment services provider you chose to withdraw the funds.</p>
  <p>5.10.2. Acceptance of a withdrawal request shall be subject to you having made and sufficiently wagered a real-money deposit and in accordance to any other terms and conditions set out by Casumo. All withdrawal requests shall be subject to the transaction limits and withdrawal methods that we shall notify you prior to withdrawal. Casumo retains the right to carry out enhanced due diligence at withdrawal stage should it deem this to be necessary and especially in cases where deposited funds have not been used for wagering.</p>
  <p>5.11.1. In accordance with applicable laws and licence conditions imposed on Casumo by the respective jurisdictions in which we are licensed to operate and provide our services, player funds are protected in the event of insolvency by the segregation of customer funds and are held in separate designated bank accounts. These accounts are used solely for this purpose and our bank has acknowledged this. Furthermore, our bank of choice ensures that these funds are not subject to the enforcement, seizure or execution of any claim against Casumo and these funds are not considered to form part of the assets of Casumo in the event of insolvency. Consequently, in the event of our insolvency, your funds are protected and shall be returned to you.</p>
  <p>5.11.2. As a general rule for all our regulated markets, Casumo holds customer funds separate from its company funds in dedicated Client Bank Accounts. This set-up ensures that funds held in player accounts are kept secure in case of insolvency. This means that steps have been taken to protect customer funds but that there is no absolute guarantee that all funds will be repaid. This also meets the UK Gambling Commission’s requirement for the segregation of customer funds at the level: medium protection.</p>
  <h4>6. Bonuses &amp; Rewards Scheme Conditions</h4>
  <p>6.1.1. We may from time to time offer you bonuses or rewards which will be credited by us into your Account. Such bonuses may only be used in relation to the facilities as may be specified when the bonus is offered to you. Acceptance of certain bonuses may be in accordance with additional or specific terms and conditions that shall be made available to you. Other bonuses and rewards shall be in accordance with standard promotional terms. Unless otherwise specified, our offers may be used only once, and you are not entitled to withdraw any bonus amounts or redeem any rewards without first complying with the applicable terms. A bonus at Casumo can mean free spins, extra money to play for directly or extra money you receive after making a deposit. The type of bonus and the size of it may vary and you need to wager the bonus money in order to withdraw the funds. For this reason you should check the bonus and rewards rules carefully before participating in any promotion.</p>
  <p>6.1.2. (a) You understand that Bonuses and Rewards are subject to certain conditions. Unless otherwise informed in the applicable conditions, the general rule at Casumo is that Bonuses carry a wagering requirement of thirty (30) times the total amount, e.g. if you deposit €10 and obtain a €10 bonus, you would have to wager 30 times the aggregate amount, in this case being €20 (deposit + bonus). Winnings from free spins have a wagering requirement of thirty (30) times. Should you decide to request a withdrawal before having fulfilled the respective wagering conditions, the bonus money shall be lost. Please make sure to refer to and understand the rules and requirements of all the different bonuses and rewards.</p>
  <p>(b) The main Casumo customer loyalty offers are the following:</p>
  <p>(i) Welcome Bonus</p>
  <p>A Welcome Bonus offer is available to new players who sign up for a Casumo account. Players who make a deposit for the first time on their Casumo account will become eligible to the Welcome Bonus. If you wish to enjoy our Welcome Bonus you have to know the following rules:</p>
  <p>Bonus Spins on registration: Only players who register an account for the first time on Casumo will be awarded the Bonus Spins on registration. The offer consists of:</p>
  <p>20 Bonus Spins on Book of Dead</p>
  <p>Deposit Bonus: Only the first deposit made on accounts shall be eligible to receive the Deposit Bonus. The offer currently consists of:</p>
  <p>A 100% matched deposit bonus up to a maximum bonus of €300.; for avoidance of doubt and to by means of example: if you deposit €100€. you receive a €100€ bonus</p>
  <p>All bonuses and bonus winnings must be wagered 30 times before withdrawal. Plus winnings on any free spins must also be wagered 30 times. The smallest possible deposit is €10. Turnover requirements vary depending on the game.</p>
  <p>(ii) Free Spins</p>
  <p>With free spins a customer gets to play for free on a game in the casino with the same chance of winning as when a customer plays with their own money. Winnings on free spins are converted to bonus money and are usually subject to a wagering requirement of 30 times. Free spins must be activated through the account, when a customer is logged in. Once these are activated, the free spins are set off and the particular game will start automatically.</p>
  <p>(iii) Other Bonuses</p>
  <p>At Casumo you can get a bonus in many different ways. Besides the welcome bonus you receive upon joining and weekly new bonus promotions, you can get lots of bonuses simply by playing at Casumo and advancing in levels. Sometimes you get a bonus when you level up, and sometimes you have a bunch of free spins waiting for you when you log in. Customers must be subscribed to our offers to benefit from these rewards.</p>
  <p>(iv) Loyalty Rewards</p>
  <p>At Casumo you can collect points by spinning and winning. When you collect enough points to fill your progress bar, you level up with a chance to earn a reward. Rewards are given out in the form of “valuables”, these contain either free spins, deposit bonuses or bonus money. Wagering requirements would apply for any winnings from free spins and for bonus money.</p>
  <p>(v) Wager Bonus Valuable</p>
  <p>This bonus type is based on a wagering mechanic. Eligible players are shown valuables with specific wagering requirements. Valuables are time-barred (“Promotion Period”) and may be subject to restrictions with regards to the game on which the wagering requirement applies. Only real-money wagering contributes towards the fulfilment of the wagering requirement. Players who wager the minimum amount shown on the valuable during the Promotion Period on the eligible game(s) will receive the corresponding amount shown on the valuable. This valuable can credit Cash, Bonus Spins or Bonus Money. For avoidance of doubt, if the valuable shows  &#8220;Play €20 and receive €5 bonus&#8221;, it means that the player must wager €20 of their deposit balance in order to receive a bonus of €5.</p>
  <p>6.1.3. These terms shall remain valid until a new version is made available and accepted by the user. Any changes to the terms of the bonuses and rewards scheme conditions will be notified to you in advance, and will not take effect until and unless you have reconfirmed your acceptance of the changes.</p>
  <p>6.2. Casumo reserves the right to withhold and remove any bonuses awarded to you if such bonuses have not been used within six (6) months from the date when they were awarded. Individual campaigns may have a shorter expiration time and if so, this shall be stated to the player upon receiving the offer about the campaign.</p>
  <p>6.3. If you are eligible for a bonus, wagering requirements will apply before you are able to make any withdrawals of the bonus or the winnings of bets made using bonus money. Wagering requirements can vary and will be displayed and made available for you to read once you receive the bonus. If you would like to request a withdrawal before the wagering requirements are fulfilled, Casumo will deduct the whole bonus amount as well as any winnings made from bonus money before approving any such withdrawal. Casumo has the right to choose which games and how much a game contributes to the wagering requirements.</p>
  <p>6.4. The bonus received when the Player makes his/her first deposit on the Website has a wagering requirement of a minimum of 30 times the sum of the received bonus and the deposit amount contributing to the bonus figure, unless any special terms and conditions apply to that offer.</p>
  <p>6.5. Without prejudice to 6.8., different games promote differently to the wagering requirements and can be seen in the list below:</p>
  <p>a) RNG based games</p>
  <p>Slot machines 100%</p>
  <p>Video Poker 30%</p>
  <p>Casino Hold’em 10%</p>
  <p>Oasis Poker 10%</p>
  <p>TXS Hold’em poker 10%</p>
  <p>Ultimate Texas Hold’em 0%</p>
  <p>Baccarat (all kind) 0%</p>
  <p>Punto Banco 0%</p>
  <p>Roulette (all kind) 0%</p>
  <p>Blackjack (all kind incl. Pontoon and Double Exposure) 0%</p>
  <p>All other games 100%</p>
  <p>b) Live Casino</p>
  <p>Live Dream Catcher/Top Wheel Treasure: 100%</p>
  <p>All Live Roulette and Live Blackjack: 10%</p>
  <p>All other Live Casino Games: 10%</p>
  <p>6.6. Local wagering requirements may be applied and if so, this shall be stated together with the offer.</p>
  <p>6.7. Bonuses/free spins at Casumo can only be received once per person, household, IP address (including shared networks), device and/or credit/debit card number or any other deposit method used. Risk-free bets on any games do not qualify for Casumo’s wagering requirements. We reserve the right to close your account and confiscate any existing funds if evidence of bonus abuse/fraud is found.</p>
  <p>6.8. Winnings on free spins may contribute to the wagering requirements, however, wagering of bonus funds on 1429 Uncharted Seas, Bloodsuckers, Dead or Alive, Super Monopoly Money, Pearls of India, Scrooge, Beautiful Bones, Tower Quest, Jack Hammer 2, Kings of Chicago and Simsalabim, will not contribute towards the playthrough requirement. Casumo Ltd. reserves the right to forfeit any winnings if bonus funds are wagered on these games.</p>
  <p>6.9. Individual bonus campaigns can have specific details and terms, in this case such information shall be made available to the user. You are to note that any specific terms relating to any particular bonus and/or promotion will take precedence over these Terms and Conditions in the event of there being any inconsistency or discrepancy.</p>
  <p>6.10. During game play, bonus money is used in relation to the real money you have on your account and winnings are divided evenly according to the relation between real money and bonus money in the bet. For example, if you have €100 real money and €50 bonus money in your account, a bet of €3 will contain €2 real money and €1 bonus money and any winnings are divided into the same ratio.</p>
  <p>6.11. The maximum bet allowed when using bonus money is of €5 per spin or €0.50 per bet line until your wagering requirements have been fulfilled. Casumo reserves the right of voiding bets and winnings resulting from bets of larger amounts.</p>
  <p>6.12. We award bonuses and entry to selected promotions in good faith to players who use our services for entertainment purposes and as a token of appreciation for your loyal play. Free bets, bonuses and entry to promotions will be revoked, denied or withdrawn from players who abuse the spirit of our offers. ‘Abuse’ refers to players who by any other means obtain an unfair or unintended advantage. In cases where Casumo suspects that the player is acting in bad faith, Casumo reserves the right to cancel a bonus offer at any time in case of any suspected abuse of the offer and to terminate the offender’s account with immediate effect. At our sole discretion, we may not issue refunds of any deposits, balances or winnings generated on the account should abuse be suspected. The term “Abuse” shall include but is not limited to the opening of multiple accounts to claim multiple bonuses.</p>
  <p>6.13. You understand that you will only be able to receive or benefit from offers that apply to your country of residence and, where stated, deposit payment method. Casumo reserves the right to vary the amount of bonuses granted depending on the user’s country of residence at any time and for any reason whatsoever. We reserve the right to offer a specific bonus to a specific customer or group of customers, to terminate a bonus offer without notice or compensation, to change the terms of a bonus offer and/or to exchange one type of bonus offer for another at our sole discretion and at any time.</p>
  <p>6.14. While playing with wagers made using their bonus balance, players are strictly prohibited from delaying the playing of a game round until after the wagering requirement for that bonus has been met, and/or they have deposited new funds. This includes all bonus and/or free spin modes and features which may arise as a result of wagers made using the player’s bonus balance. In the event that this occurs, the player agrees that their bonus and/or any associated winnings may be voided.</p>
  <p>6.15. Before any withdrawals are processed, your play will be reviewed for any irregular playing patterns. For fair gaming purposes, equal, zero or low margin bets or hedge betting, shall all be considered irregular gaming for Bonus playthrough requirement purposes. Should Casumo deem that irregular game play has occurred, it reserves the right to withhold any withdrawals and/or confiscate all winnings, and if applicable, after cancelling bonuses, to reinstate the deposit on the player’s account, without necessarily informing the player.</p>
  <p>6.16. The Wager Bonus Valuable is based on a wagering mechanic. Eligible players are shown valuables with specific wagering requirements. Valuables are time-barred (“Promotion Period”) and may be subject to restrictions with regards to the game on which the wagering requirement applies. Only real-money wagering contributes towards the fulfillment of the wagering requirement. Players who wager the minimum amount shown on the valuable during the Promotion Period on the eligible game(s) will receive the corresponding amount shown on the valuable. This valuable can credit Cash, Bonus Spins or Bonus Money. For avoidance of doubt, if the valuable shows  &#8220;Play €20 and receive €5 bonus&#8221;, it means that the player must wager €20 of their deposit balance in order to receive a bonus of €5.
  <p>6.16.1. The promotion period, the eligible game(s) and the amount left to wager will be displayed on the valuable.</p>
  <p>6.16.2. This Casino Bonus type may only be used once during the Promotion Period. Once the Promotion Period is over, the player can no longer make use of the bonus.</p>
  <p>6.16.3. This Casino Bonus is only awarded once per person, household, shared computer or shared IP address during the same promotion period. We reserve the right to close your account and confiscate any existing funds if evidence of bonus abuse is found. Casumo retains all rights under these Terms and Conditions to verify its players’ behaviour and act thereupon accordingly.</p>
  <p>6.16.4. Customers are unable to use any funds within their Bonus Balance wallet to claim this Casino Bonus. &#8211; When you place a bet at Casumo, and if you have a bonus in your wallet, 50% of your bet will use your cash wallet and 50% your bonus wallet. (If you place a bet of €10 and you have an active bonus, only €5 will count toward wagering this bonus).</p>
  <p>6.16.5. Players can wager in as many increments of the required wagering amount as they want to. For example for a €10 wagering requirement you can wager €5 twice to receive the bonus.</p>
  <p>6.16.6. Wagering Requirements apply. Deposits must be wagered at least once before they become withdrawable. All bonuses and bonus winnings must be wagered 30 times before withdrawal. Winnings on any bonus spins must also be wagered 30 times before becoming withdrawable. Bonus funds convert automatically to real money once the Wagering Requirement is completed. Unless you complete the wagering requirements, you will be unable to withdraw your bonus money. You can make a withdrawal of your deposit balance before you have fulfilled the wagering requirement, but then you will lose your bonus money. For example, to withdraw a €5 bonus, players will have to wager €150.</p>
  <p>6.16.7. Cash valuables don’t have any wagering required and the amount won will be added to the deposit balance and is withdrawable immediately.</p>
  <h4>7. Inactive Accounts</h4>
  <p>7.1. An <strong>&#8216;inactive account&#8217;</strong> is an account that has not been accessed for twelve (12) consecutive months, that has a real money balance.</p>
  <p>7.2. Casumo will contact you via email up to one month prior to your account becoming inactive. You may reactivate an inactive account by logging in. Once an account becomes inactive, Casumo will charge five (5) Euro (and any other currency equivalent) per month administrative fee to your account, as long as there is a positive balance.</p>
  <p>If after your Account has become inactive, you access your Account, we may consider reimbursement of the fees charged if you can prove one of the following:<br /> (i) You could not access your Account due to health related impediments; or <br /> (ii) You could not access your Account due to a reasonable cause.</p>
  <h4>8. Responsible Gaming</h4>
  <p>8.1. Casumo offers a range of services to assist you if you feel that you are developing a dependency towards gambling. We have in place a series of measures, which will help you play in a safe environment. You understand that when you are playing games of chance that involve money, the outcome can never be sure. We have developed tools that will make your gaming experience safer. In order to use these tools you may either go to the ‘Play OK settings’ tab on your account and set the account limitations according to your needs or you must clearly state your preferences by contacting our customer support service on <a href="mailto:hey@casumo.com"><span>hey@casumo.com</span></a>. When setting the limitations on your account yourself, through the Play OK section on your account, any set limitations will take effect immediately. Should you make your request through our customer support, you will receive an email confirmation from our Customer Support Team within a few minutes of your gaming restriction request being activated. Should you not receive such notification, we kindly ask you to re-contact Customer Support immediately. This service is available to you on a 24-hour basis. We encourage you to consider these measures when playing on Casumo. As a registered account holder you may:</p>
  <p>(i) Set a limit on the amount that you may wish to spend or on an amount you may wish to deposit within a specific period of time;<br /> (ii) Exclude yourself from playing for a definite or an indefinite period of time.</p>
  <p>8.2. Setting a Financial Limit</p>
  <p>8.2.1. We offer you the opportunity to apply financial limits to your Casumo account. When you set-up a limit, you will be unable to continue playing beyond the limit you would have set, as our system will automatically prohibit any further gameplay. You may at your discretion choose to limit the amount you wish to:</p>
  <p>(i) Spend</p>
  <p>This allows you to control the amount you can deposit on your account during a given period and additionally, you will be able to deposit an amount equal to any withdrawals made during the said period.</p>
  <p>(ii) Wagering</p>
  <p>This allows you to control exactly how much money you’re willing to spend over a given period. It limits the total amount you are able to place in stakes.</p>
  <p>(iii) Loss</p>
  <p>This allows you to restrict the amount of real money you can lose from the deposits you make. Winnings are included in the calculation of the loss.</p>
  <p>(iiii) Deposit</p>
  <p>This allows you to limit the amount of funds you can deposit into the account in a given period.</p>
  <p>8.2.2. The amounts in i., ii., iii. iiii. are limits to your spending, wagering and/or losses on a daily, weekly or monthly basis.</p>
  <p>8.2.3. You may change or revoke a limit that you set on your account either via the PlayOK settings on your account or by contacting our customer support service either via chat or on the following email address <a href="mailto:hey@casumo.com"><span>hey@casumo.com</span></a>. Increasing or revoking a limit takes effect after a period of 24 hours “cooling off” period from when Casumo has registered the requested change. This “cooling off” period will give you chance to reconsider whether you really want to raise your deposit limit. On the contrary, decreasing a limit takes place immediately after the request in change has been registered. Should you reach any limit so imposed, you will not be able to make any further deposits or place any bet (including the one you are trying to perform) until the duration of such limit has elapsed.</p>
  <p>8.3. Setting a Maximum Session Time and Reality Checks</p>
  <p>(a) You may at your discretion choose to set a maximum session time during which you will be allowed to stay logged into your account. After this period has expired, the game is automatically stopped and you have to exit and reload the game from games browser to play again.</p>
  <p>(b) The Reality Check tool helps you monitor your gaming activity. Once this feature is activated, a message will be displayed on your screen at regular intervals. A message will be displayed at regular intervals of 60 minutes. This message will inform you about how long you have been playing, how much you have spent/won, it will offer a direct link to your transaction history and present you with the option to resume or exit the game. Customers are to note that for certain Casino providers, if the ‘Autoplay’ function is active, the Reality Check might not suspend game-play when the pop-up message is displayed.</p>
  <p>8.4. Self-Exclusion</p>
  <p>8.4.1. If you feel that you are becoming dependent on gambling, you should consider limiting your access to your account. We have measures in place to ensure that as soon as your self-exclusion request is processed, you will no longer be able to play on Casumo and you will not be able to access your account until your period of limitation has elapsed. Please make sure to withdraw all the funds held in your account prior to making a self-exclusion request. For further information about withdrawals please refer to Section 5 of these Terms and Conditions. Should you still have a balance on your account after requesting self-exclusion, our Customer Support team will pay out any remaining funds on your account. We retain the right to request all necessary documentation for this purpose. Should you have any questions you may contact our customer service on <a href="mailto:hey@casumo.com"><span>hey@casumo.com</span></a>.</p>
  <p>You may, at your discretion, choose to limit your ability to access your Account (log-in) for:</p>
  <p>(i) An indefinite time (&#8216;Forever&#8217;)</p>
  <p>If you decide to close your account permanently, thus choosing ‘Forever’ from the dropdown menu list, you will not be able to access it again and we shall take all necessary steps to remit any remaining funds on your account to you.</p>
  <p>(ii) A definite term (Temporary Self-Exclusion)</p>
  <p>If you decide to self-exclude your account temporarily, you have to limit your access for a minimum period of six (6) months. Temporary self-exclusion may be extended for further periods. There is no maximum period of time for self-exclusion. If you wish to take a break from gaming for a reason, which is not related to gambling addiction, you may refer to our timeout option under Clause 3.14.</p>
  <p>8.4.2. Once the self-exclusion period has elapsed your account will be automatically reactivated.</p>
  <p>8.4.3. Please comprehend that it is important for us to be made aware as to the motive for your exclusion, especially if this related to problem gambling matters. Kindly inform us as to this reason upon making your closure request.</p>
  <p>8.4.4. You may activate your self-exclusion from the ‘Play OK Settings’ on your account. When setting your self-exclusion on your account it will take effect right away. You may also self-exclude by contacting our Customer Support and request self-exclusion. If self-exclusion has been activated by our Customer Support Team you will receive an email confirming your request. Should you not receive such notification, we kindly ask you to re-contact our customer support services immediately. Following a self-exclusion request, we will use our best endeavours not to send you any further marketing materials and, in any event, will ensure that we will not send you any further marketing materials after 48 hours of account closure.</p>
  <p>8.5. All limitations and responsible gambling tools mentioned in this section can be administered by yourself from the ‘Play OK Settings’ on your account or initiated by contacting the Customer Support Service on <a href="mailto:hey@casumo.com"><span>hey@casumo.com</span></a>. The members of this service have been trained in social responsibility and are aware of the risks of compulsive gambling. If you feel you are at risk, they are here to assist you and can explain the measures you can take to restrict your gambling by pointing you in the direction of specialist organisations, which can help you. Our Customer Support service is available to you on a 24-hour basis, 7 days a week.</p>
  <p>8.6. Any account limits and self-exclusion requests would be valid for the licensed brand you are currently a member of (for example casumo.com) only and does not include other sites operated by us.</p>
  <p>8.7. If Casumo believes that your gambling will cause you financial or personal difficulties, we reserve the right to close your account.</p>
  <p>8.8. Under-Age Players</p>
  <p>Casumo does not allow anyone under 18 years of age to open an account on its Websites. Should you be under 18 years of age and attempt to open an account with us or should you assist an underage person in opening an account with us, you are in breach of the law. Should you have minors in your household or should there be a possibility of minors accessing your computer, please make sure to:</p>
  <p>(i) Not to share your log-in details;</p>
  <p>(ii) Not to enable the “remember password” function on the login screens;</p>
  <p>(iii) Not to share your credit card or bank account details with minors;</p>
  <p>(iv) Install parental control software or internet filter software on your computers. Such software can be obtained from <a href="https://www.netnanny.com/"><span>www.netnanny.com</span></a> and <a href="https://www.cyberpatrol.com/"><span>www.cyberpatrol.com</span></a>.</p>
  <p>8.9. Casumo is committed in providing an outstanding service to its customers. As part of this commitment we endeavour to assist our customers in gambling responsibly with the tools listed under this section. Should you require further details on how to gamble responsibly kindly access our <a href="https://www.casumo.com/play-okay/"><span>Play Okay</span></a> Policy. Casumo shall always strive to reasonably enforce its social responsibility, however, we trust you understand that human error cannot be completely ruled out and we therefore solicit your full collaboration at all times. We shall take no responsibility and exclude all form of liability should you continue gambling or persist in using the Website, with the intent of avoiding the relevant measures in place, this includes opening or attempting to register accounts with us by using false or misleading personal data so as to bypass limits, exclusions and other responsible gaming tools previously requested by you.</p>
  <p>8.10. Should you feel that you may be at risk of developing a dependency on gambling or would like to be certain that you, or anyone else in your household does not have access to gambling sites, you may consider installing software which prevents users from accessing any gaming sites. There are independent third party sites that offer products that are aimed at blocking gambling related websites or software. <a href="http://www.betfilter.com/"><span>Betfilter</span></a> and <a href="http://gamblock.com/"><span>GamBlock</span></a> are two of the websites that offer this service. Please click on the links provided should you require further information. So as to ensure maximum protection to those affected by gambling problems, this kind of software cannot be removed from a device once it is installed.</p>
  <p>8.11.1. Players are to note that Casumo would not be made aware of any self-exclusions set-up on other gambling sites.</p>
  <p>8.11.2. If you have chosen to restrict yourself from playing on Casumo because there is the possibility that you might have a gambling problem, it is advisable to consider excluding yourself from all the gambling environments you may have access to, both online and offline.</p>
  <h4>9. Privacy &amp; Cookies</h4>
  <p>9.1. In order to provide you with access to Casumo&#8217;s services we need to process some of your personal information. To understand how we use your personal information you can read our Privacy Notice <a href="https://www.casumo.com/privacy-and-cookies"><span>here</span></a>.</p>
  <h4>10. Exceptional Circumstances &amp; Aborted Games</h4>
  <p>10.1. Unexpected technical problems or circumstances outside the control of Casumo such as technical problems at third party providers allows Casumo to cancel bets and give refunds to players. Additionally, you acknowledge that your computer equipment or mobile device and Internet connection may affect the performance and operation of the Website, for this reason Casumo cannot guarantee that the Website will operate without faults or errors or that its services will be provided without interruption. Casumo does not accept any liability for any failures or issues that arise due to your equipment, Internet connection or third party provider. This shall also include your inability to place bets or wagers or to view or receive information in relation to certain particular games.</p>
  <p>10.2. Casumo has the right to limit, cancel and refuse bets in the case they are considered to be too large or if we are of the opinion that the betting pattern of the player takes place in such a way that the system is being abused.</p>
  <p>10.3. If a refund is decided upon, the amount of the refund shall be returned to the player’s account, the player shall be informed and the procedure shall be finalised within 48 hours after the decision has been made.</p>
  <p>10.4. In the case that a game is “stuck” in a state where it is not being finished, for example a connection loss while playing an active Blackjack hand, Casumo has the right to “clean up” such bets on a regular basis and refund the bet/wager to the player’s account.</p>
  <p>10.5. If a bonus campaign has in any way been misconfigured, Casumo has the right to alter players balances as well as other account details which would have been affected by the misconfiguration, so as to correct the mistake.</p>
  <p>10.6. Should a game contain a bug or misconfiguration that causes incorrect behaviour or pay out, Casumo has the right to remove the game and alter players balances and account details in order to correct the mistake.</p>
  <p>10.7. The Company is not liable for any downtime, server disruptions, lagging, or any technical or political disturbance to the game play. Refunds may be given solely at the discretion of the management.</p>
  <p>10.8. The Company shall accept no liability for any damages or losses which are deemed or alleged to have arisen out of or in connection with the Website or its content; including without limitation, delays or interruptions in operation or transmission, loss or corruption of data, communication or lines failure, any person&#8217;s misuse of the site or its content or any errors or omissions in content.</p>
  <p>10.9. Casumo endeavours to ensure that the Website is available twenty-four hours a day, however it shall not be held liable if for any reason the site is unavailable at any time or for any period. We may remove any game from the Website at any time we see fit and reserve the right to make changes or amendments, to alter, suspend or discontinue any of the content, products or services, including your access to the Website.</p>
  <p>10.10. In order for you to use particular products that we might offer, you may be required to download certain software. You may also be requested by some third party software providers to agree to additional terms and conditions that govern the use of their products. Should you not wish to accept such third party terms and conditions, please refrain from using their software. Casumo does not accept any liability in relation to any third party software.</p>
  <p>10.11. You are not allowed to abuse of any error or instance of incompleteness on the Website, in the Client application, in any of the Software or in any of the Services provided by us. Should you become aware of such an error or incompleteness, you shall refrain from taking any advantage thereof and notify us immediately. If you do not comply with this clause and take advantage of or divulge any information about an error or incompleteness, Casumo shall be entitled to any remedies available at law and this shall include compensation for any costs it may have incurred in association with any losses, which would have resulted from your breach of this clause.</p>
  <h4>11. Complaints &amp; dispute resolution procedure</h4>
  <p>11.1. You may contact our customer support service according to the instructions located at the Websites should you wish to make any complaints regarding our services. This can be found under the “Contact Us” or “Help” section. Alternatively, you may send us an email to <a href="mailto:hey@casumo.com"><span>hey@casumo.com</span></a>.</p>
  <p>11.2. Complaints are handled in the support department and escalated in the organisation of Casumo in cases where the support personnel do not solve the case immediately. The player shall be reasonably informed about the state of their complaint.We always endeavour to resolve complaints in the least time possible.</p>
  <p>11.3. If you are not satisfied with the resolution of your complaint by Casumo, you may report your complaint to the alternative dispute resolution organisation eCOGRA. You may file your complaint by clicking on the following link and filling in the appropriate “disputes” form: <a href="http://ecogra.org/"><span>eCOGRA Alternative Dispute Resolution.</span></a>. eCOGRA is a third party organisation which offers independent adjudication in relation to betting and gaming disputes.</p>
  <p>11.4. Alternatively, you may direct your complaint to the Online Dispute Resolution (ODR) platform of the European Commission. This website is dedicated to helping consumers and traders resolve their disputes out-of-court, and may be accessed through this link: <a href="https://webgate.ec.europa.eu/odr/main/index.cfm?event=main.home.chooseLanguage"><span>EC Online Dispute Resolution</span></a>.</p>
  <p>11.5. If you have a complaint which may affect the status of our MGA license, particularly any claims that our conduct is unlawful or conducted in a manner which is not safe, fair, or transparent, you may report your complaint to the Malta Gaming Authority by email on <a href="mailto:support.mga@mga.org.mt"><span>support.mga@mga.org.mt</span></a>.</p>
  <h4>12. Limitation of Liability</h4>
  <p>12.1. You acknowledge that the Services offered on this Website are for entertainment purposes only. You are not required to use our Services and your participation is at your sole choice and discretion. You consequently enter the Website and participate in the Games at your own risk. The Websites and the Games are provided without any warranty whatsoever whether this is express or implied. You claim that your interest in our Services and in our Website is personal, and not professional and that you have registered an account with us only for personal entertainment. Any other use of the Services we provide and any other use of our Website is strictly prohibited.</p>
  <p>12.2. Without prejudice to the generality of the preceding provision, we, our directors, employees, partners and service providers:</p>
  <p>12.2.1. Do not warrant that the software, Games and the Websites are always fit for their purpose;</p>
  <p>12.2.2. Do not warrant that the software, Games and the Websites are free from errors;</p>
  <p>12.2.3. Do not warrant that the software, Games and the Websites will be accessible without interruptions;</p>
  <p>12.2.4. Shall not be liable for any loss, costs, expenses or damages, whether direct, indirect, special, consequential, incidental or otherwise, arising in relation to your use of the Websites or your participation in the Games.</p>
  <p>12.3. You understand and acknowledge that, if there is a malfunction in a Game or its interoperability, any bets made during such malfunctioning shall be void. Funds obtained from a malfunctioning Game shall be considered void, as well as any subsequent game rounds with said funds, regardless of what Games are played using such funds.</p>
  <p>12.4. You hereby agree to fully indemnify and hold harmless us, our directors, employees, partners, and service providers for any cost, expense, loss, damages, claims and liabilities howsoever caused, that may arise in relation to your use of the Website or participation in the Games.</p>
  <p>12.5. To the extent permitted by law, our maximum liability arising out of or in connection with your use of the Websites, regardless of the cause of action (whether in contract, tort, breach of warranty or otherwise), will not exceed €100.</p>
  <p>12.6. All information displayed on our Website is provided for information purposes only, and not intended to constitute professional advice of any kind. Neither Casumo nor any of its independent providers is liable for any information errors, incompleteness, inaccuracy or delays, or for any actions taken in reliance of information contained herein.</p>
  <h4>13. Intellectual Property</h4>
  <p>13.1. Casumo, its Group companies and its licensors (including any Third Party Providers) are the sole holders of all rights in the Software and the Software&#8217;s code, structure and organisation, including copyright, trade secrets, intellectual property and other rights. You may not, within the limits prescribed by applicable laws:</p>
  <p>a. copy, distribute, publish, reverse engineer, decompile, disassemble, modify, or translate the Software or make any attempt to access the source code to create derivative works of the source code of the Software, or otherwise;</p>
  <p>b. sell, assign, sublicense, transfer, distribute or lease the Software;</p>
  <p>c. make the Software available to any third party through a computer network or otherwise;</p>
  <p>d. export the Software to any country (whether by physical or electronic means); or</p>
  <p>e. use the Software in a manner prohibited by applicable laws or regulations.</p>
  <p>(each of the above is an <strong>&#8220;Unauthorised Use&#8221;</strong>);.</p>
  <p>13.2. The term &#8220;Casumo&#8221; and any other trademarks, service marks, signs, trade names and/or domain names used by Casumo on the Sites and/or its applications from time to time (the &#8220;Trademarks&#8221;), are the trademarks, service marks, signs, trade names and/or domain names of Casumo and/or its companies and/or licensors, and these entities reserve all rights to such Trademarks. In addition, all content on the Sites, including, but not limited to, the Software, images, pictures, graphics, photographs, animations, videos, music, audio and text (the <strong>&#8220;Site Content&#8221;</strong>) belongs to Casumo and/or its Group companies and/or its licensors (including any Third Party Providers) and is protected by copyright and/or other intellectual property or other rights. You hereby acknowledge that by using the Service and the Sites you obtain no rights in the Site Content and/or the Trademarks, or any part thereof. Under no circumstances may you use the Site Content and/or the Trademarks without Casumo’s prior written consent.</p>
  <p>Additionally, you agree not to do anything that will harm or potentially harm the rights, including the intellectual property rights, held by Casumo, its Group companies and/or its licensors (including any Third Party Providers) in the Software, the Trade Marks or the Site Content nor will you do anything that damages the image or reputation of Casumo, its Group companies, employees, directors, officers and consultants.</p>
  <p>13.3. You warrant that any names or images used by you in connection with the Site or Service (for example, your user name) shall not infringe the intellectual property, privacy or other rights of any third party. You hereby grant Casumo a worldwide, irrevocable, transferable, royalty free, sublicensable licence to use such names and images for any purpose connected with the Sites or Service, subject to the terms of our Privacy Notice.</p>
  <h4>14. Breaches, Penalties and Termination</h4>
  <p>14.1. If you breach any provision of these Terms and Conditions or should we have a reasonable ground to suspect that you have breached them, we reserve the right to not open, to suspend, or to close your Account, or withhold the payment of your winnings and apply such funds on account for any damages due by you.</p>
  <p>14.2. If Casumo suspects that you are engaged in illegal and/or fraudulent activities when using any of the Websites; or that you are in breach of this Agreement; or that you are having problems with creditors or that you are otherwise engaged in actions which may be detrimental to our business, we retain the right to freeze or terminate your account or cancel any stakes at our absolute discretion.</p>
  <p>14.3. You acknowledge that Casumo shall be the final decision-maker of whether you have violated Casumo’s rules, policies and/or Terms and Conditions, in a manner that results in the suspension or permanent barring from participation in our site(s).</p>
  <p>14.4. Should we delay or fail to enforce our rights under these Terms and Conditions, this does not mean that we are losing or waiving the rights afforded by them where set timelines have not been set out. The same shall also apply to you.</p>
  <p>14.5. We will not be liable to you for any breach of these Terms and Conditions which arises because of any circumstances that we cannot reasonably expected to control.</p>
  <h4>15. Severability</h4>
  <p>15.1. If any provision of these Terms and Conditions is held to be illegal or unenforceable, such provision shall be severed from these Terms and Conditions and all other provisions shall remain in force and unaffected by any such severance.</p>
  <h4>16. Assignment</h4>
  <p>16.1. We reserve the right to assign or otherwise lawfully transfer this agreement. You however, shall not assign or otherwise transfer this agreement.</p>
  <h4>17. Entire Agreement</h4>
  <p>17.1. These Terms and Conditions constitute the entire understanding between you and us with respect to the use of our Websites and, save in the case of fraud, they shall supersede all prior or contemporaneous communications, proposals and agreements, whether electronic, oral or written, between you and us with respect to the Websites.</p>
  <h4>18. Applicable law and jurisdiction</h4>
  <p>18.1. Any legal claim or dispute arising under or in connection with these contractual terms shall be settled in accordance with the governing law of the place of the contract. The place of contract of this agreement is Malta and these Terms and Conditions are governed by the Laws of Malta.</p>
  <p>18.2. The parties agree that any dispute, controversy or claim arising out of or in connection with these Terms and Conditions, or the breach, termination or invalidity thereof, shall be submitted to the exclusive jurisdiction of the Maltese courts. We cannot accept responsibility under the laws of any other jurisdiction.</p>
`;

export default {
  content,
  "table_of_contents_title": "Table of Contents:",
  "changelog_title": "Updates made:",
  "downloadUrl": "",
  "button_download_pdf": "Download PDF",
  "button_version_history": "Version history",
  "button_view_version": "View",
  "note_version_old":
    "This is an archived version of our Terms & Conditions. View the <#>current version.</#>",
  "version_label": "Version {{version}}",
  "version_label_current": "Version {{version}} - Current",
  "version_label_original": "Version {{version}} - Original",
  "date_published": "Published {{date}}",
  "date_agreed": "Agreed on registration {{date}}",
  "date_changes_accepted": "<b>Changes Accepted</b> {{date}}",
  "versions": {
    [17]: {
      changelog,
      version: "2.7",
      iso_8601_published_date: "2019-05-14",
      pdf: {
        url: "casumo.com"
      }
    },
    [16]: {
      changelog,
      version: "2.6",
      iso_8601_published_date: "2019-04-01",
      pdf: {
        url: "casumo.com"
      }
    },
  }
}
