// @flow
export const t  = {
  major: "Major Jackpot",
  major_icon: "https://cms.casumo.com/wp-content/uploads/2020/10/major.svg",
  mega_community: "Community Pot",
  mega_community_explanation: "Shared pot",
  mega_community_icon: "https://cms.casumo.com/wp-content/uploads/2020/10/community.svg",
  mega_single_winner: "Mega Jackpot",
  mega_single_winner_explanation: "Goes to 1 winner",
  mega_single_winner_icon: "https://cms.casumo.com/wp-content/uploads/2020/10/mega.svg",
  mini: "Mini Jackpot",
  mini_icon: "https://cms.casumo.com/wp-content/uploads/2020/10/mini.svg",
  section_title: "Casumo Jackpot Blizzard",
  jackpot_win_mini: "You won the Mini Jackpot!",
  jackpot_win_major: "You won the Major Jackpot!",
  jackpot_win_mega: "You won the Mega Jackpot!",
  continue_playing: "Continue playing",
  community_jackpot_win: "Community pot paid out",
  community_jackpot_win_amount: "You won {{{amount}}} from the pot",
  community_jackpot_win_icon: "https://cms.casumo.com/wp-content/uploads/2020/10/community.svg",
  community_jackpot_win_pot_restart: "The Mega and Community Jackpots have been won and will start over.",
  blizzard_campaign_image: "https://cms.casumo.com/wp-content/uploads/2020/10/blizzard.svg",
  blizzard_campaign_content: "You’re playing a <b>Jackpot Blizzard</b> game. Good luck!",
  eligible_games_cta_label: "See all eligible games",
  campaign_logo: "https://cms.casumo.com/wp-content/uploads/2020/10/logo.svg",
  jackpot_split_explanation: "To win the Mega Jackpot or a share of the community pot, €10 must be wagered within 6hrs from the jackpots paying out."
}
