const path = require("path");

module.exports = {
  svgoConfig: {
    multipass: true,
    pretty: process.env.NODE_ENV === "development",
    indent: 2,
    plugins: [
      { cleanupIDs: true },
      { cleanupNumericValues: true },
      { cleanupAttrs: true },
      { cleanUpEnableBackground: true },
      { convertStyleToAttrs: true },
      { convertColors: { currentColor: false } },
      { convertPathData: true },
      { convertTransform: true },
      { convertShapeToPath: true },
      { collapseGroups: true },
      { mergePaths: true },
      { moveElemsAttrsToGroup: true },
      { moveGroupAttrsToElems: true },
      { removeDoctype: true },
      { removeXMLProcInst: true },
      { removeComments: true },
      { removeMetadata: true },
      { removeTitle: true },
      { removeDesc: true },
      { removeUselessDefs: true },
      { removeEditorsNSData: true },
      { removeEmptyAttrs: true },
      { removeHiddenElems: true },
      { removeEmptyText: true },
      { removeEmptyContainers: true },
      { removeViewBox: true },
      { removeUnknownsAndDefaults: true },
      { removeNonInheritableGroupAttrs: true },
      { removeUselessStrokeAndFill: true },
      { removeUnusedNS: true },
      { removeRasterImages: true },
      { removeDimensions: false },
      { removeAttrs: { attrs: "(stroke)" } },
      // { removeAttrs: { attrs: '(stroke|fill)' } },
      { sortAttrs: true },
      { transformsWithOnePath: true },
    ],
  },
};
