// @flow
import { VALUABLE_TYPES } from "Models/valuables";

export default [
  {
    __typename: "PlayerValuableCash",
    id: "1",
    valuableType: VALUABLE_TYPES.CASH,
    title: "€50 Bonus Money",
    currency: "EUR",
    caveat: "Min dep £10. 30x wag req. T&C's apply.",
    market: "en",
    rule: {
      __typename: 'PlayerValuableRule',
      id: '1',
      name: 'rule1',
    },
    backgroundImage: "https://cms.casumo.com/wp-content/uploads/2019/04/background-cash.png",
    expiryDate: 1569794399000,
    valuableState: "Fresh",
    content: "Gives €50 in cash",
    requirementType: "deposit",
    wageringThreshold: null,
    leftToWager: null,
    magnitude: 1.0,
  },
  {
    __typename: "PlayerValuableDeposit",
    id: "2",
    valuableType: VALUABLE_TYPES.DEPOSIT,
    title: "100% Deposit Bonus",
    market: "en",
    caveat: "T&Cs apply",
    content: "Gives you 20% extra with your next deposit (max bonus €200)",
    backgroundImage: "https://cms.casumo.com/wp-content/uploads/2019/04/background-deposit.png",
    expiryDate: 1569794399000,
    valuableState: "Fresh",
    wageringThreshold: null,
    leftToWager: null,
    currency: "EUR",
    magnitude: 20,
    maxBonusValue: 100,
    minDepositValue: 30,
    rule: {
      __typename: 'PlayerValuableRule',
      id: '1',
      name: "duno",
    }
  },
  {
    __typename: "PlayerValuableDeposit",
    id: "3",
    valuableType: VALUABLE_TYPES.DEPOSIT,
    title: "20% Deposit Bonus",
    market: "en",
    caveat: "T&Cs apply",
    content: "Gives you 20% extra with your next deposit today!",
    backgroundImage: "https://cms.casumo.com/wp-content/uploads/2019/04/background-deposit.png",
    expiryDate: 1569794399000,
    valuableState: "Fresh",
    wageringThreshold: null,
    leftToWager: null,
    currency: "EUR",
    magnitude: 20,
    maxBonusValue: 100,
    minDepositValue: 30,
    rule: {
      __typename: 'PlayerValuableRule',
      id: '1',
      name: "duno",
    }
  },
  {
    __typename: "PlayerValuableDeposit",
    id: "4",
    valuableType: VALUABLE_TYPES.DEPOSIT,
    title: "10% Deposit Bonus",
    market: "en",
    caveat: "T&Cs apply",
    content: "Gives you 10% back of your deposit! Do it now! Do it Good!",
    backgroundImage: "https://cms.casumo.com/wp-content/uploads/2019/04/background-deposit.png",
    expiryDate: 1569794399000,
    valuableState: "Fresh",
    wageringThreshold: null,
    leftToWager: null,
    currency: "EUR",
    magnitude: 20,
    maxBonusValue: 10,
    minDepositValue: 30,
    rule: {
      __typename: 'PlayerValuableRule',
      id: '1',
      name: "duno",
    }
  },
  {
    __typename: "PlayerValuableDeposit",
    id: "66",
    valuableType: VALUABLE_TYPES.DEPOSIT,
    title: "30% Deposit Bonus",
    market: "en",
    caveat: "T&Cs apply",
    content: "Gives you 10% back of your deposit! Do it now! Do it Good!",
    backgroundImage: "https://cms.casumo.com/wp-content/uploads/2019/04/background-deposit.png",
    expiryDate: 1569794399000,
    valuableState: "Fresh",
    wageringThreshold: null,
    leftToWager: null,
    currency: "EUR",
    magnitude: 20,
    maxBonusValue: 10,
    minDepositValue: 30,
    rule: {
      __typename: 'PlayerValuableRule',
      id: '1',
      name: "duno",
    }
  },
  {
    __typename: "PlayerValuableDeposit",
    id: "21",
    valuableType: VALUABLE_TYPES.DEPOSIT,
    title: "30% Deposit Bonus",
    market: "en",
    caveat: "T&Cs apply",
    content: "Gives you 10% back of your deposit! Do it now! Do it Good!",
    backgroundImage: "https://cms.casumo.com/wp-content/uploads/2019/04/background-deposit.png",
    expiryDate: 1569794399000,
    valuableState: "Fresh",
    wageringThreshold: null,
    leftToWager: null,
    currency: "EUR",
    magnitude: 20,
    maxBonusValue: 10,
    minDepositValue: 30,
    rule: {
      __typename: 'PlayerValuableRule',
      id: '1',
      name: "duno",
    }
  },
  {
    __typename: "PlayerValuableDeposit",
    id: "5",
    valuableType: VALUABLE_TYPES.SPORT,
    title: "€5 Sport Bet",
    market: "en",
    caveat: "T&Cs apply",
    backgroundImage: "https://cms.casumo.com/wp-content/uploads/2019/04/background-sport.png",
    expiryDate: 1569794399000,
    valuableState: "Fresh",
    content: "Gives you 20% extra with your next deposit (max bonus €200)",
    wageringThreshold: null,
    leftToWager: null,
    currency: "EUR",
    magnitude: 20,
    maxBonusValue: 100,
    minDepositValue: 30,
    rule: {
      __typename: 'PlayerValuableRule',
      id: '1',
      name: "duno",
    }
  },
  {
    __typename: "PlayerValuableSpins",
    id: "654",
    valuableType: VALUABLE_TYPES.SPINS,
    title: "20 Free Spins",
    magnitude: 20,
    coinValue: 30,
    requirementType: "deposit",
    game: {
      __typename: "Game",
      title: "Starburst",
      name: "Starburst",
      slug: "starburst",
      logo: "",
      backgroundImage: "",
      logoBackground: "",
      disabledForLoggedOut: false,
      isInMaintenance: false,
      hasPlayForFun: false,
      inMaintenanceMode: false,
    },
    description: "Starburst",
    caveat: "T&Cs apply",
    backgroundImage: "https://cms.casumo.com/wp-content/uploads/2018/09/cc-small-starburst.png",
    market: "en",
    expiryDate: 1569794399000,
    valuableState: "Fresh",
    content: "Gives you 10 free spins in starburs",
    currency: "EUR",
    leftToWager: 0,
    wageringThreshold: 0,
    rule: {
      __typename: 'PlayerValuableRule',
      id: '1',
      name: 'rule1',
    },
  },
]
