export const TopCard = {
  backgroundImage:
    "https://cms.casumo.com/wp-content/uploads/2018/06/FootballStudio.jpg",
  id: "277054e0-8b5e-11e8-85b2-0242ac110002",
  isInMaintenance: false,
  isInMyList: false,
  liveCasinoLobby: {
    id: "TopCard000000001",
    tableId: "TopCard000000001",
    symbol: null,
    numberOfPlayers: 1,
    provider: "evolution",
    results: [
      "L",
      "R",
      "L",
      "R",
      "R",
      "L",
      "R",
      "L",
      "L",
      "R",
      "S",
      "L",
      "R",
      "R",
      "L",
      "R",
      "R",
      "R",
      "R",
      "R",
      "R",
      "L",
      "R",
      "R",
      "R",
      "R",
      "L",
      "L",
      "L",
      "L",
      "R",
      "R",
      "R",
      "L",
      "R",
      "L",
      "R",
      "L",
      "R",
      "L"
    ],
    image: "/images/live-casino/topctm1_bs_med_L.jpg",
    type: "TopCard",
    betBehind: null,
    bets: null,
  },
  logo: "https://cms.casumo.com/wp-content/uploads/2018/06/FootballLogo.png",
  name: "Football Studio",
  slug: "evolution-live-football-studio",
};
