export const ACTION_TYPES = {
  SET_LOGOUT_STARTED: "PLAYER/SET_LOGOUT_STARTED",
  SET_SESSION_STARTED: "PLAYER/SET_SESSION_STARTED",
};

export const WALLET_UPATE_REASONS = {
  GAMEPLAY: "GAMEPLAY",
  BONUS_AWARDED: "BONUS_AWARDED",
};
