export default [
  {
    id: "0dcd9b50-7ebc-11e8-a686-0242ac110002",
    providerId: "b9ebe9d0-7bcf-11e4-a8c0-005056a03973",
    slug: "1-2-3-bingo",
    name: "1 2 3 Bingo",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/06/123_bingo_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/06/123_bingo_thumbnail.jpg",
    hasPlayForFun: false,
    inMaintenance: false,
    category: "BINGO",
    media: [],
  },
  {
    id: "621862c0-a907-11e7-859e-005056a03af2",
    providerId: "1ad9a810-2425-11e5-bd73-005056a03973",
    slug: "108-heroes",
    name: "108 Heroes",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2017/07/108_heroes_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2017/07/108_heroes_bg.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "94b20790-a907-11e7-859e-005056a03af2",
    providerId: "1ad9a810-2425-11e5-bd73-005056a03973",
    slug: "108-heroes-multiplier-fortunes",
    name: "108 Heroes Multiplier Fortunes",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2017/09/108_heroes_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2017/09/108_heroes_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "48226ec0-4c45-11e7-b4f8-005056a03af2",
    providerId: "b9ebe9d0-7bcf-11e4-a8c0-005056a03973",
    slug: "13-2",
    name: "13",
    description:
      "13 slot is full of exciting features borrowed from well known myths of magic. Whether your brand of magic is voodoo, witchcraft, ancient spells or just plain old superstitions you can be sure to put your knowledge into good use here. Spot the black cat and claim up to thirteen free spins, spot the cat again and get more spins! Find the witch and turn the reels wild, or break the mirror, this time for good luck. Set your bet and double it with a gamble. Cross your fingers for each spin and you might just land a prize worth your superstitions!",
    jackpotId: null,
    liveCasinoId: null,
    logo: "https://cms.casumo.com/wp-content/uploads/2017/06/thirteen_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2017/06/thirteen_bg.jpg",
    hasPlayForFun: false,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "9a4a1140-912d-11e6-a194-005056a03af2",
    providerId: "aa35fd80-ff02-11e4-ad81-005056a03973",
    slug: "1421-voyages-of-zheng-he",
    name: "1421 Voyages of Zheng He",
    description:
      "The year is 1421 and this is the Voyages of Zheng He! Set sail and embark on a lucrative expedition with this legendary Chinese explorer. Journey across the oceans in search of fortune and enjoy beautiful scenery. Let the map guide you to the bonus games and uncover big wins. More free spins or higher multipliers? The choice is yours! Be adventurous and try the Cup Feature. Take the helm and steer the ship towards amazing treasures!",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2016/09/voyages_of_zheng_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2016/09/voyages_of_zheng_he_bg.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "15a39c83-d94d-11e3-88bd-005056a03af2",
    providerId: "0d7382f0-d94d-11e3-a4fd-005056a03af2",
    slug: "1429-uncharted-seas",
    name: "1429 Uncharted Seas",
    description:
      "Bring forward your most adventurous side and explore the uncharted seas. Sea monsters mermaids and shiny gold treasures &#8211; god knows what might be luring deep below the dark surface. The ancient map will guide your way to the secrets of the Uncharted Seas.",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2014/02/UnchartedSeas_Logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2014/06/UnchartedSeas_Thumb.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "da491330-0401-11e7-aa64-005056a03af2",
    providerId: "4bc32c90-0401-11e7-bc66-0242ac110007",
    slug: "221b-baker-street",
    name: "221B Baker Street",
    description:
      "Sherlock is not a man interested in money and prizes, so when you help him solve the source of mysterious wins 221B Baker Street slot you can claim everything for yourself! Wait for the wild card for an unexpected clue, duel with the bandits to claim the pot, or gamble away for an even bigger win! Get ready for a showdown at Baker street and win the duel. Spot the famous Big Ben and get countless free spins, re-trigger them again and claim additional bonuses each time you do. Spin the reels and reveal the hidden bonuses!",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2017/02/bakerstreet_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2017/02/bakerstreet_bg.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "4fec0850-f1db-11e7-901f-005056a03af2",
    providerId: "cb0a8190-15b7-11e5-a40d-005056a03973",
    slug: "3-elements",
    name: "3 Elements",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/01/three_elements_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/01/three_elements_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "affcfd60-997b-11e8-9172-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "3-genie-wishes",
    name: "3 Genie Wishes",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/08/3_genie_wishes_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/08/3_genie_wishes_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "e012b670-997b-11e8-9172-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "3-kingdoms-battle-of-red-cliffs",
    name: "3 Kingdoms Battle Of Red Cliffs",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/08/3_kingdoms_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/08/3_kingdoms_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "1b7e3420-7dd2-11e8-a686-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "300-shields",
    name: "300 Shields",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2016/12/300Shields-BellyLogo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2016/12/300-shields_bg.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "64101812-2bff-11e6-a731-005056a03af2",
    providerId: "b9ebe9d0-7bcf-11e4-a8c0-005056a03973",
    slug: "4-reel-kings",
    name: "4 Reel Kings",
    description:
      "4 Reels Kings is a turbocharged version of the undeniable king of slot machines, Reel King. This Novomatic one arm bandit is not lacking in chances to win, because it is actually four slots in one. You read it right. Not two, not three, but four! Why play one if you can play four? Without a doubt all the usual features are there, 20 win lines and your old friend the joker as the wild symbol. When you see the kings money bag, get ready to cash in! All in all it is a royal update of the old king of the online slot machines. Four times more chances to win big time. Too good to be true? Why dont you try for yourself",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2016/06/Greentube_4ReelKings_Logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2016/06/Greentube_4ReelKings_Thumbnail.jpg",
    hasPlayForFun: false,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "97c23b00-998c-11e8-9172-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "5-lions",
    name: "5 Lions",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo: "https://cms.casumo.com/wp-content/uploads/2018/08/5_lions_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/08/5_lions_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "2ccd5a10-997c-11e8-9172-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "7-monkeys",
    name: "7 Monkeys",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/08/7_monkeys_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/08/7_monkeys_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "7a87e180-997c-11e8-9172-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "7-piggies",
    name: "7 Piggies",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/08/7_piggies_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/08/7_piggies_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "92f94b20-afed-11e6-9b35-005056a03af2",
    providerId: "f1d0f670-15ac-11e5-adb5-005056a03973",
    slug: "7-sins",
    name: "7 Sins",
    description:
      "Indulge yourself with 7 Sins! And there is no need to feel guilty about it. This is a slot you simply cant say no to. Its like with chocolate, you cant just take one bite. You have to take at least two. Enjoy beautiful graphics and an alluring 243 ways to win. Benefit from Double Wilds and second chances. Take pleasure in Free Spins with Expanding Symbols and lucrative Multipliers. Get a 7 of a kind and claim a heavenly win!",
    jackpotId: null,
    liveCasinoId: null,
    logo: "https://cms.casumo.com/wp-content/uploads/2016/11/7_sins_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2016/11/7_sins_bg.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "5dfc98c0-e8b5-11e8-8e3a-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "7s-to-burn",
    name: "7&#8217;s To Burn",
    description:
      "Kan du ibland känna att det lever en liten eldfluga inom dig? Var det ett ja? Då är det dags att prova vår nya spelautomat 7s To Burn. Om du får tre brännande Lucky 7s-symboler på vinstlinjen kommer du definitivt behöva kyla ner dig. Vi ska berätta varför, och det är för att du just kammat  hem en maxvinst! Det är enkelt, det är skoj. Prova själv!",
    jackpotId: null,
    liveCasinoId: null,
    logo: "https://cms.casumo.com/wp-content/uploads/2015/04/7stoburnlogo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2015/04/7stoburnbg-thumb.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "b6d90330-997c-11e8-9172-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "8-dragons",
    name: "8 Dragons",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/08/8_dragons_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/08/8_dragons_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "37e354d0-e8b5-11e8-8e3a-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "88-fortunes",
    name: "88 Fortunes",
    description:
      "Try your fortune on the 88 Fortunes slot! Hit the gong to receive lucrative free spins and look forward to the opportunity to re-trigger new ones. This you can do an unlimited number of times! Make use of the All Up game feature and increase your winning chances. Buy more gold symbols and become eligible for more and bigger jackpots. Pick golden coins until you match three babies and win a jackpot. Good luck!",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2016/06/88_fortune_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2016/06/88_fortune_bg.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "129e3500-997d-11e8-9172-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "888-dragons",
    name: "888 Dragons",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/08/888_dragons_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/08/888_dragons_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "41cf2fc0-d8bb-11e6-b55a-005056a03af2",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "a-dragons-story",
    name: "A Dragon&#8217;s Story",
    description:
      "This is a story about a dragon. As all dragons, Ruffs heart burns with a fiery passion for gold. Help him defend his treasure from Sir William. If the knight dares to enter the lair, send him a fireball and watch him run. The more he runs the bigger the win. Ruff also has a buddy, a green little dragon that burn symbols to reveal wilds. He looks a bit angry, but hes a really good friend. Play the Superbet and youll meet more of these fire-breathing creatures.",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2017/01/a_dragons_story_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2017/01/a_dragons_story_bg.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "4b6ab4f0-9629-11e8-b612-0242ac110002",
    providerId: "cb0a8190-15b7-11e5-a40d-005056a03973",
    slug: "a-la-carte",
    name: "A La Carte",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/07/a_la_carte_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/07/a_la_carte_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "758630c0-58df-11e8-a764-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "abracadabra",
    name: "Abracardabra",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/04/abracardabra_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/04/abracardabra_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "1e7e0f90-9f56-11e5-9785-005056a03af2",
    providerId: "f1d0f670-15ac-11e5-adb5-005056a03973",
    slug: "ace-of-spades",
    name: "Ace Of Spades",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/07/ace_of_spades_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/07/ace_of_spades_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "aa7f8870-7a05-11e8-b267-0242ac110002",
    providerId: "1ad9a810-2425-11e5-bd73-005056a03973",
    slug: "aces-eights-poker",
    name: "Aces &#038; Eights Poker",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2017/09/aces_and_8s_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2017/09/green_bg_vp_mg.png",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "VIDEO_POKER",
    media: [],
  },
  {
    id: "83684000-7a06-11e8-b267-0242ac110002",
    providerId: "1ad9a810-2425-11e5-bd73-005056a03973",
    slug: "aces-faces",
    name: "Aces &#038; Faces Poker",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2017/09/aces_and_faces.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2017/09/blue_bg_vp_mg.png",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "VIDEO_POKER",
    media: [],
  },
  {
    id: "81bd94d0-e8b5-11e8-8e3a-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "action-bank",
    name: "Action Bank",
    description:
      "A old-school looking slot for the online slot player of today. Match three, four or five symbols on any of the 20 paylines and win. It is that simple! With wild symbols you will achieve your goal easier. Open the bonus game and get the chance to obtain a big win. Enter the bank vault and pick a lock. Gain up to 30 free spins or get access to a second bonus game. Get three diamonds, sapphires or rubies in a row and watch your money grow on Action Bank!",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2015/04/action-bank_game-logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2015/04/action-bank_game-backgroundplate.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "22cbe520-f7b1-11e8-b148-0242ac110002",
    providerId: "1ad9a810-2425-11e5-bd73-005056a03973",
    slug: "action-ops-snow-and-sable",
    name: "Action Ops: Snow And Sable",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/11/action_ops_snow_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/11/action_ops_snow_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [
      {
        order: 1,
        path:
          "https://cms.casumo.com/wp-content/uploads/2018/11/action_ops_snow_preview.jpg",
        type: "image",
      },
    ],
  },
  {
    id: "7a862470-1ae3-11e8-8de6-005056a03af2",
    providerId: "d8ffb890-3c4f-11e7-8fe5-0242ac110007",
    slug: "adventure-cab",
    name: "Adventure Cab",
    description:
      "Adventure Cab is a cascading slot like no other. Swipe bugs off the windshield to collect wins by matching 3 or more bugs of the same type. Collect special bugs to trigger a Free Spins Bonus Game. Other features include an incrementing payout multiplier, the Swarm Feature and Bug Zapper game that lets you zap away 2 bugs of your choice to be replaced by new bugs. \r\n\r\n<strong>RTP 97.14%</strong>",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2017/09/AdventureCab_thumbnail_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2017/09/AdventureCab_thumbnail_bg.png",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "32d9e6c0-7ac4-11e8-992d-0242ac110002",
    providerId: "1ad9a810-2425-11e5-bd73-005056a03973",
    slug: "adventures-palace",
    name: "Adventure Palace",
    description:
      "Are you adventurous enough to try this exciting slot? Adventure Palace from Microgaming takes you deep into the heart of the tropical playground where cobras and tigers prowl. In the lush green jungle you will find peacocks strut around with its colorful feathers and monkeys who jump from tree to tree. Juicy prizes are available for those who dare to go there . Dont panic if you see a six-ton elephant marching towards you. The rules of the jungle are different! Are you ready to play?",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2016/07/adventure_palace_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2016/07/adventure_palace_bg.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "3e127fb0-78f1-11e6-888f-005056a03af2",
    providerId: "b9ebe9d0-7bcf-11e4-a8c0-005056a03973",
    slug: "african-simba",
    name: "African Simba",
    description:
      "Welcome to Tanzania! Enjoy the countrys magnificent wilderness and benefit from 243 ways to win. Watch the animals in their natural habitat and collect roaring winnings. Be on the lookout for the king of the savanna and boost your winning chances. Take a trip to Mount Kilimanjaro and find mighty bonus action. Activate the free games feature and get the opportunity to triple all your wins. Play the African Simba slot and go on a winning safari!",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2016/09/african_simba_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2016/09/african_simba_bg.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "8b52fad0-7ac4-11e8-992d-0242ac110002",
    providerId: "1ad9a810-2425-11e5-bd73-005056a03973",
    slug: "age-of-discovery",
    name: "Age of Discovery",
    description:
      "Are you a landlubber or a true voyager? This slot will put your navigating skills to test! Microgaming has come up with an unique theme: the Age of Discoveries. Be an explorer and discover new lands and plentiful wins. Watch out for the storms and let´s hope there will be no pirates! For the adventurous this is a real opportunity. The promise of gold and silver treasures lingers in the air like the sweet aroma of precious spices&#8230; Columbus, here I come!",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2016/07/age_of_discovery_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2016/07/age_of_discovery_bg.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "b8074cd0-8f19-11e7-aa86-005056a03af2",
    providerId: "b9ebe9d0-7bcf-11e4-a8c0-005056a03973",
    slug: "age-of-privateers",
    name: "Age of Privateers",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2017/07/age_of_privateers_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2017/07/age_of_privateers_bg.jpg",
    hasPlayForFun: false,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "ccca26d0-3d6d-11e8-bfe2-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "aladdins-legacy",
    name: "Aladdin&#8217;s Legacy",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/04/aladdins_legacy_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/04/aladdins_legacy_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "64e4eab0-7ac5-11e8-992d-0242ac110002",
    providerId: "1ad9a810-2425-11e5-bd73-005056a03973",
    slug: "alaskan-fishing",
    name: "Alaskan Fishing",
    description:
      "Head to Alaska and fish for a big win! Throw out your fishing line and enjoy a pristine wilderness and 243 ways to win. Pull up the largest salmon and look forward to wins and bragging rights. Spin the fishing boxes in view and trigger the free spins. Get the fish to bite and double your wins. Find the best fishing spots in the bonus game and multiply your win up to 12 times your bet. Play the Alaskan Fishing slot and be part of a grand fishing adventure!",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2016/04/Alaskan-Fishing_game-thumb-logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2016/04/Alaskan-Fishing_game-thumb-plate.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "cb3c61d0-622a-11e7-8677-005056a03af2",
    providerId: "df8213e1-6227-11e7-9c6a-0242ac110008",
    slug: "alchymedes",
    name: "Alchymedes",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2017/06/alchymedes_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2017/06/alchymedes_bg.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "40b05690-e1a2-11e8-ae01-0242ac110002",
    providerId: "b9ebe9d0-7bcf-11e4-a8c0-005056a03973",
    slug: "almighty-reels-garden-of-persephone",
    name: "Almighty Reels &#8211; Garden of Persephone",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/10/garden-of-persephone_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/10/garden-of-persephone_thumbnail.jpg",
    hasPlayForFun: false,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "c1f01e91-f0ee-11e5-8f76-005056a03af2",
    providerId: "c4204890-0842-11e2-b0fd-005056bf4a60",
    slug: "aloha-cluster-pays",
    name: "Aloha! Cluster Pays",
    description:
      "Aloha, fly to a paradise island where Tiki heads host a party all day long. Aloha Cluster Pays is no ordinary slot. When then 9 or more symbols join together in a cluster it is a winning combination. Free spins feast starts when you get 3 or more stamp symbols. The common symbols starts dropping from the reels after a few rounds of free spins. Soon only the big win Tiki heads remain pretty much guaranteeing big wins on last spins. Those Tikis sure know how to party.",
    jackpotId: null,
    liveCasinoId: null,
    logo: "https://cms.casumo.com/wp-content/uploads/2016/03/aloha_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2016/03/aloha_bp.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "2b8a01c0-816a-11e6-895c-005056a03af2",
    providerId: "b9ebe9d0-7bcf-11e4-a8c0-005056a03973",
    slug: "always-hot",
    name: "Always Hot deluxe",
    description:
      "Play the Always Hot Deluxe and get the chance to gain plenty of bucks! Have fun with this classic three-reel slot, but remember, the wins are really hot. So receive your claims before they go up in flames. Find many delicious sweets and collect lots and lots of yummy treats. The symbols here come in two, which means bigger wins for you. Land three matching sevens side by side and go for a winning ride!",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2016/09/always_hot_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2016/09/always_hot_bg.jpg",
    hasPlayForFun: false,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "c59a2420-63f9-11e8-9f13-0242ac110002",
    providerId: "1ad9a810-2425-11e5-bd73-005056a03973",
    slug: "amazing-aztecs",
    name: "Amazing Aztecs",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/05/amazing_aztecs_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/05/amazing_aztecs_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "374955d0-3d6e-11e8-bfe2-0242ac110002",
    providerId: "b9ebe9d0-7bcf-11e4-a8c0-005056a03973",
    slug: "amazing-fruits",
    name: "Amazing Fruits",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/04/amazing_fruits_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/04/amazing_fruits_thumbnail.jpg",
    hasPlayForFun: false,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "54929d70-816a-11e6-895c-005056a03af2",
    providerId: "b9ebe9d0-7bcf-11e4-a8c0-005056a03973",
    slug: "amazing-stars",
    name: "Amazing Stars",
    description:
      "Amazing Stars is sure to tickle your taste buds! If you like fruits, berries and beautiful graphics this is the place to be. Here you can pick the juiciest oranges and lemons and the sweetest plums and cherries. And the most delicious grapes and melons are there for the taking. But this stunning slot offers you more than just vitamins. You can also win Free Games and two jackpots. That is absolutely amazing!",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2016/09/amazing_stars_logo2.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2016/09/amazing_stars_bg.jpg",
    hasPlayForFun: false,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "a93df570-f3cf-11e8-b6a2-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "amazon-queen",
    name: "Amazon Queen",
    description:
      "Deep in the South American rainforest the Amazon queen reigns over a vast country. In the trees sits blue-and-yellow macaws and screaming. If you look close you can see a yellow anaconda wrapped around a tree branch. Here also live&#8230;gorillas and tigers! What! Gorillas and tigers in the Amazon jungle. How did they get here? The gorillas pay left to right and give you the opportunity to collect lots of exotic winnings from Amazon Queen.",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2015/03/amazonqueen_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2015/03/amazonqueen_backplate.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "a539ae30-4451-11e7-9e41-005056a03af2",
    providerId: "b9ebe9d0-7bcf-11e4-a8c0-005056a03973",
    slug: "amazons-diamonds",
    name: "Amazons Diamonds",
    description:
      "Stacked scatters that offer up to 30 free spins are certainly something to go for in Amazons Diamond slot. Bet on thirty paylines and double up any win with the gamble feature, as many time as you dare! Find the hidden gem and use it to substitute for any other symbol, even the beauty of amazon&#8217;s pale in comparison to the prizes you can grab! Stack the screen full of wilds for a payout that fills your pockets with coins. Tame the wild animals and let them loose on the reels for wild wins!",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2017/05/amazons_diamonds_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2017/05/amazons_diamonds_bg.jpg",
    hasPlayForFun: false,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "10a05540-63df-11e8-b43f-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "ambassador",
    name: "Ambassador",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/05/ambassador_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/05/ambassador_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "c729b1d2-7bd0-11e4-8af5-005056a03af2",
    providerId: "b9ebe9d0-7bcf-11e4-a8c0-005056a03973",
    slug: "american-poker-ii",
    name: "American Poker II",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2016/08/Greentube-AmericanPokerII-Logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2016/08/Greentube-AmericanPokerII-thumbnail.jpg",
    hasPlayForFun: false,
    inMaintenance: false,
    category: "VIDEO_POKER",
    media: [],
  },
  {
    id: "7520ab50-5f39-11e8-a182-0242ac110002",
    providerId: "c4204890-0842-11e2-b0fd-005056bf4a60",
    slug: "american-roulette",
    name: "American Roulette",
    description:
      "We&#8217;re in Vegas baby! Prepare for a world class experience with an attractive table and billboard, cool and interactive design and voice announcements. Tonight we&#8217;re playing roulette the American way and we all know what that means. Now spin that ball, croupier!",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2012/05/AmericanRoulette_Logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2012/05/AmericanRouletteBack.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "TABLE_GAME",
    media: [],
  },
  {
    id: "890762e0-73ce-11e8-929f-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "anchorman",
    name: "Anchorman",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/06/anchorman_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/06/anchorman_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "037e68c0-998b-11e8-9172-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "ancient-egypt",
    name: "Ancient Egypt",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/09/ancient_egypt_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/09/ancient_egypt_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
  {
    id: "3255f710-dc27-11e8-a57b-0242ac110002",
    providerId: "0c900240-4904-11e6-a7a2-005056a975b1",
    slug: "ancient-egypt-classic",
    name: "Ancient Egypt Classic",
    description: "",
    jackpotId: null,
    liveCasinoId: null,
    logo:
      "https://cms.casumo.com/wp-content/uploads/2018/10/ancient_egypt_logo.png",
    logoBackground:
      "https://cms.casumo.com/wp-content/uploads/2018/10/ancient_egypt_thumbnail.jpg",
    hasPlayForFun: true,
    inMaintenance: false,
    category: "SLOT_MACHINE",
    media: [],
  },
];
