const sports = [
  {
    id: 1000093190,
    userFavourite: true,
    canSelectSubgroups: true,
    __typename: "EventGroup",
    name: "Football",
    popular: true,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/handball.svg",
    favouriteCompetitions: [
      {
        id: 1000093381,
        userFavourite: true,
        name: "Champions League",
        flagEmoji: "🇪🇺",
        __typename: "EventGroup",
      },
      {
        id: 1000094985,
        userFavourite: true,
        name: "Premier League",
        flagEmoji: null,
        __typename: "EventGroup",
      },
      {
        id: 1000094981,
        userFavourite: true,
        name: "The Championship",
        flagEmoji: null,
        __typename: "EventGroup",
      },
      {
        id: 2000051195,
        userFavourite: true,
        name: "Europa League",
        flagEmoji: "🇪🇺",
        __typename: "EventGroup",
      },
      {
        id: 1000095057,
        userFavourite: true,
        name: "Allsvenskan",
        flagEmoji: null,
        __typename: "EventGroup",
      },
    ],
  },
  {
    id: 1000093193,
    userFavourite: true,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Tennis",
    popular: false,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/tennis.svg",
    favouriteCompetitions: [],
  },
  {
    id: 1000093187,
    userFavourite: true,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Golf",
    popular: false,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/golf.svg",
    favouriteCompetitions: [],
  },
  {
    id: 1000093199,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "American Football",
    popular: false,
    icon:
      "https://cms.casumo.com/wp-content/uploads/2019/02/american-football.svg",
    favouriteCompetitions: [],
  },
  {
    id: 1000093200,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Athletics",
    popular: false,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/athletics.svg",
    favouriteCompetitions: [],
  },
  {
    id: 1000449347,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Australian Rules",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 1000093192,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Bandy",
    popular: false,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/bandy.svg",
    favouriteCompetitions: [],
  },
  {
    id: 1000093211,
    userFavourite: true,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Baseball",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 1000093204,
    userFavourite: true,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Basketball",
    popular: true,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/basketball.svg",
    favouriteCompetitions: [],
  },
  {
    id: 1000093201,
    userFavourite: true,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Boxing",
    popular: false,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/boxing.svg",
    favouriteCompetitions: [],
  },
  {
    id: 1000190837,
    userFavourite: true,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Chess",
    popular: false,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/chess.svg",
    favouriteCompetitions: [],
  },
  {
    id: 1000093178,
    userFavourite: true,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Cricket",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 1000093233,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Cycling",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 1000093225,
    userFavourite: true,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Darts",
    popular: false,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/darts.svg",
    favouriteCompetitions: [],
  },
  {
    id: 2000077768,
    userFavourite: true,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Esports",
    popular: false,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/e-sports.svg",
    favouriteCompetitions: [],
  },
  {
    id: 1000093206,
    userFavourite: true,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Floorball",
    popular: false,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/floorball.svg",
    favouriteCompetitions: [],
  },
  {
    id: 1000093184,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Futsal",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 2000087309,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Gaelic Sports",
    popular: false,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/gaelic.svg",
    favouriteCompetitions: [],
  },
  {
    id: 2000065087,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Greyhounds",
    popular: false,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/greyhound.svg",
    favouriteCompetitions: [],
  },
  {
    id: 1000093205,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Handball",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 2000065773,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Horse Racing",
    popular: false,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/horse_racing.svg",
    favouriteCompetitions: [],
  },
  {
    id: 1000093191,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Ice Hockey",
    popular: false,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/ice_hockey.svg",
    favouriteCompetitions: [],
  },
  {
    id: 2000050136,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Motorsports",
    popular: false,
    icon: "https://cms.casumo.com/wp-content/uploads/2019/02/motorsports.svg",
    favouriteCompetitions: [],
  },
  {
    id: 2000054941,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Netball",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 1000093179,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Olympic Games",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 2000061894,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Politics",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 1000154363,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Rugby League",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 1000093230,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Rugby Union",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 1000093176,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Snooker",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 2000061311,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Surfing",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 1000093195,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Trotting",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 2000053071,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "TV & Novelty",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 1000093238,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "UFC/MMA",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 1000093214,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Volleyball",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 1000093180,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Winter Olympic Games",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 1000217859,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Winter Sports",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 2000089034,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "WWE/Pro Wrestling",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
  {
    id: 1000093260,
    userFavourite: false,
    canSelectSubgroups: false,
    __typename: "EventGroup",
    name: "Z_Sports",
    popular: false,
    icon: null,
    favouriteCompetitions: [],
  },
];

const sportsWithNoFavourites = sports.map(sport => ({
  ...sport,
  userFavourite: false,
  favouriteCompetitions: [],
}));

export const withFavouritesResult = {
  groups: sports,
};

export const noFavouritesResult = {
  groups: sportsWithNoFavourites,
};
