import { TPlayOkaySettingsTranslations } from "../playOkay.types";

export const settingsCms: TPlayOkaySettingsTranslations = {
  available_amount_daily: "{{amount}} left today",
  available_amount_weekly: "{{amount}} left this week",
  available_amount_monthly: "{{amount}} left this month",
  available_amount_indefinite: "{{amount}} left",
  available_amount_loginblockstart: "",
  available_amount_loginblockend: "",
  cancel_coming_change: "Cancel",
  coming_limit_note: "{{period}} limit will be set to {{amount}} on {{date}}.",
  coming_revocation_note: "This limit will be revoked on {{date}}.",
  form_allow_single_period_copy: "You can have one limit defined at any given moment.",
  form_error_request_failed: "Saving failed. Please try again later or contact our support.",
  form_input_helper_daily: "Limit per day",
  form_input_helper_weekly: "Limit per week",
  form_input_helper_monthly: "Limit per month",
  form_input_helper_hours_daily: "Hours per day",
  form_input_helper_hours_weekly: "Hours per week",
  form_input_helper_hours_monthly: "Hours per month",
  form_input_helper_hours_indefinite: "Hours",
  form_input_helper_hours_loginblockend: "",
  form_input_helper_hours_loginblockstart: "",
  form_input_helper_indefinite: "",
  form_input_helper_loginblockend: "End time",
  form_input_helper_loginblockstart: "Start time",
  form_input_placeholder: "Text input",
  form_outro_copy_decreasing: "Your new {{period}} limit is now active.",
  form_outro_copy_increasing: "Your new {{period}} limit will be activated on {{date}}.",
  form_outro_copy_initial: "",
  form_outro_copy_revoking: "Your {{period}} limit will be revoked on {{date}}.",
  form_outro_cta: "OK",
  period_daily: "Daily",
  period_weekly: "Weekly",
  period_monthly: "Monthly",
  period_loginblockstart: "Start time",
  period_loginblockend: "End time",
  period_indefinite: "Indefinitely",
  subtitle_affordabilitylimit: "",
  subtitle_depositlimit: "",
  subtitle_logintimeblock: "",
  subtitle_logintimelimit: "",
  subtitle_losslimit: "",
  subtitle_spendingbudget: "",
  subtitle_wagerlimit: "",
  title_affordabilitylimit: "Affordability Limit",
  title_depositlimit: "Deposit Limit",
  title_logintimeblock: "Login Time Block",
  title_logintimelimit: "Login Time Limit",
  title_losslimit: "Loss Limit",
  title_spendingbudget: "Spending Budget",
  title_wagerlimit: "Wager Limit",
  form_validator_none_required: "",
  form_validator_all_required: "All limits are mandatory",
  form_validator_anyone_required: "You need to have at least one limit defined.",
  form_validator_anytwo_required: "You need to have at least two limits defined.",
  form_validator_period_too_high: "This limit is too high.",
  form_validator_period_too_low: "This limit is too low.",
  data_not_loaded_error: "Please refresh the page or contact our support if this error persists."
};