// @flow
export const methodTypes = [
  { type: "APPLEPAY", displayName: "ApplePay", inMaintenanceMode: false },
  {
    type: "ASTROPAYCARD",
    displayName: "AstroPay Card",
    inMaintenanceMode: false,
  },
  {
    type: "BANK_DEPOSIT",
    displayName: "Bank Deposit",
    inMaintenanceMode: false,
  },
  {
    type: "BANK_WITHDRAW",
    displayName: "Bank Withdrawal",
    inMaintenanceMode: false,
  },
  { type: "BOKU", displayName: "Boku", inMaintenanceMode: true },
  {
    type: "FUNANGACASHTOCODE",
    displayName: "CashtoCode (Funanga)",
    inMaintenanceMode: false,
  },
  { type: "EPS", displayName: "EPS", inMaintenanceMode: false },
  {
    type: "EPROPAYMENTWALL",
    displayName: "EProPaymentWall",
    inMaintenanceMode: false,
  },
  { type: "ECOBANQ", displayName: "EcoBanq", inMaintenanceMode: false },
  { type: "ECOPAYZ", displayName: "EcoPayz", inMaintenanceMode: false },
  { type: "FONIX", displayName: "Fonix", inMaintenanceMode: false },
  { type: "GIROPAY", displayName: "Giropay", inMaintenanceMode: false },
  {
    type: "GIROPAY_BY_SKRILLQCO",
    displayName: "Giropay by Skrill",
    inMaintenanceMode: false,
  },
  { type: "IDEBIT", displayName: "IDebit", inMaintenanceMode: false },
  { type: "IDEAL", displayName: "Ideal", inMaintenanceMode: false },
  { type: "INSTADEBIT", displayName: "InstaDebit", inMaintenanceMode: false },
  { type: "INTERAC", displayName: "Interac", inMaintenanceMode: false },
  { type: "JCB_CARD", displayName: "JCB", inMaintenanceMode: false },
  { type: "MASTER_CARD", displayName: "MasterCard", inMaintenanceMode: false },
  { type: "MOBILEPAY", displayName: "MobilePay", inMaintenanceMode: false },
  { type: "MUCHBETTER", displayName: "MuchBetter", inMaintenanceMode: false },
  { type: "NETELLER", displayName: "Neteller", inMaintenanceMode: false },
  { type: "POLI", displayName: "POLi", inMaintenanceMode: false },
  { type: "PAYPAL", displayName: "PayPal", inMaintenanceMode: false },
  { type: "PAYSAFECARD", displayName: "Paysafe", inMaintenanceMode: false },
  { type: "PUGGLEPAY", displayName: "PugglePay", inMaintenanceMode: false },
  { type: "SIIRTO", displayName: "Siirto", inMaintenanceMode: false },
  { type: "MONEYBOOKERS", displayName: "Skrill", inMaintenanceMode: false },
  {
    type: "SKRILLQUICKCHECKOUT",
    displayName: "SkrillQuickCheckout",
    inMaintenanceMode: false,
  },
  { type: "SOFORT", displayName: "Sofort", inMaintenanceMode: false },
  {
    type: "SOFORT_BY_SKRILLQCO",
    displayName: "Sofort by Skrill",
    inMaintenanceMode: false,
  },
  { type: "STICPAY", displayName: "Sticpay", inMaintenanceMode: false },
  { type: "SWISH", displayName: "Swish", inMaintenanceMode: false },
  { type: "TRUSTLY", displayName: "Trustly", inMaintenanceMode: false },
  { type: "VENUSPOINT", displayName: "Venus Point", inMaintenanceMode: false },
  { type: "VISA_CARD", displayName: "Visa", inMaintenanceMode: false },
  {
    type: "ZIMPLERBANK",
    displayName: "Zimpler Bank",
    inMaintenanceMode: false,
  },
  {
    type: "ZIMPLERPHONE",
    displayName: "Zimpler Phone",
    inMaintenanceMode: false,
  },
  { type: "IWALLET", displayName: "iWallet", inMaintenanceMode: false },
];
