export default {
  data: {
    group: {
      __typename: "EventGroup",
      name: "Football",
      groups: [
        {
          __typename: "EventGroup",
          id: 1000093381,
          popular: false,
          name: "Champions League",
          groups: null,
        },
        {
          __typename: "EventGroup",
          id: 1000461733,
          popular: false,
          name: "England",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000094985,
              popular: true,
              userFavourite: true,
              name: "Premier League",
              flagEmoji: "🇬🇧",
            },
            {
              __typename: "EventGroup",
              id: 1000094981,
              popular: true,
              userFavourite: true,
              name: "The Championship",
              flagEmoji: "🇬🇧",
            },
            {
              __typename: "EventGroup",
              id: 1000094982,
              popular: false,
              userFavourite: false,
              name: "League One",
              flagEmoji: "🇬🇧",
            },
            {
              __typename: "EventGroup",
              id: 1000094987,
              popular: false,
              userFavourite: false,
              name: "League Two",
              flagEmoji: "🇬🇧",
            },
            {
              __typename: "EventGroup",
              id: 1000094984,
              popular: false,
              userFavourite: false,
              name: "FA Cup",
              flagEmoji: "🇬🇧",
            },
            {
              __typename: "EventGroup",
              id: 1000094986,
              popular: false,
              userFavourite: false,
              name: "EFL Cup",
              flagEmoji: "🇬🇧",
            },
            {
              __typename: "EventGroup",
              id: 2000054642,
              popular: false,
              userFavourite: false,
              name: "Isthmian League Premier Division",
              flagEmoji: "🇬🇧",
            },
            {
              __typename: "EventGroup",
              id: 1000095485,
              popular: false,
              userFavourite: false,
              name: "National League",
              flagEmoji: "🇬🇧",
            },
            {
              __typename: "EventGroup",
              id: 2000073684,
              popular: false,
              userFavourite: false,
              name: "Non League/County Cups",
              flagEmoji: "🇬🇧",
            },
            {
              __typename: "EventGroup",
              id: 2000080468,
              popular: false,
              userFavourite: false,
              name: "The Championship (W)",
              flagEmoji: "🇬🇧",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461745,
          popular: false,
          name: "Italy",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000095001,
              popular: false,
              userFavourite: false,
              name: "Serie A",
              flagEmoji: "🇮🇹",
            },
            {
              __typename: "EventGroup",
              id: 1000095002,
              popular: false,
              userFavourite: false,
              name: "Serie B",
              flagEmoji: "🇮🇹",
            },
            {
              __typename: "EventGroup",
              id: 1000094998,
              popular: false,
              userFavourite: false,
              name: "TIM Cup",
              flagEmoji: "🇮🇹",
            },
            {
              __typename: "EventGroup",
              id: 2000079607,
              popular: false,
              userFavourite: false,
              name: "Serie C Girone A",
              flagEmoji: "🇮🇹",
            },
            {
              __typename: "EventGroup",
              id: 2000079609,
              popular: false,
              userFavourite: false,
              name: "Serie C Girone C",
              flagEmoji: "🇮🇹",
            },
            {
              __typename: "EventGroup",
              id: 2000056085,
              popular: false,
              userFavourite: false,
              name: "Serie D",
              flagEmoji: "🇮🇹",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461813,
          popular: false,
          name: "Spain",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000095049,
              popular: false,
              userFavourite: false,
              name: "La Liga",
              flagEmoji: "🇪🇸",
            },
            {
              __typename: "EventGroup",
              id: 1000094708,
              popular: false,
              userFavourite: false,
              name: "La Liga 2",
              flagEmoji: "🇪🇸",
            },
            {
              __typename: "EventGroup",
              id: 1000095050,
              popular: false,
              userFavourite: false,
              name: "Copa del Rey",
              flagEmoji: "🇪🇸",
            },
            {
              __typename: "EventGroup",
              id: 2000054359,
              popular: false,
              userFavourite: false,
              name: "Copa Federación",
              flagEmoji: "🇪🇸",
            },
            {
              __typename: "EventGroup",
              id: 2000051626,
              popular: false,
              userFavourite: false,
              name: "Superliga Femenina (W)",
              flagEmoji: "🇪🇸",
            },
            {
              __typename: "EventGroup",
              id: 2000103574,
              popular: false,
              userFavourite: false,
              name: "Tercera División 2",
              flagEmoji: "🇪🇸",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461728,
          popular: false,
          name: "Germany",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000094994,
              popular: false,
              userFavourite: false,
              name: "Bundesliga",
              flagEmoji: "🇩🇪",
            },
            {
              __typename: "EventGroup",
              id: 1000094993,
              popular: false,
              userFavourite: false,
              name: "2. Bundesliga",
              flagEmoji: "🇩🇪",
            },
            {
              __typename: "EventGroup",
              id: 1000355562,
              popular: false,
              userFavourite: false,
              name: "3. Liga",
              flagEmoji: "🇩🇪",
            },
            {
              __typename: "EventGroup",
              id: 1000094995,
              popular: false,
              userFavourite: false,
              name: "DFB Pokal",
              flagEmoji: "🇩🇪",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461727,
          popular: false,
          name: "France",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000094991,
              popular: false,
              userFavourite: false,
              name: "Ligue 1",
              flagEmoji: "🇫🇷",
            },
            {
              __typename: "EventGroup",
              id: 1000094568,
              popular: false,
              userFavourite: false,
              name: "Ligue 2",
              flagEmoji: "🇫🇷",
            },
            {
              __typename: "EventGroup",
              id: 1000094992,
              popular: false,
              userFavourite: false,
              name: "Coupe de la Ligue",
              flagEmoji: "🇫🇷",
            },
            {
              __typename: "EventGroup",
              id: 1000094825,
              popular: false,
              userFavourite: false,
              name: "Championnat National",
              flagEmoji: "🇫🇷",
            },
            {
              __typename: "EventGroup",
              id: 1000181000,
              popular: false,
              userFavourite: false,
              name: "National 2 Group C",
              flagEmoji: "🇫🇷",
            },
            {
              __typename: "EventGroup",
              id: 1000181002,
              popular: false,
              userFavourite: false,
              name: "National 2 Group D",
              flagEmoji: "🇫🇷",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000123032,
          popular: false,
          name: "African Nations Cup",
          groups: null,
        },
        {
          __typename: "EventGroup",
          id: 2000050278,
          popular: false,
          name: "Algeria",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000050279,
              popular: false,
              userFavourite: false,
              name: "Ligue 1",
              flagEmoji: "🇩🇿",
            },
            {
              __typename: "EventGroup",
              id: 2000082448,
              popular: false,
              userFavourite: false,
              name: "Ligue 2 U21",
              flagEmoji: "🇩🇿",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461754,
          popular: false,
          name: "Argentina",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000050561,
              popular: false,
              userFavourite: false,
              name: "Primera Division",
              flagEmoji: "🇦🇷",
            },
            {
              __typename: "EventGroup",
              id: 2000061427,
              popular: false,
              userFavourite: false,
              name: "Reserves Leagues",
              flagEmoji: "🇦🇷",
            },
            {
              __typename: "EventGroup",
              id: 2000087788,
              popular: false,
              userFavourite: false,
              name: "Torneo Federal A",
              flagEmoji: "🇦🇷",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461755,
          popular: false,
          name: "Australia",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000182606,
              popular: false,
              userFavourite: false,
              name: "A-League",
              flagEmoji: "🇦🇺",
            },
            {
              __typename: "EventGroup",
              id: 2000051282,
              popular: false,
              userFavourite: false,
              name: "W-League (W)",
              flagEmoji: "🇦🇺",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461751,
          popular: false,
          name: "Austria",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000345237,
              popular: true,
              userFavourite: false,
              name: "Bundesliga",
              flagEmoji: "🇦🇹",
            },
            {
              __typename: "EventGroup",
              id: 1000094692,
              popular: false,
              userFavourite: false,
              name: "ÖFB Cup",
              flagEmoji: "🇦🇹",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000052393,
          popular: false,
          name: "Azerbaijan",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000056769,
              popular: false,
              userFavourite: false,
              name: "1st Division",
              flagEmoji: "🇦🇿",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000063155,
          popular: false,
          name: "Bangladesh",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000063156,
              popular: false,
              userFavourite: false,
              name: "Premier League",
              flagEmoji: "🇧🇩",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461740,
          popular: false,
          name: "Belgium",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000094965,
              popular: false,
              userFavourite: false,
              name: "Jupiler Pro League",
              flagEmoji: "🇧🇪",
            },
            {
              __typename: "EventGroup",
              id: 1000094961,
              popular: false,
              userFavourite: false,
              name: "Beker van Belgie",
              flagEmoji: "🇧🇪",
            },
            {
              __typename: "EventGroup",
              id: 1000358593,
              popular: false,
              userFavourite: false,
              name: "Proximus League",
              flagEmoji: "🇧🇪",
            },
            {
              __typename: "EventGroup",
              id: 1000094954,
              popular: false,
              userFavourite: false,
              name: "Eerste Klasse Amateurs",
              flagEmoji: "🇧🇪",
            },
            {
              __typename: "EventGroup",
              id: 2000096513,
              popular: false,
              userFavourite: false,
              name: "Tweede Klasse Amateurs ACFF",
              flagEmoji: "🇧🇪",
            },
            {
              __typename: "EventGroup",
              id: 2000096514,
              popular: false,
              userFavourite: false,
              name: "Tweede Klasse Amateurs VFV A",
              flagEmoji: "🇧🇪",
            },
            {
              __typename: "EventGroup",
              id: 2000096515,
              popular: false,
              userFavourite: false,
              name: "Tweede Klasse Amateurs VFV B",
              flagEmoji: "🇧🇪",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000051030,
          popular: false,
          name: "Bolivia",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000051031,
              popular: false,
              userFavourite: false,
              name: "Liga Profesional",
              flagEmoji: "🇧🇴",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461741,
          popular: false,
          name: "Brazil",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000094569,
              popular: false,
              userFavourite: false,
              name: "Série A",
              flagEmoji: "🇧🇷",
            },
            {
              __typename: "EventGroup",
              id: 1000094971,
              popular: false,
              userFavourite: false,
              name: "Carioca",
              flagEmoji: "🇧🇷",
            },
            {
              __typename: "EventGroup",
              id: 2000054682,
              popular: false,
              userFavourite: false,
              name: "Cearense",
              flagEmoji: "🇧🇷",
            },
            {
              __typename: "EventGroup",
              id: 1000093998,
              popular: false,
              userFavourite: false,
              name: "Copa do Brasil",
              flagEmoji: "🇧🇷",
            },
            {
              __typename: "EventGroup",
              id: 2000086229,
              popular: false,
              userFavourite: false,
              name: "Paulista A2",
              flagEmoji: "🇧🇷",
            },
            {
              __typename: "EventGroup",
              id: 2000064212,
              popular: false,
              userFavourite: false,
              name: "Paulista A3",
              flagEmoji: "🇧🇷",
            },
            {
              __typename: "EventGroup",
              id: 2000087049,
              popular: false,
              userFavourite: false,
              name: "Piauiense",
              flagEmoji: "🇧🇷",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461757,
          popular: false,
          name: "Bulgaria",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000285388,
              popular: false,
              userFavourite: false,
              name: "Cup",
              flagEmoji: "🇵🇸",
            },
            {
              __typename: "EventGroup",
              id: 1000383831,
              popular: false,
              userFavourite: false,
              name: "PFL 1",
              flagEmoji: "🇧🇬",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000056939,
          popular: false,
          name: "Cameroon",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000092970,
              popular: false,
              userFavourite: false,
              name: "Elite Two",
              flagEmoji: "🇨🇲",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000093393,
          popular: false,
          name: "Club Friendly Matches",
          groups: null,
        },
        {
          __typename: "EventGroup",
          id: 2000057348,
          popular: false,
          name: "Club Tournaments",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000057361,
              popular: false,
              userFavourite: false,
              name: "CAF Confederations Cup",
              flagEmoji: null,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461759,
          popular: false,
          name: "Colombia",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000050211,
              popular: false,
              userFavourite: false,
              name: "Copa Colombia",
              flagEmoji: "🇨🇴",
            },
            {
              __typename: "EventGroup",
              id: 1000449742,
              popular: false,
              userFavourite: false,
              name: "Liga Águila",
              flagEmoji: "🇨🇴",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000114415,
          popular: false,
          name: "CONCACAF Champions League",
          groups: null,
        },
        {
          __typename: "EventGroup",
          id: 1000093398,
          popular: false,
          name: "Copa America",
          groups: null,
        },
        {
          __typename: "EventGroup",
          id: 1000093399,
          popular: false,
          name: "Copa Libertadores",
          groups: null,
        },
        {
          __typename: "EventGroup",
          id: 1000179126,
          popular: false,
          name: "Copa Sudamericana",
          groups: null,
        },
        {
          __typename: "EventGroup",
          id: 2000050275,
          popular: false,
          name: "Costa Rica",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000050276,
              popular: false,
              userFavourite: false,
              name: "Primera Division",
              flagEmoji: "🇨🇷",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461739,
          popular: false,
          name: "Croatia",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000095736,
              popular: false,
              userFavourite: false,
              name: "1. HNL League",
              flagEmoji: "🇭🇷",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461735,
          popular: false,
          name: "Czech Republic",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000094975,
              popular: false,
              userFavourite: false,
              name: "First League",
              flagEmoji: "🇨🇿",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461736,
          popular: false,
          name: "Denmark",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000094978,
              popular: false,
              userFavourite: false,
              name: "Superligaen",
              flagEmoji: "🇩🇰",
            },
            {
              __typename: "EventGroup",
              id: 1000443738,
              popular: false,
              userFavourite: false,
              name: "Sydbank Pokalen",
              flagEmoji: "🇩🇰",
            },
            {
              __typename: "EventGroup",
              id: 1000094976,
              popular: false,
              userFavourite: false,
              name: "1st Division",
              flagEmoji: "🇩🇰",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461807,
          popular: false,
          name: "Egypt",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000055763,
              popular: false,
              userFavourite: false,
              name: "2nd Division",
              flagEmoji: "🇪🇬",
            },
            {
              __typename: "EventGroup",
              id: 1000251645,
              popular: false,
              userFavourite: false,
              name: "Premier League",
              flagEmoji: "🇪🇬",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000075124,
          popular: false,
          name: "El Salvador",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000075125,
              popular: false,
              userFavourite: false,
              name: "Primera Division",
              flagEmoji: "🇸🇻",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000095271,
          popular: false,
          name: "Euro 2020",
          groups: null,
        },
        {
          __typename: "EventGroup",
          id: 2000117846,
          popular: false,
          name: "Euro 2020 Qualification",
          groups: null,
        },
        {
          __typename: "EventGroup",
          id: 2000051195,
          popular: false,
          name: "Europa League",
          groups: null,
        },
        {
          __typename: "EventGroup",
          id: 1000461822,
          popular: false,
          name: "Finland",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000094989,
              popular: false,
              userFavourite: false,
              name: "Veikkausliiga",
              flagEmoji: "🇫🇮",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000050538,
          popular: false,
          name: "Guatemala",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000050539,
              popular: false,
              userFavourite: false,
              name: "Liga Nacional",
              flagEmoji: "🇬🇹",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000055522,
          popular: false,
          name: "Honduras",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000055524,
              popular: false,
              userFavourite: false,
              name: "Liga Nacional",
              flagEmoji: "🇭🇳",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461748,
          popular: false,
          name: "Hungary",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000094997,
              popular: false,
              userFavourite: false,
              name: "NB 1",
              flagEmoji: "🇭🇺",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461749,
          popular: false,
          name: "Iceland",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000083149,
              popular: false,
              userFavourite: false,
              name: "Faxaflói Cup (W)",
              flagEmoji: "🇮🇸",
            },
            {
              __typename: "EventGroup",
              id: 2000055609,
              popular: false,
              userFavourite: false,
              name: "League Cup",
              flagEmoji: "🇮🇸",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000051152,
          popular: false,
          name: "India",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000051953,
              popular: false,
              userFavourite: false,
              name: "I-League",
              flagEmoji: "🇮🇳",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000188298,
          popular: false,
          name: "International Friendly Matches (W)",
          groups: null,
        },
        {
          __typename: "EventGroup",
          id: 1000242145,
          popular: false,
          name: "International Youth Friendlies",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000057396,
              popular: false,
              userFavourite: false,
              name: "Under 19",
              flagEmoji: null,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000057322,
          popular: false,
          name: "International Youth Tournaments",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000057336,
              popular: false,
              userFavourite: false,
              name: "CAF Championship U20",
              flagEmoji: null,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000051705,
          popular: false,
          name: "Iran",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000051706,
              popular: false,
              userFavourite: false,
              name: "Pro League",
              flagEmoji: "🇮🇷",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461750,
          popular: false,
          name: "Ireland",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000095601,
              popular: false,
              userFavourite: false,
              name: "Premier Division",
              flagEmoji: "🇮🇪",
            },
            {
              __typename: "EventGroup",
              id: 2000086608,
              popular: false,
              userFavourite: false,
              name: "Leinster Senior League",
              flagEmoji: "🇮🇪",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461820,
          popular: false,
          name: "Israel",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000057138,
              popular: false,
              userFavourite: false,
              name: "Ligat Nashim (W)",
              flagEmoji: "🇮🇱",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000050579,
          popular: false,
          name: "Jordan",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000050580,
              popular: false,
              userFavourite: false,
              name: "Premier League",
              flagEmoji: "🇯🇴",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000116072,
          popular: false,
          name: "Marcatore",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000116073,
              popular: false,
              userFavourite: false,
              name: "Serie A",
              flagEmoji: null,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461742,
          popular: false,
          name: "Mexico",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000094112,
              popular: false,
              userFavourite: false,
              name: "Liga MX",
              flagEmoji: "🇲🇽",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461753,
          popular: false,
          name: "Netherlands",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000094980,
              popular: false,
              userFavourite: false,
              name: "Eredivisie",
              flagEmoji: "🇳🇱",
            },
            {
              __typename: "EventGroup",
              id: 1000095127,
              popular: false,
              userFavourite: false,
              name: "Eerste Divisie",
              flagEmoji: "🇳🇱",
            },
            {
              __typename: "EventGroup",
              id: 1000094979,
              popular: false,
              userFavourite: false,
              name: "KNVB Beker",
              flagEmoji: "🇳🇱",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000052558,
          popular: false,
          name: "Nigeria",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000052559,
              popular: false,
              userFavourite: false,
              name: "Premier League",
              flagEmoji: "🇳🇬",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000258090,
          popular: false,
          name: "Northern Ireland",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000098633,
              popular: false,
              userFavourite: false,
              name: "Development League U20",
              flagEmoji: "🇬🇧",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461744,
          popular: false,
          name: "Norway",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000095010,
              popular: false,
              userFavourite: false,
              name: "Eliteserien",
              flagEmoji: "🇳🇴",
            },
            {
              __typename: "EventGroup",
              id: 1000095003,
              popular: false,
              userFavourite: false,
              name: "OBOS-ligaen",
              flagEmoji: "🇳🇴",
            },
            {
              __typename: "EventGroup",
              id: 2000100352,
              popular: false,
              userFavourite: false,
              name: "Postnordligaen avd. 1",
              flagEmoji: "🇳🇴",
            },
            {
              __typename: "EventGroup",
              id: 2000100353,
              popular: false,
              userFavourite: false,
              name: "Postnordligaen avd. 2",
              flagEmoji: "🇳🇴",
            },
            {
              __typename: "EventGroup",
              id: 2000100354,
              popular: false,
              userFavourite: false,
              name: "Regionsligaen avd. 1",
              flagEmoji: "🇳🇴",
            },
            {
              __typename: "EventGroup",
              id: 2000100372,
              popular: false,
              userFavourite: false,
              name: "Regionsligaen avd. 2",
              flagEmoji: "🇳🇴",
            },
            {
              __typename: "EventGroup",
              id: 2000100373,
              popular: false,
              userFavourite: false,
              name: "Regionsligaen avd. 3",
              flagEmoji: "🇳🇴",
            },
            {
              __typename: "EventGroup",
              id: 2000100374,
              popular: false,
              userFavourite: false,
              name: "Regionsligaen avd. 4",
              flagEmoji: "🇳🇴",
            },
            {
              __typename: "EventGroup",
              id: 2000100375,
              popular: false,
              userFavourite: false,
              name: "Regionsligaen avd. 5",
              flagEmoji: "🇳🇴",
            },
            {
              __typename: "EventGroup",
              id: 2000100376,
              popular: false,
              userFavourite: false,
              name: "Regionsligaen avd. 6",
              flagEmoji: "🇳🇴",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000055545,
          popular: false,
          name: "Panama",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000055546,
              popular: false,
              userFavourite: false,
              name: "LPF",
              flagEmoji: "🇵🇦",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000050114,
          popular: false,
          name: "Paraguay",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000050115,
              popular: false,
              userFavourite: false,
              name: "Primera Division",
              flagEmoji: "🇵🇾",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461811,
          popular: false,
          name: "Poland",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000385219,
              popular: false,
              userFavourite: false,
              name: "Ekstraklasa",
              flagEmoji: "🇵🇱",
            },
            {
              __typename: "EventGroup",
              id: 1000095016,
              popular: false,
              userFavourite: false,
              name: "Puchar Polski",
              flagEmoji: "🇵🇱",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461812,
          popular: false,
          name: "Portugal",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000095042,
              popular: false,
              userFavourite: false,
              name: "Primeira Liga",
              flagEmoji: "🇵🇹",
            },
            {
              __typename: "EventGroup",
              id: 1000095039,
              popular: false,
              userFavourite: false,
              name: "Taça de Portugal",
              flagEmoji: "🇵🇹",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461806,
          popular: false,
          name: "Qatar",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000054001,
              popular: false,
              userFavourite: false,
              name: "Qatar Stars League",
              flagEmoji: "🇶🇦",
            },
            {
              __typename: "EventGroup",
              id: 2000056484,
              popular: false,
              userFavourite: false,
              name: "Qatargas League",
              flagEmoji: "🇶🇦",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461808,
          popular: false,
          name: "Romania",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000095499,
              popular: false,
              userFavourite: false,
              name: "Liga I",
              flagEmoji: "🇷🇴",
            },
            {
              __typename: "EventGroup",
              id: 2000095935,
              popular: false,
              userFavourite: false,
              name: "Liga II",
              flagEmoji: "🇷🇴",
            },
            {
              __typename: "EventGroup",
              id: 1000095805,
              popular: false,
              userFavourite: false,
              name: "Cupa Romaniei",
              flagEmoji: "🇴🇲",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461809,
          popular: false,
          name: "Russia",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000095590,
              popular: false,
              userFavourite: false,
              name: "Premier League",
              flagEmoji: "🇷🇺",
            },
            {
              __typename: "EventGroup",
              id: 2000084447,
              popular: false,
              userFavourite: false,
              name: "FNL Cup",
              flagEmoji: "🇷🇺",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461819,
          popular: false,
          name: "Saudi Arabia",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000050420,
              popular: false,
              userFavourite: false,
              name: "Division 1",
              flagEmoji: "🇸🇦",
            },
            {
              __typename: "EventGroup",
              id: 1000250591,
              popular: false,
              userFavourite: false,
              name: "Professional League",
              flagEmoji: "🇸🇦",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461810,
          popular: false,
          name: "Scotland",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000095047,
              popular: false,
              userFavourite: false,
              name: "Scottish Premiership",
              flagEmoji: "🇬🇧",
            },
            {
              __typename: "EventGroup",
              id: 1000095045,
              popular: false,
              userFavourite: false,
              name: "Championship",
              flagEmoji: "🇬🇧",
            },
            {
              __typename: "EventGroup",
              id: 1000280417,
              popular: false,
              userFavourite: false,
              name: "League One",
              flagEmoji: "🇬🇧",
            },
            {
              __typename: "EventGroup",
              id: 1000280418,
              popular: false,
              userFavourite: false,
              name: "League Two",
              flagEmoji: "🇬🇧",
            },
            {
              __typename: "EventGroup",
              id: 1000094254,
              popular: false,
              userFavourite: false,
              name: "Scottish Cup",
              flagEmoji: "🇬🇧",
            },
            {
              __typename: "EventGroup",
              id: 2000108773,
              popular: false,
              userFavourite: false,
              name: "Amateur Leagues",
              flagEmoji: "🇬🇧",
            },
            {
              __typename: "EventGroup",
              id: 1000193401,
              popular: false,
              userFavourite: false,
              name: "Challenge Cup",
              flagEmoji: "🇬🇧",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461803,
          popular: false,
          name: "South Africa",
          groups: [
            {
              __typename: "EventGroup",
              id: 2000050659,
              popular: false,
              userFavourite: false,
              name: "Nedbank Cup",
              flagEmoji: "🇿🇦",
            },
            {
              __typename: "EventGroup",
              id: 1000250636,
              popular: false,
              userFavourite: false,
              name: "SA Premier Soccer League",
              flagEmoji: "🇿🇦",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000093791,
          popular: false,
          name: "Specials",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000097836,
              popular: false,
              userFavourite: false,
              name: "Managers",
              flagEmoji: null,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461814,
          popular: false,
          name: "Sweden",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000095057,
              popular: false,
              userFavourite: true,
              name: "Allsvenskan",
              flagEmoji: "🇸🇪",
            },
            {
              __typename: "EventGroup",
              id: 1000095052,
              popular: false,
              userFavourite: false,
              name: "Superettan",
              flagEmoji: "🇸🇪",
            },
            {
              __typename: "EventGroup",
              id: 1000094744,
              popular: false,
              userFavourite: false,
              name: "Division 1 N",
              flagEmoji: "🇸🇪",
            },
            {
              __typename: "EventGroup",
              id: 1000094745,
              popular: false,
              userFavourite: false,
              name: "Division 1 S",
              flagEmoji: "🇸🇪",
            },
            {
              __typename: "EventGroup",
              id: 1000095059,
              popular: false,
              userFavourite: false,
              name: "Svenska Cupen",
              flagEmoji: "🇸🇪",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461815,
          popular: false,
          name: "Switzerland",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000095020,
              popular: false,
              userFavourite: false,
              name: "Super League",
              flagEmoji: "🇨🇭",
            },
            {
              __typename: "EventGroup",
              id: 1000095021,
              popular: false,
              userFavourite: false,
              name: "Challenge League",
              flagEmoji: "🇨🇭",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461821,
          popular: false,
          name: "Turkey",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000095062,
              popular: false,
              userFavourite: false,
              name: "Süper Lig",
              flagEmoji: "🇹🇷",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000151680,
          popular: false,
          name: "UEFA Championship U21",
          groups: null,
        },
        {
          __typename: "EventGroup",
          id: 2000113672,
          popular: false,
          name: "UEFA Nations League",
          groups: null,
        },
        {
          __typename: "EventGroup",
          id: 1000461804,
          popular: false,
          name: "Ukraine",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000171537,
              popular: false,
              userFavourite: false,
              name: "Premier League",
              flagEmoji: "🇺🇦",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461805,
          popular: false,
          name: "United Arab Emirates",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000253277,
              popular: false,
              userFavourite: false,
              name: "Arabian Gulf League",
              flagEmoji: "🇦🇪",
            },
            {
              __typename: "EventGroup",
              id: 2000054582,
              popular: false,
              userFavourite: false,
              name: "U21 League",
              flagEmoji: "🇦🇪",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461816,
          popular: false,
          name: "USA",
          groups: [
            {
              __typename: "EventGroup",
              id: 1000095063,
              popular: false,
              userFavourite: false,
              name: "MLS",
              flagEmoji: "🇺🇸",
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000101172,
          popular: false,
          name: "World Cup (W)",
          groups: null,
        },
        {
          __typename: "EventGroup",
          id: 2000116272,
          popular: false,
          name: "World Cup 2022",
          groups: null,
        },
      ],
    },
  },
};
