export default {
  data: {
    group: {
      __typename: "EventGroup",
      name: "Football",
      groups: [
        {
          __typename: "EventGroup",
          id: 1000093381,
          popular: true,
          name: "Champions League",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000461733,
          popular: false,
          name: "England",
          groups: [
            {
              id: 1000094985,
              userFavourite: true,
              name: "Premier League",
              regionCode: "GB-ENG",
              __typename: "EventGroup",
              popular: true,
            },
            {
              id: 1000094981,
              userFavourite: true,
              name: "The Championship",
              regionCode: "GB-ENG",
              __typename: "EventGroup",
              popular: true,
            },
            {
              id: 1000094982,
              userFavourite: false,
              name: "League One",
              regionCode: "GB-ENG",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094987,
              userFavourite: false,
              name: "League Two",
              regionCode: "GB-ENG",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094984,
              userFavourite: false,
              name: "FA Cup",
              regionCode: "GB-ENG",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095137,
              userFavourite: false,
              name: "EFL Trophy",
              regionCode: "GB-ENG",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000054642,
              userFavourite: false,
              name: "Isthmian League Premier Division",
              regionCode: "GB-ENG",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095485,
              userFavourite: false,
              name: "National League",
              regionCode: "GB-ENG",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000050126,
              userFavourite: false,
              name: "National League North",
              regionCode: "GB-ENG",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000385084,
              userFavourite: false,
              name: "National League South",
              regionCode: "GB-ENG",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000054030,
              userFavourite: false,
              name: "Northern League Premier Division",
              regionCode: "GB-ENG",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000052846,
              userFavourite: false,
              name: "Southern League Premier Division",
              regionCode: "GB-ENG",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461745,
          popular: false,
          name: "Italy",
          groups: [
            {
              id: 1000095001,
              userFavourite: true,
              name: "Serie A",
              regionCode: "IT",
              __typename: "EventGroup",
              popular: true,
            },
            {
              id: 1000095002,
              userFavourite: false,
              name: "Serie B",
              regionCode: "IT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094998,
              userFavourite: false,
              name: "TIM Cup",
              regionCode: "IT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000056483,
              userFavourite: false,
              name: "Serie A (W)",
              regionCode: "IT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000079607,
              userFavourite: false,
              name: "Serie C Girone A",
              regionCode: "IT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000079608,
              userFavourite: false,
              name: "Serie C Girone B",
              regionCode: "IT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000079609,
              userFavourite: false,
              name: "Serie C Girone C",
              regionCode: "IT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000056085,
              userFavourite: false,
              name: "Serie D",
              regionCode: "IT",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461813,
          popular: false,
          name: "Spain",
          groups: [
            {
              id: 1000095049,
              userFavourite: false,
              name: "La Liga",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094708,
              userFavourite: false,
              name: "La Liga 2",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094816,
              userFavourite: false,
              name: "Segunda B-1",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094817,
              userFavourite: false,
              name: "Segunda B-2",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094818,
              userFavourite: false,
              name: "Segunda B-3",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095050,
              userFavourite: false,
              name: "Copa del Rey",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000074384,
              userFavourite: false,
              name: "Segunda División Feminina (W)",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000051626,
              userFavourite: false,
              name: "Superliga Femenina (W)",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000103573,
              userFavourite: false,
              name: "Tercera División 1",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000103583,
              userFavourite: false,
              name: "Tercera División 11",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000103584,
              userFavourite: false,
              name: "Tercera División 12",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000103585,
              userFavourite: false,
              name: "Tercera División 13",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000103586,
              userFavourite: false,
              name: "Tercera División 14",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000103587,
              userFavourite: false,
              name: "Tercera División 15",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000103588,
              userFavourite: false,
              name: "Tercera División 16",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000103590,
              userFavourite: false,
              name: "Tercera División 18",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000103575,
              userFavourite: false,
              name: "Tercera División 3",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000103576,
              userFavourite: false,
              name: "Tercera División 4",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000103578,
              userFavourite: false,
              name: "Tercera División 6",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461728,
          popular: false,
          name: "Germany",
          groups: [
            {
              id: 1000094994,
              userFavourite: false,
              name: "Bundesliga",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094993,
              userFavourite: false,
              name: "2. Bundesliga",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000355562,
              userFavourite: false,
              name: "3. Liga",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094995,
              userFavourite: false,
              name: "DFB Pokal",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000435401,
              userFavourite: false,
              name: "Bundesliga (W)",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000062770,
              userFavourite: false,
              name: "Oberliga Baden-Württemberg",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000062774,
              userFavourite: false,
              name: "Oberliga Bayern Nord",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000062775,
              userFavourite: false,
              name: "Oberliga Bayern Süd",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000065519,
              userFavourite: false,
              name: "Oberliga Bremen",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000062771,
              userFavourite: false,
              name: "Oberliga Hamburg",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000064573,
              userFavourite: false,
              name: "Oberliga Hessen",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000062736,
              userFavourite: false,
              name: "Oberliga Rheinland-Pfalz/Saar",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000059631,
              userFavourite: false,
              name: "Regionalliga Bayern",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094593,
              userFavourite: false,
              name: "Regionalliga Nord",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000059629,
              userFavourite: false,
              name: "Regionalliga Nordost",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000059630,
              userFavourite: false,
              name: "Regionalliga Südwest",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000355768,
              userFavourite: false,
              name: "Regionalliga West",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461727,
          popular: false,
          name: "France",
          groups: [
            {
              id: 1000094991,
              userFavourite: false,
              name: "Ligue 1",
              regionCode: "FR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094568,
              userFavourite: false,
              name: "Ligue 2",
              regionCode: "FR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094990,
              userFavourite: false,
              name: "Coupe de France",
              regionCode: "FR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094992,
              userFavourite: false,
              name: "Coupe de la Ligue",
              regionCode: "FR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000086887,
              userFavourite: false,
              name: "Championnat National U19",
              regionCode: "FR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000190533,
              userFavourite: false,
              name: "Division 1 (W)",
              regionCode: "FR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000181002,
              userFavourite: false,
              name: "National 2 Group D",
              regionCode: "FR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000056080,
              userFavourite: false,
              name: "National 3",
              regionCode: "FR",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000084547,
          popular: false,
          name: "AFC Champions League",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000123032,
          popular: false,
          name: "African Nations Cup",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 2000066140,
          popular: false,
          name: "African Nations Cup Qualification",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000461754,
          popular: false,
          name: "Argentina",
          groups: [
            {
              id: 2000050561,
              userFavourite: false,
              name: "Primera Division",
              regionCode: "AR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000442572,
              userFavourite: false,
              name: "Primera B Nacional",
              regionCode: "AR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000056748,
              userFavourite: false,
              name: "Copa Argentina",
              regionCode: "AR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000052332,
              userFavourite: false,
              name: "Primera B Metropolitana",
              regionCode: "AR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000073003,
              userFavourite: false,
              name: "Primera C",
              regionCode: "AR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000113832,
              userFavourite: false,
              name: "Primera D Metropolitana",
              regionCode: "AR",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461755,
          popular: false,
          name: "Australia",
          groups: [
            {
              id: 1000182606,
              userFavourite: false,
              name: "A-League",
              regionCode: "AU",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000064679,
              userFavourite: false,
              name: "NPL NSW",
              regionCode: "AU",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000066177,
              userFavourite: false,
              name: "State Leagues (W)",
              regionCode: "AU",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461751,
          popular: false,
          name: "Austria",
          groups: [
            {
              id: 1000345237,
              userFavourite: false,
              name: "Bundesliga",
              regionCode: "AT",
              __typename: "EventGroup",
              popular: true,
            },
            {
              id: 2000055929,
              userFavourite: false,
              name: "Regional League Central",
              regionCode: "AT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000055928,
              userFavourite: false,
              name: "Regional League East",
              regionCode: "AT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000055930,
              userFavourite: false,
              name: "Regional League West",
              regionCode: "AT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094692,
              userFavourite: false,
              name: "ÖFB Cup",
              regionCode: "AT",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461740,
          popular: false,
          name: "Belgium",
          groups: [
            {
              id: 1000094965,
              userFavourite: false,
              name: "Jupiler Pro League",
              regionCode: "BE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094961,
              userFavourite: false,
              name: "Beker van Belgie",
              regionCode: "BE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000358593,
              userFavourite: false,
              name: "Proximus League",
              regionCode: "BE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094954,
              userFavourite: false,
              name: "Eerste Klasse Amateurs",
              regionCode: "BE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000105053,
              userFavourite: false,
              name: "First Division (W)",
              regionCode: "BE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000096513,
              userFavourite: false,
              name: "Tweede Klasse Amateurs ACFF",
              regionCode: "BE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000096514,
              userFavourite: false,
              name: "Tweede Klasse Amateurs VFV A",
              regionCode: "BE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000096515,
              userFavourite: false,
              name: "Tweede Klasse Amateurs VFV B",
              regionCode: "BE",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000051030,
          popular: false,
          name: "Bolivia",
          groups: [
            {
              id: 2000051031,
              userFavourite: false,
              name: "Liga Profesional",
              regionCode: "BO",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461741,
          popular: false,
          name: "Brazil",
          groups: [
            {
              id: 1000094569,
              userFavourite: false,
              name: "Série A",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000068940,
              userFavourite: false,
              name: "Campeonato Brasileiro (W)",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000055450,
              userFavourite: false,
              name: "Carioca U20",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000063632,
              userFavourite: false,
              name: "Copa do Nordeste",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000052788,
              userFavourite: false,
              name: "Goiano",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095036,
              userFavourite: false,
              name: "Mineiro",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000103873,
              userFavourite: false,
              name: "Mineiro 2",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095037,
              userFavourite: false,
              name: "Paranaense",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094970,
              userFavourite: false,
              name: "Paulista A1",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000086229,
              userFavourite: false,
              name: "Paulista A2",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000064212,
              userFavourite: false,
              name: "Paulista A3",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461757,
          popular: false,
          name: "Bulgaria",
          groups: [
            {
              id: 1000285388,
              userFavourite: false,
              name: "Cup",
              regionCode: "PS",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000383831,
              userFavourite: false,
              name: "PFL 1",
              regionCode: "BG",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000115276,
              userFavourite: true,
              name: "PFL 1 Play-offs",
              regionCode: "BG",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461738,
          popular: false,
          name: "Chile",
          groups: [
            {
              id: 2000050080,
              userFavourite: false,
              name: "Copa Chile",
              regionCode: "CL",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095155,
              userFavourite: false,
              name: "Primera",
              regionCode: "CL",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000066921,
              userFavourite: false,
              name: "Super Cup",
              regionCode: "CL",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461784,
          popular: false,
          name: "China",
          groups: [
            {
              id: 2000055591,
              userFavourite: false,
              name: "League Two",
              regionCode: "CN",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000338400,
              userFavourite: false,
              name: "Super League",
              regionCode: "CN",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000093393,
          popular: false,
          name: "Club Friendly Matches",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000461759,
          popular: false,
          name: "Colombia",
          groups: [
            {
              id: 1000449742,
              userFavourite: true,
              name: "Liga Águila",
              regionCode: "CO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000057058,
              userFavourite: false,
              name: "Primera B",
              regionCode: "CO",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000114415,
          popular: false,
          name: "CONCACAF Champions League",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000093398,
          popular: false,
          name: "Copa America",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000093399,
          popular: false,
          name: "Copa Libertadores",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 2000050275,
          popular: false,
          name: "Costa Rica",
          groups: [
            {
              id: 2000050276,
              userFavourite: false,
              name: "Primera Division",
              regionCode: "CR",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461739,
          popular: false,
          name: "Croatia",
          groups: [
            {
              id: 1000095736,
              userFavourite: false,
              name: "1. HNL League",
              regionCode: "HR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000052327,
              userFavourite: false,
              name: "2. HNL League",
              regionCode: "HR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000085049,
              userFavourite: false,
              name: "3. HNL League",
              regionCode: "HR",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461735,
          popular: false,
          name: "Czech Republic",
          groups: [
            {
              id: 1000094975,
              userFavourite: false,
              name: "First League",
              regionCode: "CZ",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000085689,
              userFavourite: false,
              name: "4. Liga",
              regionCode: "CZ",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000051610,
              userFavourite: false,
              name: "MSFL",
              regionCode: "CZ",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000085810,
              userFavourite: false,
              name: "Regional Leagues",
              regionCode: "CZ",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000051159,
              userFavourite: false,
              name: "ČFL",
              regionCode: "CZ",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461736,
          popular: false,
          name: "Denmark",
          groups: [
            {
              id: 1000094978,
              userFavourite: false,
              name: "Superligaen",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000443738,
              userFavourite: false,
              name: "Sydbank Pokalen",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094976,
              userFavourite: false,
              name: "1st Division",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094921,
              userFavourite: false,
              name: "DS Pulje 1",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094922,
              userFavourite: false,
              name: "DS Pulje 2",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000393906,
              userFavourite: false,
              name: "DS Pulje 3",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000088288,
              userFavourite: false,
              name: "2nd Division Pulje 1",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000088289,
              userFavourite: false,
              name: "2nd Division Pulje 2",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000095377,
              userFavourite: false,
              name: "DS Pulje 4",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000095271,
          popular: false,
          name: "Euro 2020",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 2000117846,
          popular: false,
          name: "Euro 2020 Qualification",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 2000051195,
          popular: false,
          name: "Europa League",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000151772,
          popular: false,
          name: "FIFA World Cup U20",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000461822,
          popular: false,
          name: "Finland",
          groups: [
            {
              id: 1000094989,
              userFavourite: true,
              name: "Veikkausliiga",
              regionCode: "FI",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461752,
          popular: false,
          name: "Greece",
          groups: [
            {
              id: 1000094996,
              userFavourite: false,
              name: "Super League",
              regionCode: "GR",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000050538,
          popular: false,
          name: "Guatemala",
          groups: [
            {
              id: 2000084267,
              userFavourite: false,
              name: "Primera Division de Ascenso",
              regionCode: "GT",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461748,
          popular: false,
          name: "Hungary",
          groups: [
            {
              id: 1000094997,
              userFavourite: false,
              name: "NB 1",
              regionCode: "HU",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000053582,
              userFavourite: false,
              name: "NB 1 (W)",
              regionCode: "HU",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000080688,
              userFavourite: false,
              name: "NB 3",
              regionCode: "HU",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461749,
          popular: false,
          name: "Iceland",
          groups: [
            {
              id: 2000084987,
              userFavourite: false,
              name: "League Cup B",
              regionCode: "IS",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000093570,
          popular: false,
          name: "International Friendly Matches",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 2000057339,
          popular: false,
          name: "International Tournaments",
          groups: [
            {
              id: 2000117768,
              userFavourite: false,
              name: "CONCACAF Nations League",
              regionCode: null,
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461750,
          popular: false,
          name: "Ireland",
          groups: [
            {
              id: 1000157155,
              userFavourite: false,
              name: "1st Division",
              regionCode: "IE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000082492,
              userFavourite: false,
              name: "Elite League U19",
              regionCode: "IE",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461820,
          popular: false,
          name: "Israel",
          groups: [
            {
              id: 2000056903,
              userFavourite: false,
              name: "Liga Bet",
              regionCode: "IL",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461746,
          popular: false,
          name: "Japan",
          groups: [
            {
              id: 1000152623,
              userFavourite: false,
              name: "J2-League",
              regionCode: "JP",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000050579,
          popular: false,
          name: "Jordan",
          groups: [
            {
              id: 2000053443,
              userFavourite: false,
              name: "FA Cup",
              regionCode: "JO",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000073085,
          popular: false,
          name: "Kenya",
          groups: [
            {
              id: 2000073086,
              userFavourite: false,
              name: "Premier League",
              regionCode: "KE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000114293,
              userFavourite: false,
              name: "Super League",
              regionCode: "KE",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461742,
          popular: false,
          name: "Mexico",
          groups: [
            {
              id: 1000094112,
              userFavourite: false,
              name: "Liga MX",
              regionCode: "MX",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000109034,
              userFavourite: false,
              name: "Liga MX Femenil (W)",
              regionCode: "MX",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000092649,
              userFavourite: false,
              name: "Liga Premier",
              regionCode: "MX",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461753,
          popular: false,
          name: "Netherlands",
          groups: [
            {
              id: 1000094980,
              userFavourite: false,
              name: "Eredivisie",
              regionCode: "NL",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095127,
              userFavourite: false,
              name: "Eerste Divisie",
              regionCode: "NL",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094979,
              userFavourite: false,
              name: "KNVB Beker",
              regionCode: "NL",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000095410,
              userFavourite: false,
              name: "Tweede Divisie",
              regionCode: "NL",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461743,
          popular: false,
          name: "New Zealand",
          groups: [
            {
              id: 1000281673,
              userFavourite: false,
              name: "ASB Premiership",
              regionCode: "NZ",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000258090,
          popular: false,
          name: "Northern Ireland",
          groups: [
            {
              id: 1000258091,
              userFavourite: false,
              name: "NIFL Premiership",
              regionCode: "GB",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461744,
          popular: false,
          name: "Norway",
          groups: [
            {
              id: 1000095010,
              userFavourite: false,
              name: "Eliteserien",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095008,
              userFavourite: false,
              name: "NM Cupen",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000074108,
              userFavourite: false,
              name: "4 Div Agder 1",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000074111,
              userFavourite: false,
              name: "4 Div Akershus 1",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095003,
              userFavourite: false,
              name: "OBOS-ligaen",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000100352,
              userFavourite: false,
              name: "Postnordligaen avd. 1",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000100353,
              userFavourite: false,
              name: "Postnordligaen avd. 2",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000100354,
              userFavourite: false,
              name: "Regionsligaen avd. 1",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000100373,
              userFavourite: false,
              name: "Regionsligaen avd. 3",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000100374,
              userFavourite: false,
              name: "Regionsligaen avd. 4",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000100375,
              userFavourite: false,
              name: "Regionsligaen avd. 5",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000100376,
              userFavourite: false,
              name: "Regionsligaen avd. 6",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000176403,
              userFavourite: false,
              name: "Toppserien (W)",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000055545,
          popular: false,
          name: "Panama",
          groups: [
            {
              id: 2000055546,
              userFavourite: false,
              name: "LPF",
              regionCode: "PA",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000050114,
          popular: false,
          name: "Paraguay",
          groups: [
            {
              id: 2000050115,
              userFavourite: false,
              name: "Primera Division",
              regionCode: "PY",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461802,
          popular: false,
          name: "Peru",
          groups: [
            {
              id: 1000237680,
              userFavourite: false,
              name: "Primera Division",
              regionCode: "PE",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461811,
          popular: false,
          name: "Poland",
          groups: [
            {
              id: 1000385219,
              userFavourite: true,
              name: "Ekstraklasa",
              regionCode: "PL",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000348167,
              userFavourite: false,
              name: "I Liga",
              regionCode: "PL",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000077607,
              userFavourite: false,
              name: "II Liga",
              regionCode: "PL",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000057911,
              userFavourite: false,
              name: "III Liga",
              regionCode: "PL",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095016,
              userFavourite: false,
              name: "Puchar Polski",
              regionCode: "PL",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461812,
          popular: false,
          name: "Portugal",
          groups: [
            {
              id: 1000095042,
              userFavourite: true,
              name: "Primeira Liga",
              regionCode: "PT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000116777,
              userFavourite: false,
              name: "Liga Revelacao U23",
              regionCode: "PT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000076626,
              userFavourite: false,
              name: "Taça de Portugal (W)",
              regionCode: "PT",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461808,
          popular: false,
          name: "Romania",
          groups: [
            {
              id: 1000095499,
              userFavourite: false,
              name: "Liga I",
              regionCode: "RO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000095935,
              userFavourite: false,
              name: "Liga II",
              regionCode: "RO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095805,
              userFavourite: false,
              name: "Cupa Romaniei",
              regionCode: "OM",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461809,
          popular: false,
          name: "Russia",
          groups: [
            {
              id: 1000095590,
              userFavourite: true,
              name: "Premier League",
              regionCode: "RU",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461819,
          popular: false,
          name: "Saudi Arabia",
          groups: [
            {
              id: 1000250591,
              userFavourite: false,
              name: "Professional League",
              regionCode: "SA",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461810,
          popular: false,
          name: "Scotland",
          groups: [
            {
              id: 1000095047,
              userFavourite: true,
              name: "Scottish Premiership",
              regionCode: "GB-SCT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095045,
              userFavourite: false,
              name: "Championship",
              regionCode: "GB-SCT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000280417,
              userFavourite: false,
              name: "League One",
              regionCode: "GB-SCT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000280418,
              userFavourite: false,
              name: "League Two",
              regionCode: "GB-SCT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094254,
              userFavourite: false,
              name: "Scottish Cup",
              regionCode: "GB-SCT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000193401,
              userFavourite: false,
              name: "Challenge Cup",
              regionCode: "GB-SCT",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000050598,
          popular: false,
          name: "Serbia",
          groups: [
            {
              id: 2000055499,
              userFavourite: false,
              name: "Prva Liga",
              regionCode: "RS",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000097633,
              userFavourite: false,
              name: "Srpska Liga",
              regionCode: "RS",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461798,
          popular: false,
          name: "Slovenia",
          groups: [
            {
              id: 2000074146,
              userFavourite: false,
              name: "SNL 2",
              regionCode: "SI",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000076187,
              userFavourite: false,
              name: "SNL 3",
              regionCode: "SI",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461803,
          popular: false,
          name: "South Africa",
          groups: [
            {
              id: 2000051878,
              userFavourite: true,
              name: "1st Division",
              regionCode: "ZA",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000050659,
              userFavourite: false,
              name: "Nedbank Cup",
              regionCode: "ZA",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000250636,
              userFavourite: false,
              name: "SA Premier Soccer League",
              regionCode: "ZA",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461814,
          popular: false,
          name: "Sweden",
          groups: [
            {
              id: 1000095057,
              userFavourite: true,
              name: "Allsvenskan",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: true,
            },
            {
              id: 1000095052,
              userFavourite: false,
              name: "Superettan",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094744,
              userFavourite: false,
              name: "Division 1 N",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094745,
              userFavourite: false,
              name: "Division 1 S",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095059,
              userFavourite: false,
              name: "Svenska Cupen",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000176396,
              userFavourite: false,
              name: "Damallsvenskan (W)",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095053,
              userFavourite: false,
              name: "Division 2 N",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094184,
              userFavourite: false,
              name: "Division 2 NS",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000266381,
              userFavourite: false,
              name: "Division 2 SS",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461815,
          popular: false,
          name: "Switzerland",
          groups: [
            {
              id: 1000095020,
              userFavourite: false,
              name: "Super League",
              regionCode: "CH",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461821,
          popular: false,
          name: "Turkey",
          groups: [
            {
              id: 1000095062,
              userFavourite: true,
              name: "Süper Lig",
              regionCode: "TR",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000151680,
          popular: false,
          name: "UEFA Championship U21",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 2000113672,
          popular: false,
          name: "UEFA Nations League",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 2000065880,
          popular: false,
          name: "UEFA Qualification U21",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000461804,
          popular: false,
          name: "Ukraine",
          groups: [
            {
              id: 1000171537,
              userFavourite: false,
              name: "Premier League",
              regionCode: "UA",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000051471,
              userFavourite: false,
              name: "Persha Liga",
              regionCode: "UA",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461805,
          popular: false,
          name: "United Arab Emirates",
          groups: [
            {
              id: 2000050277,
              userFavourite: false,
              name: "Division 1",
              regionCode: "AE",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461760,
          popular: false,
          name: "Uruguay",
          groups: [
            {
              id: 1000450453,
              userFavourite: true,
              name: "Primera Division",
              regionCode: "UY",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461816,
          popular: false,
          name: "USA",
          groups: [
            {
              id: 1000095063,
              userFavourite: true,
              name: "MLS",
              regionCode: "US",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000065915,
              userFavourite: false,
              name: "NPSL",
              regionCode: "US",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000055612,
              userFavourite: false,
              name: "USL",
              regionCode: "US",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000050117,
          popular: false,
          name: "Venezuela",
          groups: [
            {
              id: 2000050118,
              userFavourite: false,
              name: "Primera Division",
              regionCode: "VE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000083468,
              userFavourite: false,
              name: "Segunda Division",
              regionCode: "VE",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000050124,
          popular: false,
          name: "Wales",
          groups: [
            {
              id: 2000050125,
              userFavourite: true,
              name: "Premier League",
              regionCode: "GB-WLS",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000101172,
          popular: false,
          name: "World Cup (W)",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 2000116272,
          popular: false,
          name: "World Cup 2022",
          groups: [],
        },
      ],
    },
  },
};
