export default {
  data: {
    internationalGroupName: "International",
    group: {
      __typename: "EventGroup",
      name: "Football",
      groups: [
        {
          __typename: "EventGroup",
          id: 1000093381,
          popular: true,
          name: "Champions League",
          regionCode: "EU",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000461733,
          popular: false,
          name: "England",
          regionCode: "GB-ENG",
          groups: [
            {
              id: 1000094985,
              userFavourite: true,
              name: "Premier League",
              regionCode: "GB-ENG",
              __typename: "EventGroup",
              popular: true,
            },
            {
              id: 1000094981,
              userFavourite: true,
              name: "The Championship",
              regionCode: "GB-ENG",
              __typename: "EventGroup",
              popular: true,
            },
            {
              id: 1000094984,
              userFavourite: false,
              name: "FA Cup",
              regionCode: "GB-ENG",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095137,
              userFavourite: false,
              name: "EFL Trophy",
              regionCode: "GB-ENG",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461745,
          popular: false,
          name: "Italy",
          regionCode: "IT",
          groups: [
            {
              id: 1000095001,
              userFavourite: true,
              name: "Serie A",
              regionCode: "IT",
              __typename: "EventGroup",
              popular: true,
            },
            {
              id: 1000095002,
              userFavourite: false,
              name: "Serie B",
              regionCode: "IT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094998,
              userFavourite: false,
              name: "TIM Cup",
              regionCode: "IT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000079607,
              userFavourite: false,
              name: "Serie C Girone A",
              regionCode: "IT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000079608,
              userFavourite: false,
              name: "Serie C Girone B",
              regionCode: "IT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000079609,
              userFavourite: false,
              name: "Serie C Girone C",
              regionCode: "IT",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461813,
          popular: false,
          name: "Spain",
          regionCode: "ES",
          groups: [
            {
              id: 1000095049,
              userFavourite: false,
              name: "La Liga",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094708,
              userFavourite: false,
              name: "La Liga 2",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095050,
              userFavourite: false,
              name: "Copa del Rey",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000074384,
              userFavourite: false,
              name: "Segunda División Feminina (W)",
              regionCode: "ES",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461728,
          popular: false,
          name: "Germany",
          regionCode: "DE",
          groups: [
            {
              id: 1000094994,
              userFavourite: false,
              name: "Bundesliga",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094993,
              userFavourite: false,
              name: "2. Bundesliga",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000355562,
              userFavourite: false,
              name: "3. Liga",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094995,
              userFavourite: false,
              name: "DFB Pokal",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000435401,
              userFavourite: false,
              name: "Bundesliga (W)",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094593,
              userFavourite: false,
              name: "Regionalliga Nord",
              regionCode: "DE",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461727,
          popular: false,
          name: "France",
          regionCode: "FR",
          groups: [
            {
              id: 1000094991,
              userFavourite: false,
              name: "Ligue 1",
              regionCode: "FR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094568,
              userFavourite: false,
              name: "Ligue 2",
              regionCode: "FR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094990,
              userFavourite: false,
              name: "Coupe de France",
              regionCode: "FR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094992,
              userFavourite: false,
              name: "Coupe de la Ligue",
              regionCode: "FR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000086887,
              userFavourite: false,
              name: "Championnat National U19",
              regionCode: "FR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000056080,
              userFavourite: false,
              name: "National 3",
              regionCode: "FR",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000084547,
          popular: false,
          name: "AFC Champions League",
          regionCode: null,
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000123032,
          popular: false,
          name: "African Nations Cup",
          regionCode: null,
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 2000066140,
          popular: false,
          name: "African Nations Cup Qualification",
          regionCode: null,
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000461754,
          popular: false,
          name: "Argentina",
          regionCode: "AR",
          groups: [
            {
              id: 2000050561,
              userFavourite: false,
              name: "Primera Division",
              regionCode: "AR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000442572,
              userFavourite: false,
              name: "Primera B Nacional",
              regionCode: "AR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000056748,
              userFavourite: false,
              name: "Copa Argentina",
              regionCode: "AR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000052332,
              userFavourite: false,
              name: "Primera B Metropolitana",
              regionCode: "AR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000073003,
              userFavourite: false,
              name: "Primera C",
              regionCode: "AR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000113832,
              userFavourite: false,
              name: "Primera D Metropolitana",
              regionCode: "AR",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461755,
          popular: false,
          name: "Australia",
          regionCode: "AU",
          groups: [
            {
              id: 1000182606,
              userFavourite: false,
              name: "A-League",
              regionCode: "AU",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000064679,
              userFavourite: false,
              name: "NPL NSW",
              regionCode: "AU",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000066177,
              userFavourite: false,
              name: "State Leagues (W)",
              regionCode: "AU",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461751,
          popular: false,
          name: "Austria",
          regionCode: "AT",
          groups: [
            {
              id: 1000345237,
              userFavourite: false,
              name: "Bundesliga",
              regionCode: "AT",
              __typename: "EventGroup",
              popular: true,
            },
            {
              id: 2000055930,
              userFavourite: false,
              name: "Regional League West",
              regionCode: "AT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094692,
              userFavourite: false,
              name: "ÖFB Cup",
              regionCode: "AT",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461740,
          popular: false,
          name: "Belgium",
          regionCode: "BE",
          groups: [
            {
              id: 1000094965,
              userFavourite: false,
              name: "Jupiler Pro League",
              regionCode: "BE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094961,
              userFavourite: false,
              name: "Beker van Belgie",
              regionCode: "BE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000358593,
              userFavourite: false,
              name: "Proximus League",
              regionCode: "BE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094954,
              userFavourite: false,
              name: "Eerste Klasse Amateurs",
              regionCode: "BE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000096513,
              userFavourite: false,
              name: "Tweede Klasse Amateurs ACFF",
              regionCode: "BE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000096514,
              userFavourite: false,
              name: "Tweede Klasse Amateurs VFV A",
              regionCode: "BE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000096515,
              userFavourite: false,
              name: "Tweede Klasse Amateurs VFV B",
              regionCode: "BE",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000051030,
          popular: false,
          name: "Bolivia",
          regionCode: "BO",
          groups: [
            {
              id: 2000051031,
              userFavourite: false,
              name: "Liga Profesional",
              regionCode: "BO",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461741,
          popular: false,
          name: "Brazil",
          regionCode: "BR",
          groups: [
            {
              id: 1000094569,
              userFavourite: false,
              name: "Série A",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000106234,
              userFavourite: false,
              name: "Acriano",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000068940,
              userFavourite: false,
              name: "Campeonato Brasileiro (W)",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094971,
              userFavourite: false,
              name: "Carioca",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000055450,
              userFavourite: false,
              name: "Carioca U20",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000063632,
              userFavourite: false,
              name: "Copa do Nordeste",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095035,
              userFavourite: false,
              name: "Gaúcho",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000066021,
              userFavourite: false,
              name: "Gaúcho U20",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000052788,
              userFavourite: false,
              name: "Goiano",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095036,
              userFavourite: false,
              name: "Mineiro",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095037,
              userFavourite: false,
              name: "Paranaense",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094970,
              userFavourite: false,
              name: "Paulista A1",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000086229,
              userFavourite: false,
              name: "Paulista A2",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000064212,
              userFavourite: false,
              name: "Paulista A3",
              regionCode: "BR",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461757,
          popular: false,
          name: "Bulgaria",
          regionCode: "BG",
          groups: [
            {
              id: 1000285388,
              userFavourite: false,
              name: "Cup",
              regionCode: "PS",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000383831,
              userFavourite: false,
              name: "PFL 1",
              regionCode: "BG",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000115276,
              userFavourite: false,
              name: "PFL 1 Play-offs",
              regionCode: "BG",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461738,
          popular: false,
          name: "Chile",
          regionCode: "CL",
          groups: [
            {
              id: 2000050080,
              userFavourite: false,
              name: "Copa Chile",
              regionCode: "CL",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095155,
              userFavourite: false,
              name: "Primera",
              regionCode: "CL",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000066921,
              userFavourite: false,
              name: "Super Cup",
              regionCode: "CL",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461784,
          popular: false,
          name: "China",
          regionCode: "CN",
          groups: [
            {
              id: 2000055591,
              userFavourite: false,
              name: "League Two",
              regionCode: "CN",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000338400,
              userFavourite: false,
              name: "Super League",
              regionCode: "CN",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000093393,
          popular: false,
          name: "Club Friendly Matches",
          regionCode: null,
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000461759,
          popular: false,
          name: "Colombia",
          regionCode: "CO",
          groups: [
            {
              id: 1000449742,
              userFavourite: false,
              name: "Liga Águila",
              regionCode: "CO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000057058,
              userFavourite: false,
              name: "Primera B",
              regionCode: "CO",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000114415,
          popular: false,
          name: "CONCACAF Champions League",
          regionCode: null,
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000093398,
          popular: false,
          name: "Copa America",
          regionCode: null,
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000093399,
          popular: false,
          name: "Copa Libertadores",
          regionCode: null,
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 2000050275,
          popular: false,
          name: "Costa Rica",
          regionCode: "CR",
          groups: [
            {
              id: 2000057464,
              userFavourite: false,
              name: "Liga de Ascenso",
              regionCode: "CR",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000050276,
              userFavourite: false,
              name: "Primera Division",
              regionCode: "CR",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461739,
          popular: false,
          name: "Croatia",
          regionCode: "HR",
          groups: [
            {
              id: 1000095736,
              userFavourite: false,
              name: "1. HNL League",
              regionCode: "HR",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461735,
          popular: false,
          name: "Czech Republic",
          regionCode: "CZ",
          groups: [
            {
              id: 1000094975,
              userFavourite: false,
              name: "First League",
              regionCode: "CZ",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461736,
          popular: false,
          name: "Denmark",
          regionCode: "DK",
          groups: [
            {
              id: 1000094978,
              userFavourite: false,
              name: "Superligaen",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000443738,
              userFavourite: false,
              name: "Sydbank Pokalen",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094976,
              userFavourite: false,
              name: "1st Division",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094921,
              userFavourite: false,
              name: "DS Pulje 1",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094922,
              userFavourite: false,
              name: "DS Pulje 2",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000088288,
              userFavourite: false,
              name: "2nd Division Pulje 1",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000088289,
              userFavourite: false,
              name: "2nd Division Pulje 2",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000095377,
              userFavourite: false,
              name: "DS Pulje 4",
              regionCode: "DK",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000095271,
          popular: false,
          name: "Euro 2020",
          regionCode: "EU",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 2000117846,
          popular: false,
          name: "Euro 2020 Qualification",
          regionCode: "EU",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 2000051195,
          popular: false,
          name: "Europa League",
          regionCode: "EU",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000151772,
          popular: false,
          name: "FIFA World Cup U20",
          regionCode: null,
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000461822,
          popular: false,
          name: "Finland",
          regionCode: "FI",
          groups: [
            {
              id: 1000094989,
              userFavourite: false,
              name: "Veikkausliiga",
              regionCode: "FI",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461752,
          popular: false,
          name: "Greece",
          regionCode: "GR",
          groups: [
            {
              id: 1000094996,
              userFavourite: false,
              name: "Super League",
              regionCode: "GR",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000050538,
          popular: false,
          name: "Guatemala",
          regionCode: "GT",
          groups: [
            {
              id: 2000084267,
              userFavourite: false,
              name: "Primera Division de Ascenso",
              regionCode: "GT",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461748,
          popular: false,
          name: "Hungary",
          regionCode: "HU",
          groups: [
            {
              id: 1000094997,
              userFavourite: false,
              name: "NB 1",
              regionCode: "HU",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000093570,
          popular: false,
          name: "International Friendly Matches",
          regionCode: null,
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 2000057339,
          popular: false,
          name: "International Tournaments",
          regionCode: null,
          groups: [
            {
              id: 2000117768,
              userFavourite: false,
              name: "CONCACAF Nations League",
              regionCode: null,
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461746,
          popular: false,
          name: "Japan",
          regionCode: "JP",
          groups: [
            {
              id: 1000152623,
              userFavourite: false,
              name: "J2-League",
              regionCode: "JP",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000073085,
          popular: false,
          name: "Kenya",
          regionCode: "KE",
          groups: [
            {
              id: 2000114293,
              userFavourite: false,
              name: "Super League",
              regionCode: "KE",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461742,
          popular: false,
          name: "Mexico",
          regionCode: "MX",
          groups: [
            {
              id: 1000094112,
              userFavourite: false,
              name: "Liga MX",
              regionCode: "MX",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000092649,
              userFavourite: false,
              name: "Liga Premier",
              regionCode: "MX",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461753,
          popular: false,
          name: "Netherlands",
          regionCode: "NL",
          groups: [
            {
              id: 1000094980,
              userFavourite: false,
              name: "Eredivisie",
              regionCode: "NL",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095127,
              userFavourite: false,
              name: "Eerste Divisie",
              regionCode: "NL",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094979,
              userFavourite: false,
              name: "KNVB Beker",
              regionCode: "NL",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000095410,
              userFavourite: false,
              name: "Tweede Divisie",
              regionCode: "NL",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461743,
          popular: false,
          name: "New Zealand",
          regionCode: "NZ",
          groups: [
            {
              id: 1000281673,
              userFavourite: false,
              name: "ASB Premiership",
              regionCode: "NZ",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000258090,
          popular: false,
          name: "Northern Ireland",
          regionCode: "GB",
          groups: [
            {
              id: 1000258091,
              userFavourite: false,
              name: "NIFL Premiership",
              regionCode: "GB",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461744,
          popular: false,
          name: "Norway",
          regionCode: "NO",
          groups: [
            {
              id: 1000095010,
              userFavourite: false,
              name: "Eliteserien",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000074108,
              userFavourite: false,
              name: "4 Div Agder 1",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095003,
              userFavourite: false,
              name: "OBOS-ligaen",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000100352,
              userFavourite: false,
              name: "Postnordligaen avd. 1",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000100353,
              userFavourite: false,
              name: "Postnordligaen avd. 2",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000100354,
              userFavourite: false,
              name: "Regionsligaen avd. 1",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000100373,
              userFavourite: false,
              name: "Regionsligaen avd. 3",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000100374,
              userFavourite: false,
              name: "Regionsligaen avd. 4",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000100375,
              userFavourite: false,
              name: "Regionsligaen avd. 5",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000100376,
              userFavourite: false,
              name: "Regionsligaen avd. 6",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000176403,
              userFavourite: false,
              name: "Toppserien (W)",
              regionCode: "NO",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000055545,
          popular: false,
          name: "Panama",
          regionCode: "PA",
          groups: [
            {
              id: 2000055546,
              userFavourite: false,
              name: "LPF",
              regionCode: "PA",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000062635,
              userFavourite: false,
              name: "Reserve League",
              regionCode: "PA",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000050114,
          popular: false,
          name: "Paraguay",
          regionCode: "PY",
          groups: [
            {
              id: 2000050115,
              userFavourite: false,
              name: "Primera Division",
              regionCode: "PY",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461802,
          popular: false,
          name: "Peru",
          regionCode: "PE",
          groups: [
            {
              id: 1000237680,
              userFavourite: false,
              name: "Primera Division",
              regionCode: "PE",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461811,
          popular: false,
          name: "Poland",
          regionCode: "PL",
          groups: [
            {
              id: 1000385219,
              userFavourite: false,
              name: "Ekstraklasa",
              regionCode: "PL",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000348167,
              userFavourite: false,
              name: "I Liga",
              regionCode: "PL",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095016,
              userFavourite: false,
              name: "Puchar Polski",
              regionCode: "PL",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461812,
          popular: false,
          name: "Portugal",
          regionCode: "PT",
          groups: [
            {
              id: 1000095042,
              userFavourite: false,
              name: "Primeira Liga",
              regionCode: "PT",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461808,
          popular: false,
          name: "Romania",
          regionCode: "RO",
          groups: [
            {
              id: 1000095499,
              userFavourite: false,
              name: "Liga I",
              regionCode: "RO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000095935,
              userFavourite: false,
              name: "Liga II",
              regionCode: "RO",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095805,
              userFavourite: false,
              name: "Cupa Romaniei",
              regionCode: "OM",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461809,
          popular: false,
          name: "Russia",
          regionCode: "RU",
          groups: [
            {
              id: 1000095590,
              userFavourite: false,
              name: "Premier League",
              regionCode: "RU",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461810,
          popular: false,
          name: "Scotland",
          regionCode: "GB-SCT",
          groups: [
            {
              id: 1000095047,
              userFavourite: true,
              name: "Scottish Premiership",
              regionCode: "GB-SCT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095045,
              userFavourite: false,
              name: "Championship",
              regionCode: "GB-SCT",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094254,
              userFavourite: false,
              name: "Scottish Cup",
              regionCode: "GB-SCT",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461803,
          popular: false,
          name: "South Africa",
          regionCode: "ZA",
          groups: [
            {
              id: 2000050659,
              userFavourite: false,
              name: "Nedbank Cup",
              regionCode: "ZA",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000250636,
              userFavourite: false,
              name: "SA Premier Soccer League",
              regionCode: "ZA",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461814,
          popular: false,
          name: "Sweden",
          regionCode: "SE",
          groups: [
            {
              id: 1000095057,
              userFavourite: true,
              name: "Allsvenskan",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: true,
            },
            {
              id: 1000095052,
              userFavourite: false,
              name: "Superettan",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094744,
              userFavourite: false,
              name: "Division 1 N",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094745,
              userFavourite: false,
              name: "Division 1 S",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095059,
              userFavourite: false,
              name: "Svenska Cupen",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000176396,
              userFavourite: false,
              name: "Damallsvenskan (W)",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000095053,
              userFavourite: false,
              name: "Division 2 N",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000094184,
              userFavourite: false,
              name: "Division 2 NS",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 1000266381,
              userFavourite: false,
              name: "Division 2 SS",
              regionCode: "SE",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461815,
          popular: false,
          name: "Switzerland",
          regionCode: "CH",
          groups: [
            {
              id: 1000095020,
              userFavourite: false,
              name: "Super League",
              regionCode: "CH",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461821,
          popular: false,
          name: "Turkey",
          regionCode: "TR",
          groups: [
            {
              id: 1000095062,
              userFavourite: false,
              name: "Süper Lig",
              regionCode: "TR",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000151680,
          popular: false,
          name: "UEFA Championship U21",
          regionCode: "EU",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 2000113672,
          popular: false,
          name: "UEFA Nations League",
          regionCode: "EU",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 2000065880,
          popular: false,
          name: "UEFA Qualification U21",
          regionCode: "EU",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 1000461804,
          popular: false,
          name: "Ukraine",
          regionCode: "UA",
          groups: [
            {
              id: 1000171537,
              userFavourite: false,
              name: "Premier League",
              regionCode: "UA",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461760,
          popular: false,
          name: "Uruguay",
          regionCode: "UY",
          groups: [
            {
              id: 1000450453,
              userFavourite: false,
              name: "Primera Division",
              regionCode: "UY",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 1000461816,
          popular: false,
          name: "USA",
          regionCode: "US",
          groups: [
            {
              id: 1000095063,
              userFavourite: false,
              name: "MLS",
              regionCode: "US",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000065915,
              userFavourite: false,
              name: "NPSL",
              regionCode: "US",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000055612,
              userFavourite: false,
              name: "USL",
              regionCode: "US",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000050117,
          popular: false,
          name: "Venezuela",
          regionCode: "VE",
          groups: [
            {
              id: 2000050118,
              userFavourite: false,
              name: "Primera Division",
              regionCode: "VE",
              __typename: "EventGroup",
              popular: false,
            },
            {
              id: 2000083468,
              userFavourite: false,
              name: "Segunda Division",
              regionCode: "VE",
              __typename: "EventGroup",
              popular: false,
            },
          ],
        },
        {
          __typename: "EventGroup",
          id: 2000101172,
          popular: false,
          name: "World Cup (W)",
          regionCode: "WORLD",
          groups: [],
        },
        {
          __typename: "EventGroup",
          id: 2000116272,
          popular: false,
          name: "World Cup 2022",
          regionCode: "WORLD",
          groups: [],
        },
      ],
    },
  },
};
