export const coinsDefinitions = {
  landscape: [
    {
      id: "Frame1",
      order: 1,
      left: 0,
      top: 0,
      group: "big",
      width: 92,
      height: 88,
    },
    {
      id: "Frame2",
      order: 2,
      left: 82,
      top: 0,
      group: "medium",
      width: 52,
      height: 50,
    },
    {
      id: "Frame3",
      order: 3,
      left: 59,
      top: 55,
      group: "medium",
      width: 52,
      height: 50,
    },
    {
      id: "Frame4",
      order: 4,
      left: 0,
      top: 72,
      group: "medium",
      width: 52,
      height: 50,
    },
    {
      id: "Frame5",
      order: 5,
      left: -59,
      top: 55,
      group: "medium",
      width: 52,
      height: 50,
    },
    {
      id: "Frame6",
      order: 6,
      left: -82,
      top: 0,
      group: "medium",
      width: 52,
      height: 50,
    },
    {
      id: "Frame7",
      order: 7,
      left: -59,
      top: -55,
      group: "medium",
      width: 52,
      height: 50,
    },
    {
      id: "Frame8",
      order: 8,
      left: 0,
      top: -73,
      group: "medium",
      width: 52,
      height: 50,
    },
    {
      id: "Frame9",
      order: 9,
      left: 59,
      top: -55,
      group: "medium",
      width: 52,
      height: 50,
    },
    {
      id: "Frame10",
      order: 10,
      left: 108.5,
      top: -40.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame11",
      order: 11,
      left: 128.5,
      top: -13.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame12",
      order: 12,
      left: 128.5,
      top: 14.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame13",
      order: 13,
      left: 108.5,
      top: 41.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame14",
      order: 14,
      left: -108.5,
      top: 41.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame15",
      order: 15,
      left: -128.5,
      top: 14.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame16",
      order: 16,
      left: -128.5,
      top: -13.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame17",
      order: 17,
      left: -108.5,
      top: -40.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame18",
      order: 18,
      left: 108.5,
      top: -69.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame19",
      order: 19,
      left: 142.5,
      top: -40.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame20",
      order: 20,
      left: 160.5,
      top: -13.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame21",
      order: 21,
      left: 160.5,
      top: 14.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame22",
      order: 22,
      left: 142.5,
      top: 41.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame23",
      order: 23,
      left: 108.5,
      top: 70.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame24",
      order: 24,
      left: -108.5,
      top: 70.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame25",
      order: 25,
      left: -142.5,
      top: 41.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame26",
      order: 26,
      left: -160.5,
      top: 14.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame27",
      order: 27,
      left: -160.5,
      top: -13.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame28",
      order: 28,
      left: -142.5,
      top: -40.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame29",
      order: 29,
      left: -108.5,
      top: -69.5,
      group: "small",
      width: 25,
      height: 23,
    },
  ],
  portrait: [
    {
      id: "Frame1",
      order: 1,
      left: 0,
      top: 0,
      group: "big",
      width: 92,
      height: 88,
    },
    {
      id: "Frame2",
      order: 2,
      left: 0,
      top: -82,
      group: "medium",
      width: 52,
      height: 50,
    },
    {
      id: "Frame3",
      order: 3,
      left: 55,
      top: -59,
      group: "medium",
      width: 52,
      height: 50,
    },
    {
      id: "Frame4",
      order: 4,
      left: 72,
      top: 0,
      group: "medium",
      width: 52,
      height: 50,
    },
    {
      id: "Frame5",
      order: 5,
      left: 55,
      top: 59,
      group: "medium",
      width: 52,
      height: 50,
    },
    {
      id: "Frame6",
      order: 6,
      left: 0,
      top: 82,
      group: "medium",
      width: 52,
      height: 50,
    },
    {
      id: "Frame7",
      order: 7,
      left: -55,
      top: 59,
      group: "medium",
      width: 52,
      height: 50,
    },
    {
      id: "Frame8",
      order: 8,
      left: -73,
      top: 0,
      group: "medium",
      width: 52,
      height: 50,
    },
    {
      id: "Frame9",
      order: 9,
      left: -55,
      top: -59,
      group: "medium",
      width: 52,
      height: 50,
    },
    {
      id: "Frame10",
      order: 10,
      left: -40.5,
      top: -108.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame11",
      order: 11,
      left: -13.5,
      top: -128.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame12",
      order: 12,
      left: 14.5,
      top: -128.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame13",
      order: 13,
      left: 41.5,
      top: -108.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame14",
      order: 14,
      left: 41.5,
      top: 108.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame15",
      order: 15,
      left: 14.5,
      top: 128.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame16",
      order: 16,
      left: -13.5,
      top: 128.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame17",
      order: 17,
      left: -40.5,
      top: 108.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame18",
      order: 18,
      left: -69.5,
      top: -108.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame19",
      order: 19,
      left: -40.5,
      top: -142.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame20",
      order: 20,
      left: -13.5,
      top: -160.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame21",
      order: 21,
      left: 14.5,
      top: -160.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame22",
      order: 22,
      left: 41.5,
      top: -142.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame23",
      order: 23,
      left: 70.5,
      top: -108.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame24",
      order: 24,
      left: 70.5,
      top: 108.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame25",
      order: 25,
      left: 41.5,
      top: 142.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame26",
      order: 26,
      left: 14.5,
      top: 160.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame27",
      order: 27,
      left: -13.5,
      top: 160.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame28",
      order: 28,
      left: -40.5,
      top: 142.5,
      group: "small",
      width: 25,
      height: 23,
    },
    {
      id: "Frame29",
      order: 29,
      left: -69.5,
      top: 108.5,
      group: "small",
      width: 25,
      height: 23,
    },
  ],
};
