export const types = {
  FETCH_BLUERIBBON_JACKPOTS_HANDSHAKE: "FETCH_BLUERIBBON_JACKPOTS_HANDSHAKE",
  UPDATE_BLUERIBBON_JACKPOTS_HANDSHAKE: "UPDATE_BLUERIBBON_JACKPOTS_HANDSHAKE",
  SET_BLUE_RIBBON_JACKPOTS: "SET_BLUE_RIBBON_JACKPOTS",
  SET_SDK_POTS: "SET_SDK_POTS",
};
