export const types = {
  FETCH_BLUERIBBON_JACKPOTS_HANDSHAKE: "FETCH_BLUERIBBON_JACKPOTS_HANDSHAKE",
  UPDATE_BLUERIBBON_JACKPOTS_HANDSHAKE: "UPDATE_BLUERIBBON_JACKPOTS_HANDSHAKE",
  WIN_ANIMATION_RUNNING: "WIN_ANIMATION_RUNNING",
};
