export const types = {
  FETCH_BLUERIBBON_JACKPOTS_HANDSHAKE: "FETCH_BLUERIBBON_JACKPOTS_HANDSHAKE",
  UPDATE_BLUERIBBON_JACKPOTS_HANDSHAKE: "UPDATE_BLUERIBBON_JACKPOTS_HANDSHAKE",
  TURN_ON_START_GAMES_FEED: "TURN_ON_START_GAMES_FEED",
};
